"use client";

import { useEffect, useMemo, useRef, useState, type ChangeEvent } from "react";
import { Camera, Heart, MessageCircle, MoreHorizontal, Play, Send, Sparkles, Video, X } from "lucide-react";
import { PageHero } from "@/components/layout/page-hero";
import { Avatar } from "@/components/identity/avatar";
import { loadIdentity, type Identity } from "@/lib/identity";
import { canEditPost, createPost, deletePost, fileToPostPhoto, fileToPostVideo, formatSocialTime, loadPosts, savePosts, updatePost, type Post } from "@/lib/social";
import { feedback } from "@/lib/sensory";

type Tab="For you"|"Following"|"Proof";
const TABS:Tab[]=["For you","Following","Proof"];
const ACCENTS=["#4C8DFF","#3DDC97","#FF5C8A","#F5C542","#B28CFF"];

export default function SocialPage(){
 const [me,setMe]=useState<Identity|null>(null);const [posts,setPosts]=useState<Post[]>([]);const [tab,setTab]=useState<Tab>("For you");const [composer,setComposer]=useState(false);const [text,setText]=useState("");const [photo,setPhoto]=useState<string|null>(null);const [video,setVideo]=useState<string|null>(null);const [editing,setEditing]=useState<string|null>(null);const [replies,setReplies]=useState<string|null>(null);const [replyText,setReplyText]=useState("");const photoRef=useRef<HTMLInputElement>(null);const videoRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{setMe(loadIdentity());setPosts(loadPosts());window.addEventListener("livv-social",()=>setPosts(loadPosts()));return()=>window.removeEventListener("livv-social",()=>setPosts(loadPosts()));},[]);
 const filtered=useMemo(()=>posts.filter(p=>tab!=="Proof"||Boolean(p.photo||p.video)||p.text.toLowerCase().includes("proof")),[posts,tab]);
 const submit=()=>{if(!me||(!text.trim()&&!photo&&!video))return;if(editing) setPosts(updatePost(editing,{text:text.trim(),photo,video}));else{createPost({text:text.trim(),photo,video,track:null,allowReplies:true});setPosts(loadPosts());}setText("");setPhoto(null);setVideo(null);setEditing(null);setComposer(false);feedback("complete");};
 const like=(id:string)=>{const next=posts.map(p=>p.id===id?{...p,likes:p.likes+(p.likedByMe?-1:1),likedByMe:!p.likedByMe}:p);savePosts(next);setPosts(next);};
 const reply=(id:string)=>{if(!me||!replyText.trim())return;const next=posts.map(p=>p.id===id?{...p,replies:[...p.replies,{id:crypto.randomUUID(),author:{displayName:me.displayName,username:me.username,photo:me.photo,accent:me.accent},text:replyText.trim(),createdAt:Date.now()}]}:p);savePosts(next);setPosts(next);setReplyText("");};
 const pickPhoto=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setVideo(null);try{setPhoto(await fileToPostPhoto(f));}catch{}if(photoRef.current)photoRef.current.value="";};
 const pickVideo=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setPhoto(null);try{setVideo(await fileToPostVideo(f));}catch{}if(videoRef.current)videoRef.current.value="";};
 const edit=(p:Post)=>{setEditing(p.id);setText(p.text);setPhoto(p.photo);setVideo(p.video);setComposer(true);};
 return <main className="livv-social-page relative min-h-full overflow-hidden pb-28 text-white"><div className="px-4 pt-5"><PageHero eyebrow="Social" title="Community" subtitle="Share what you are doing. See what other people are building." accent="#3DDC97"/></div><section className="relative z-10 px-4 pt-5">
   <div className="rounded-[28px] border border-white/10 bg-white/[0.025] p-3"><div className="flex items-center gap-3 overflow-x-auto scrollbar-none">{["You","Maya","Andre","Nia","Jules"].map((name,i)=><button key={name} type="button" onClick={()=>name==="You"&&setComposer(true)} className="shrink-0 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-white/10 bg-white/[0.04]" style={{boxShadow:`0 0 18px ${ACCENTS[i]}25`}}><span className="text-[11px] font-bold" style={{color:ACCENTS[i]}}>{name[0]}</span></span><span className="mt-1 block text-[9px] text-white/55">{name}</span></button>)}<button type="button" onClick={()=>setComposer(true)} className="ml-auto grid h-12 w-12 shrink-0 place-items-center rounded-full bg-white text-black"><Sparkles size={18}/></button></div></div>
   <div className="mt-4 grid grid-cols-3 gap-1 rounded-2xl border border-white/10 bg-white/[0.025] p-1">{TABS.map(t=><button key={t} type="button" onClick={()=>setTab(t)} className={`rounded-xl py-2.5 text-[11px] font-semibold ${tab===t?"bg-white text-black":"text-white/50"}`}>{t}</button>)}</div>
   <button type="button" onClick={()=>setComposer(true)} className="mt-4 flex w-full items-center gap-3 rounded-[24px] border border-white/10 bg-white/[0.025] p-3 text-left"><Avatar identity={me?{displayName:me.displayName,photo:me.photo,accent:me.accent,tier:me.tier}:{displayName:"You",photo:null,accent:"#4C8DFF",tier:"spark"}} size={40}/><span className="flex-1 text-[13px] text-white/50">What are you working on?</span><span className="rounded-full bg-white px-3 py-2 text-[10px] font-bold text-black">POST</span></button>
   <div className="mt-5 space-y-4">{filtered.map(p=><article key={p.id} className="overflow-hidden rounded-[28px] border border-white/10 bg-white/[0.025]"><div className="flex items-center gap-3 p-4"><Avatar identity={p.author} size={40}/><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold">{p.author.displayName}</p><p className="text-[10px] text-white/45">@{p.author.username} · {formatSocialTime(p.createdAt,Date.now())}</p></div>{me?.username===p.author.username&&<button type="button" onClick={()=>edit(p)} className="grid h-9 w-9 place-items-center rounded-full text-white/45"><MoreHorizontal size={18}/></button>}</div>{p.text&&<p className="px-4 pb-4 text-[15px] leading-6 text-white/85">{p.text}</p>}{p.photo&&<img src={p.photo} alt="" className="block max-h-[620px] w-full object-cover"/>}{p.video&&<video src={p.video} controls playsInline className="block max-h-[620px] w-full bg-black object-contain"/>}<div className="flex items-center gap-1 border-t border-white/10 p-3"><button type="button" onClick={()=>like(p.id)} className="flex items-center gap-1 rounded-full px-3 py-2 text-[11px] text-white/60"><Heart size={17} fill={p.likedByMe?"currentColor":"none"}/> {p.likes}</button>{p.allowReplies&&<button type="button" onClick={()=>setReplies(replies===p.id?null:p.id)} className="flex items-center gap-1 rounded-full px-3 py-2 text-[11px] text-white/60"><MessageCircle size={17}/> {p.replies.length}</button>}{me?.username===p.author.username&&<button type="button" onClick={()=>{setPosts(deletePost(p.id));}} className="ml-auto rounded-full px-3 py-2 text-[11px] text-red-300/70">Delete</button>}</div>{replies===p.id&&<div className="border-t border-white/10 p-4"><div className="space-y-2">{p.replies.map(r=><p key={r.id} className="text-[12px] leading-5 text-white/65"><b className="text-white/85">{r.author.displayName}</b> {r.text}</p>)}</div><div className="mt-3 flex gap-2"><input value={replyText} onChange={e=>setReplyText(e.target.value)} placeholder="Write a reply" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/10 px-3 py-2.5 text-[12px] outline-none"/><button type="button" onClick={()=>reply(p.id)} className="grid h-10 w-10 place-items-center rounded-xl bg-white text-black"><Send size={15}/></button></div></div>}</article>)}</div>
 </section>
 {composer&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/70 p-3 backdrop-blur-md" onClick={()=>setComposer(false)}><div className="w-full max-w-xl rounded-[30px] border border-white/10 bg-[#101116] p-5" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#3DDC97]">{editing?"Edit post":"Create post"}</p><h2 className="font-display mt-1 text-[22px] font-semibold">Say something real.</h2></div><button type="button" onClick={()=>setComposer(false)} className="grid h-9 w-9 place-items-center rounded-full border border-white/10"><X size={17}/></button></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="What are you building, learning, training, or thinking about?" className="mt-5 min-h-36 w-full resize-none rounded-2xl border border-white/10 bg-black/15 p-4 text-[13px] leading-relaxed outline-none placeholder:text-white/35"/>{(photo||video)&&<div className="mt-3 rounded-2xl border border-white/10 p-2">{photo&&<img src={photo} alt="Preview" className="max-h-56 w-full rounded-xl object-cover"/>}{video&&<video src={video} controls className="max-h-56 w-full rounded-xl"/>}</div>}<div className="mt-4 flex items-center gap-2"><button type="button" onClick={()=>photoRef.current?.click()} className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2.5 text-[11px]"><Camera size={15}/> Photo</button><button type="button" onClick={()=>videoRef.current?.click()} className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2.5 text-[11px]"><Video size={15}/> Video</button><button type="button" onClick={submit} className="ml-auto rounded-full bg-white px-5 py-2.5 text-[11px] font-bold text-black">{editing?"Save":"Post"}</button></div><input ref={photoRef} type="file" accept="image/*" onChange={pickPhoto} className="hidden"/><input ref={videoRef} type="file" accept="video/*" onChange={pickVideo} className="hidden"/></div></div>}
 </main>;
}
