"use client";

import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { Camera, Heart, MessageCircle, Video } from "lucide-react";
import { PageHero } from "@/components/layout/page-hero";
import { Avatar } from "@/components/identity/avatar";
import { loadIdentity, type Identity } from "@/lib/identity";
import { fileToPostPhoto, fileToPostVideo, formatSocialTime, loadPosts, savePosts, type Post } from "@/lib/social";

const ACCENTS = ["#4C8DFF", "#3DDC97", "#FF5C8A", "#F5C542", "#7C6BFF"];
type Tab = "For you" | "Following" | "Proof" | "Watch";

export default function ConnectPage() {
 const [me,setMe]=useState<Identity|null>(null);const [posts,setPosts]=useState<Post[]>([]);const [tab,setTab]=useState<Tab>("For you");const [composer,setComposer]=useState(false);
 const [text,setText]=useState("");const [photo,setPhoto]=useState<string|null>(null);const [video,setVideo]=useState<string|null>(null);const [editing,setEditing]=useState<string|null>(null);const [replyText,setReplyText]=useState("");const [replyOpen,setReplyOpen]=useState<string|null>(null);
 const photoRef=useRef<HTMLInputElement>(null);const videoRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{setMe(loadIdentity());setPosts(loadPosts());const sync=()=>setPosts(loadPosts());window.addEventListener("livv-social",sync);return()=>window.removeEventListener("livv-social",sync);},[]);
 const filtered=posts.filter(p=>tab==="For you"?true:tab==="Following"?p.author.username===me?.username:tab==="Proof"?Boolean(p.photo||p.video):Boolean(p.video));
 const like=(id:string)=>{const next=posts.map(p=>p.id===id?{...p,likes:p.likes+(p.likedByMe?-1:1),likedByMe:!p.likedByMe}:p);savePosts(next);setPosts(next);};
 const reply=(id:string)=>{if(!me||!replyText.trim())return;const next=posts.map(p=>p.id===id?{...p,replies:[...p.replies,{id:crypto.randomUUID(),author:{displayName:me.displayName,username:me.username,photo:me.photo},text:replyText.trim(),createdAt:Date.now()}]}:p);savePosts(next);setPosts(next);setReplyText("");setReplyOpen(null);};
 const pickPhoto=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setVideo(null);try{setPhoto(await fileToPostPhoto(f));}catch{}if(photoRef.current)photoRef.current.value="";};
 const pickVideo=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setPhoto(null);try{setVideo(await fileToPostVideo(f));}catch{}if(videoRef.current)videoRef.current.value="";};
 const edit=(p:Post)=>{setEditing(p.id);setText(p.text);setPhoto(p.photo);setVideo(p.video);setComposer(true);};
 const submit=()=>{if(!me||(!text.trim()&&!photo&&!video))return;let next:Post[];if(editing){next=posts.map(p=>p.id===editing?{...p,text:text.trim(),photo,video,kind:photo?"photo":video?"video":"text"}:p);}else{next=[{id:crypto.randomUUID(),createdAt:Date.now(),author:{displayName:me.displayName||"You",username:me.username||"you",photo:me.photo},text:text.trim(),photo,video,kind:photo?"photo":video?"video":"text",track:null,allowReplies:true,likes:0,likedByMe:false,replies:[]},...posts];}savePosts(next);setPosts(next);setComposer(false);setEditing(null);setText("");setPhoto(null);setVideo(null);};
 return <main className="livv-social-page relative min-h-full overflow-hidden pb-28 text-[rgb(var(--livv-fg))]"><div className="mx-auto max-w-lg px-4 pt-4"><PageHero title="Social" subtitle="Share proof, training, and thoughts with the LIVV community." /><div className="mt-4 flex gap-2 overflow-x-auto scrollbar-none">{(["For you","Following","Proof","Watch"] as Tab[]).map(t=><button key={t} type="button" onClick={()=>setTab(t)} className={`shrink-0 rounded-full px-4 py-2 text-[11px] font-semibold ${tab===t?"bg-white text-black":"border border-white/10 bg-white/[0.03] text-white/60"}`}>{t}</button>)}</div>
   <div className="mt-4 rounded-[28px] border border-white/10 bg-white/[0.025] p-3"><div className="flex items-center gap-3 overflow-x-auto scrollbar-none">{["You","Maya","Andre","Nia","Jules"].map((name,i)=><button key={name} type="button" onClick={()=>name==="You"&&setComposer(true)} className="shrink-0 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-white/10 bg-white/[0.04]" style={{boxShadow:`0 0 18px ${ACCENTS[i]}25`}}><span className="text-[11px] font-bold" style={{color:ACCENTS[i]}}>{name[0]}</span></span><span className="mt-1 block text-[9px] text-white/55">{name}</span></button>)}<button type="button" onClick={()=>setComposer(true)} className="ml-auto shrink-0 rounded-full bg-white px-4 py-2 text-[11px] font-bold text-black">Post</button></div></div>
   <button type="button" onClick={()=>setComposer(true)} className="mt-3 flex w-full items-center gap-3 rounded-[24px] border border-white/10 bg-white/[0.03] p-3 text-left"><Avatar identity={me?{displayName:me.displayName,photo:me.photo,accent:me.accent,tier:me.tier}:{displayName:"You",photo:null,accent:"#4C8DFF",tier:"spark"}} size={40}/><span className="flex-1 text-[13px] text-white/50">What are you working on?</span><span className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] font-semibold text-white/70">Compose</span></button>
   <div className="mt-4 space-y-3">{filtered.map(p=><article key={p.id} className="rounded-[28px] border border-white/10 bg-white/[0.03] p-4"><div className="flex items-start gap-3"><Avatar identity={p.author} size={40}/><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold">{p.author.displayName}</p><p className="text-[10px] text-white/45">@{p.author.username} · {formatSocialTime(p.createdAt,Date.now())}</p></div>{me&&p.author.username===me.username&&<button type="button" onClick={()=>edit(p)} className="text-[10px] text-white/40">Edit</button>}</div>{p.text&&<p className="mt-3 text-[13px] leading-relaxed text-white/85">{p.text}</p>}{p.photo&&<img src={p.photo} alt="" className="mt-3 max-h-80 w-full rounded-2xl object-cover"/>}{p.video&&<video src={p.video} controls className="mt-3 max-h-80 w-full rounded-2xl"/>}<div className="mt-3 flex items-center gap-4"><button type="button" onClick={()=>like(p.id)} className="flex items-center gap-1.5 text-[11px] text-white/55"><Heart size={15} className={p.likedByMe?"fill-rose-400 text-rose-400":""}/>{p.likes}</button><button type="button" onClick={()=>setReplyOpen(replyOpen===p.id?null:p.id)} className="flex items-center gap-1.5 text-[11px] text-white/55"><MessageCircle size={15}/>{p.replies.length}</button></div>{replyOpen===p.id&&<div className="mt-3 flex gap-2"><input value={replyText} onChange={e=>setReplyText(e.target.value)} placeholder="Reply…" className="flex-1 rounded-full border border-white/10 bg-black/20 px-4 py-2 text-[12px] outline-none"/><button type="button" onClick={()=>reply(p.id)} className="rounded-full bg-white px-4 py-2 text-[11px] font-bold text-black">Send</button></div>}{p.replies.slice(-2).map(r=><p key={r.id} className="mt-2 text-[11px] text-white/50"><span className="font-semibold text-white/70">{r.author.displayName}</span> {r.text}</p>)}</article>)}{filtered.length===0&&<div className="rounded-[28px] border border-dashed border-white/10 p-8 text-center text-[13px] text-white/40">No posts in this view yet. Share the first one.</div>}</div></div>
 {composer&&<div className="fixed inset-0 z-[90] grid place-items-end bg-black/70 p-4 backdrop-blur-sm sm:place-items-center"><div className="w-full max-w-md rounded-[28px] border border-white/10 bg-[#0b0d12] p-5"><div className="flex items-center justify-between"><p className="text-[12px] font-semibold uppercase tracking-[0.2em] text-white/40">{editing?"Edit post":"New post"}</p><button type="button" onClick={()=>{setComposer(false);setEditing(null);setText("");setPhoto(null);setVideo(null);}} className="text-[12px] text-white/45">Close</button></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="What are you building, learning, training, or thinking about?" className="mt-5 min-h-36 w-full resize-none rounded-2xl border border-white/10 bg-black/15 p-4 text-[13px] leading-relaxed outline-none placeholder:text-white/35"/>{(photo||video)&&<div className="mt-3 rounded-2xl border border-white/10 p-2">{photo&&<img src={photo} alt="Preview" className="max-h-56 w-full rounded-xl object-cover"/>}{video&&<video src={video} controls className="max-h-56 w-full rounded-xl"/>}</div>}<div className="mt-4 flex items-center gap-2"><button type="button" onClick={()=>photoRef.current?.click()} className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2.5 text-[11px]"><Camera size={15}/> Photo</button><button type="button" onClick={()=>videoRef.current?.click()} className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2.5 text-[11px]"><Video size={15}/> Video</button><button type="button" onClick={submit} className="ml-auto rounded-full bg-white px-5 py-2.5 text-[11px] font-bold text-black">{editing?"Save":"Post"}</button></div><input ref={photoRef} type="file" accept="image/*" onChange={pickPhoto} className="hidden"/><input ref={videoRef} type="file" accept="video/*" onChange={pickVideo} className="hidden"/></div></div>}</main>;
}
