/**
 * Entitlements & payments boundary.
 * Spark is free. Paid tiers go through Stripe Checkout when configured.
 * Demo unlock remains for non-production QA only.
 * Server entitlements are authoritative whenever available.
 */
import type { LivvTier } from "./identity";
import { loadIdentity, patchIdentity } from "./identity";
import { ensureAnonymousSession } from "./supabase/anon-session";
import { getSupabaseBrowserClient, isSupabaseConfigured } from "./supabase/client";
const ENTITLEMENTS_KEY="livv-entitlements-v1";
export type Entitlements={tier:LivvTier;source:"stripe"|"demo"|"spark";expiresAt:string|null;stripeCustomerId?:string;stripeSubscriptionId?:string};
export type ServerEntitlement={tier:LivvTier;status:string;stripe_customer_id:string|null;stripe_subscription_id:string|null;current_period_end:string|null};
let serverCache:ServerEntitlement|null|undefined=undefined;let hydrateInflight:Promise<void>|null=null;
export function isStripeConfigured(){return Boolean(typeof process!=="undefined"&&process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY);}
export function isDemoUnlock(){if(typeof window==="undefined"||process.env.NODE_ENV==="production")return false;return process.env.NEXT_PUBLIC_LIVV_DEMO_UNLOCK==="1"&&window.localStorage.getItem("livv-demo-unlock")==="1";}
function isLivvTier(v:string):v is LivvTier{return v==="spark"||v==="rise"||v==="apex"||v==="circle";}
function rank(t:LivvTier){return {spark:0,rise:1,apex:2,circle:3}[t]??0;}
export function loadEntitlements():Entitlements{if(typeof window==="undefined")return{tier:"spark",source:"spark",expiresAt:null};try{const raw=window.localStorage.getItem(ENTITLEMENTS_KEY);if(!raw){const e:Entitlements={tier:"spark",source:"spark",expiresAt:null};window.localStorage.setItem(ENTITLEMENTS_KEY,JSON.stringify(e));return e;}const parsed=JSON.parse(raw) as Partial<Entitlements>;if(!isLivvTier(String(parsed.tier))||!(["stripe","demo","spark"] as string[]).includes(String(parsed.source)))return{tier:"spark",source:"spark",expiresAt:null};return{tier:parsed.tier as LivvTier,source:parsed.source as Entitlements["source"],expiresAt:typeof parsed.expiresAt==="string"?parsed.expiresAt:null,stripeCustomerId:typeof parsed.stripeCustomerId==="string"?parsed.stripeCustomerId:undefined,stripeSubscriptionId:typeof parsed.stripeSubscriptionId==="string"?parsed.stripeSubscriptionId:undefined};}catch{return{tier:"spark",source:"spark",expiresAt:null};}}
function saveEntitlements(e:Entitlements){if(typeof window==="undefined")return;window.localStorage.setItem(ENTITLEMENTS_KEY,JSON.stringify(e));window.dispatchEvent(new Event("livv-billing"));}
export function applyStripeEntitlement(input:{tier:LivvTier;customerId?:string|null;subscriptionId?:string|null}){const e:Entitlements={tier:input.tier,source:"stripe",expiresAt:null,stripeCustomerId:input.customerId||undefined,stripeSubscriptionId:input.subscriptionId||undefined};saveEntitlements(e);patchIdentity({tier:input.tier});return e;}
export function resolveEffectiveEntitlement():Entitlements{const local=loadEntitlements();if(isDemoUnlock())return local.source==="demo"||local.tier!=="spark"?local:{...local,source:"demo"};if(isSupabaseConfigured()){if(serverCache===undefined)return{tier:"spark",source:"spark",expiresAt:null};if(!serverCache)return{tier:"spark",source:"spark",expiresAt:null};const status=serverCache.status.toLowerCase(),tier=isLivvTier(serverCache.tier)?serverCache.tier:"spark";if(status==="active"||status==="trialing"||status==="past_due")return{tier,source:"stripe",expiresAt:serverCache.current_period_end,stripeCustomerId:serverCache.stripe_customer_id||undefined,stripeSubscriptionId:serverCache.stripe_subscription_id||undefined};return{tier:"spark",source:"stripe",expiresAt:serverCache.current_period_end,stripeCustomerId:serverCache.stripe_customer_id||undefined,stripeSubscriptionId:serverCache.stripe_subscription_id||undefined};}return local;}
export function getEffectiveTier(){return resolveEffectiveEntitlement().tier;}
export function canAccessTier(tier:LivvTier){return tier==="spark"||isDemoUnlock()||rank(resolveEffectiveEntitlement().tier)>=rank(tier);}
export async function hydrateServerEntitlement():Promise<void>{if(typeof window==="undefined")return;if(!isSupabaseConfigured()){serverCache=null;return;}if(hydrateInflight)return hydrateInflight;hydrateInflight=(async()=>{try{await ensureAnonymousSession();const client=getSupabaseBrowserClient();if(!client)return;const{data:sessionData}=await client.auth.getSession();const uid=sessionData.session?.user?.id;if(!uid){serverCache=null;return;}const{data,error}=await client.from("entitlements").select("tier,status,stripe_customer_id,stripe_subscription_id,current_period_end").eq("user_id",uid).maybeSingle();if(error){serverCache=null;console.info("[billing] server entitlement read failed — defaulting to Spark",error.message);return;}serverCache=data?{tier:isLivvTier(String(data.tier))?(data.tier as LivvTier):"spark",status:String(data.status||"none"),stripe_customer_id:data.stripe_customer_id??null,stripe_subscription_id:data.stripe_subscription_id??null,current_period_end:data.current_period_end??null}:null;saveEntitlements(resolveEffectiveEntitlement());patchIdentity({tier:resolveEffectiveEntitlement().tier});window.dispatchEvent(new Event("livv-billing"));}catch(err){serverCache=null;console.info("[billing] hydrate failed — defaulting to Spark",err);}finally{hydrateInflight=null;}})();return hydrateInflight;}
export function invalidateServerEntitlementCache(){serverCache=undefined;}
export type UpgradeResult={ok:true;tier:LivvTier}|{ok:false;reason:"payments_required"|"stripe_not_configured"|"already"|"redirecting"};
export function requestTierChange(tier:LivvTier):UpgradeResult{const current=getEffectiveTier();if(tier===current&&canAccessTier(tier))return{ok:true,tier};if(tier==="spark"){saveEntitlements({tier:"spark",source:"spark",expiresAt:null});patchIdentity({tier:"spark"});serverCache=undefined;return{ok:true,tier:"spark"};}if(isDemoUnlock()){saveEntitlements({tier,source:"demo",expiresAt:null});patchIdentity({tier});return{ok:true,tier};}if(!isStripeConfigured())return{ok:false,reason:"stripe_not_configured"};return{ok:false,reason:"payments_required"};}
async function getAuthHeader(){if(!isSupabaseConfigured())return{};try{await ensureAnonymousSession();const client=getSupabaseBrowserClient();if(!client)return{};const{data}=await client.auth.getSession();const token=data.session?.access_token;if(!token)return{};return{Authorization:`Bearer ${token}`};}catch{return{};}}
async function authenticatedFetch(input:RequestInfo|URL,init:RequestInit={}){const headers=new Headers(init.headers);const auth=await getAuthHeader();if(auth.Authorization)headers.set("Authorization",auth.Authorization);if(!headers.has("Content-Type"))headers.set("Content-Type","application/json");return fetch(input,{...init,headers});}
export async function startCheckout(tier:Exclude<LivvTier,"spark">):Promise<{ok:boolean;error?:string}>{if(typeof window==="undefined")return{ok:false,error:"client only"};const me=loadIdentity();try{const authHeader=await getAuthHeader();if(isSupabaseConfigured()&&!authHeader.Authorization)return{ok:false,error:"Identity session missing. Reload LIVV and try checkout again."};const res=await authenticatedFetch("/api/stripe/checkout",{method:"POST",body:JSON.stringify({tier,username:me.username})});const data=await res.json() as{url?:string;error?:string};if(!res.ok||!data.url)return{ok:false,error:data.error||"Checkout unavailable"};window.location.href=data.url;return{ok:true};}catch{return{ok:false,error:"Network error starting checkout"};}}
export async function openBillingPortal():Promise<{ok:boolean;error?:string}>{if(typeof window==="undefined")return{ok:false,error:"client only"};try{const authHeader=await getAuthHeader();if(isSupabaseConfigured()&&!authHeader.Authorization)return{ok:false,error:"Identity session missing. Reload LIVV and try again."};const res=await authenticatedFetch("/api/stripe/portal",{method:"POST"});const data=await res.json() as{url?:string;error?:string};if(!res.ok||!data.url)return{ok:false,error:data.error||"Portal unavailable"};window.location.href=data.url;return{ok:true};}catch{return{ok:false,error:"Network error opening portal"};}}
export function enableDemoUnlock(){if(typeof window!=="undefined"&&process.env.NODE_ENV!=="production"&&process.env.NEXT_PUBLIC_LIVV_DEMO_UNLOCK==="1")window.localStorage.setItem("livv-demo-unlock","1");}
export function paidTierMessage(tier:LivvTier){const names:Record<LivvTier,string>={spark:"Spark",rise:"Rise",apex:"Apex",circle:"Inner Circle"};return isStripeConfigured()?`Continue to secure checkout to unlock ${names[tier]}.`:`${names[tier]} unlocks when billing goes live. You’re on Spark until then.`;}
