import { dayKey } from "./dates";
import { worldState } from "./daily";
import { loadIdentity } from "./identity";
import { isCheckedInToday,loadRecord,livePillars,todaysObjectives } from "./record";
export type Move={title:string;reason:string;cta:string;href:string;pillar?:string};export type DayPillar={id:string;name:string;done:boolean};
const CORE_PILLARS=["body","mind","career","finance","social"] as const;
export function contextGreeting(now=new Date(),rec=loadRecord()){const me=loadIdentity(),first=(me.displayName||"there").split(" ")[0],hour=now.getHours(),checked=isCheckedInToday(rec),objs=todaysObjectives(rec),done=objs.filter(o=>o.completed).length;let salutation=`Hey, ${first}`;if(hour<5)salutation=`Still up, ${first}`;else if(hour<12)salutation=`Morning, ${first}`;else if(hour<17)salutation=`Afternoon, ${first}`;else if(hour<21)salutation=`Evening, ${first}`;else salutation=`Wind down, ${first}`;let line="Here's what matters today.";if(rec.streak===0&&rec.workoutsCompleted===0&&done===0)line="Start with one thing today.";else if(!checked&&hour>=20)line="Still time to log one action.";else if(checked&&done>=Math.max(1,objs.length-1))line="Solid day. Don't force more.";else if(rec.streak>=6)line=`${rec.streak}-day streak. Keep it going.`;else if(rec.streak>=2)line="A few days in a row. Keep going.";else if(done===0&&hour>=14)line="Nothing done yet. Still recoverable.";return{salutation,line};}
export function nextMove(rec=loadRecord()):Move{const today=dayKey(),day=rec.days[today],objs=todaysObjectives(rec),incomplete=objs.find(o=>!o.completed);if(!day?.workout)return{title:"Train your body",reason:"You haven't trained yet today.",cta:"Train",href:"/home/train",pillar:"Body"};if(incomplete){const map:Record<string,{title:string;cta:string;href:string}>={Body:{title:"Train your body",cta:"Open Train",href:"/home/train"},Mind:{title:"Clear your mind",cta:"Open Mind",href:"/home/mind"},Career:{title:"Finish the priority",cta:"Open Daily",href:"/home/daily"},Finance:{title:"Protect your money",cta:"Open Daily",href:"/home/daily"},Social:{title:"Reach someone real",cta:"Open Daily",href:"/home/daily"}};const m=map[incomplete.pillar]||{title:incomplete.title,cta:"Open Daily",href:"/home/daily"};return{title:m.title,reason:incomplete.title,cta:m.cta,href:m.href,pillar:incomplete.pillar};}if(!isCheckedInToday(rec))return{title:"Check in",reason:"Close the day so it counts.",cta:"Check in",href:"/home",pillar:"Life"};return{title:"Day is done",reason:"Today is logged. Review your week if you want.",cta:"View progress",href:"/home/progress"};}
export function dailyPillarStatus(rec=loadRecord()):DayPillar[]{const today=dayKey(),day=rec.days[today],objs=todaysObjectives(rec);return CORE_PILLARS.map(id=>{const name=id[0].toUpperCase()+id.slice(1);let done=false;if(id==="body")done=Boolean(day?.workout)||objs.some(o=>o.pillar==="Body"&&o.completed);else done=objs.some(o=>o.pillar.toLowerCase()===id&&o.completed);return{id,name,done};});}
export function strongestPillar(rec=loadRecord()){return[...livePillars(rec)].sort((a,b)=>b.level-a.level||b.progress-a.progress)[0];}
export function needsAttention(rec=loadRecord()){return[...livePillars(rec)].sort((a,b)=>a.level-b.level||a.progress-b.progress)[0];}
export function focusCard(date=new Date()){const w=worldState(date);return{theme:w.title,principle:w.line,detail:w.focus};}
export function actionsCompletedCount(rec=loadRecord()){const pillars=dailyPillarStatus(rec),checked=isCheckedInToday(rec)?1:0,pillarDone=pillars.filter(p=>p.done).length;return{done:Math.min(6,pillarDone+checked),total:6,pillars};}
