export type ShareTemplate = "evolution" | "daily" | "workout" | "streak" | "life" | "weekly" | "milestone" | "identity" | "editorial";
export type ShareFont = "sans" | "display" | "mono" | "serif";
export type ShareLogo = "auto" | "white" | "black";
export type ShareCardData = {displayName:string;username:string;level:number;evolutionName:string;streak:number;tierLabel:string;tierColor:string;embers:number;workoutsCompleted:number;dailyScore:number;bodyScore:number;weeklyActive:number;weeklyWorkouts:number;mindSessions:number;customPhoto?:string|null;backgroundSrc?:string|null;workoutName:string;focus:string;duration:string;exerciseCount:number;font?:ShareFont;textColor?:string;logo?:ShareLogo};
const W=1080,H=1350; const F:Record<ShareFont,string>={sans:"Arial,Helvetica,sans-serif",display:"Arial Black,Arial,sans-serif",mono:"monospace",serif:"Georgia,serif"};
const img=(s:string)=>new Promise<HTMLImageElement>((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=s});
const put=(c:CanvasRenderingContext2D,s:string,x:number,y:number,n:number,w:number,col:string,f:ShareFont,align:CanvasTextAlign="left")=>{c.font=`${w} ${n}px ${F[f]}`;c.fillStyle=col;c.textAlign=align;c.fillText(s,x,y)};
const track=(c:CanvasRenderingContext2D,s:string,x:number,y:number,n:number,col:string,f:ShareFont,align:CanvasTextAlign="left")=>{c.font=`650 ${n}px ${F[f]}`;c.fillStyle=col;c.textAlign=align;const gap=n*.16;const width=c.measureText(s).width+gap*(s.length-1);let xx=align==="center"?x-width/2:x;for(const ch of s){c.fillText(ch,xx,y);xx+=c.measureText(ch).width+gap}};
async function background(c:CanvasRenderingContext2D,src:string|null,accent:string){c.fillStyle="#080a0d";c.fillRect(0,0,W,H);if(src)try{const i=await img(src),scale=Math.max(W/i.naturalWidth,H/i.naturalHeight),sw=W/scale,sh=H/scale;c.drawImage(i,(i.naturalWidth-sw)/2,(i.naturalHeight-sh)/2,sw,sh,0,0,W,H)}catch{}const g=c.createLinearGradient(0,0,0,H);g.addColorStop(0,"rgba(0,0,0,.18)");g.addColorStop(.5,"rgba(0,0,0,.3)");g.addColorStop(1,"rgba(0,0,0,.82)");c.fillStyle=g;c.fillRect(0,0,W,H);const r=c.createRadialGradient(850,170,0,850,170,650);r.addColorStop(0,accent+"55");r.addColorStop(1,"transparent");c.fillStyle=r;c.fillRect(0,0,W,H)}
async function logo(c:CanvasRenderingContext2D,choice:ShareLogo){const src=choice==="black"?"/LIVV%20Pillars%20Logo%20-%20BLACK.PNG":"/LIVV%20Pillars%20Logo%20-%20WHITE.PNG";try{const i=await img(src),s=Math.min(290/i.naturalWidth,100/i.naturalHeight);c.drawImage(i,72,42,i.naturalWidth*s,i.naturalHeight*s)}catch{put(c,"LIVV",72,90,42,800,"#fff","sans")}}
function line(c:CanvasRenderingContext2D,y:number,col:string){c.strokeStyle=col;c.lineWidth=1.5;c.beginPath();c.moveTo(72,y);c.lineTo(W-72,y);c.stroke()}
function metric(c:CanvasRenderingContext2D,l:string,v:string,x:number,y:number,col:string,f:ShareFont){track(c,l,x,y,12,col,f);put(c,v,x,y+47,34,650,col,f)}
export async function renderLIVVShareCard(t:ShareTemplate,d:ShareCardData):Promise<Blob>{const c=document.createElement("canvas"),f=d.font||"sans",col=d.textColor||"#fff",muted=col.toLowerCase()==="#fff"?"rgba(255,255,255,.68)":"rgba(0,0,0,.62)";c.width=W;c.height=H;const x=c.getContext("2d");if(!x)throw Error("canvas");await background(x,d.backgroundSrc||d.customPhoto||null,d.tierColor||"#1769ff");await logo(x,d.logo||"white");
if(t==="evolution"){track(x,"LEVEL",W/2,255,26,muted,f,"center");put(x,String(d.level),W/2,575,340,800,col,f,"center");track(x,"EVOLVING",W/2,650,34,col,f,"center");put(x,d.displayName.slice(0,28),W/2,1130,36,600,col,f,"center");put(x,`@${d.username}`.slice(0,32),W/2,1164,18,500,muted,f,"center");line(x,1200,muted);metric(x,"STREAK",`${d.streak} DAYS`,96,1250,col,f);metric(x,"WORKOUTS",String(d.workoutsCompleted),360,1250,col,f);metric(x,"MIND",String(d.mindSessions),620,1250,col,f);metric(x,"LIFE",`${d.bodyScore}%`,835,1250,col,f)}
else if(t==="daily"){track(x,"TODAY",W/2,270,30,col,f,"center");put(x,String(d.dailyScore),W/2,525,300,800,col,f,"center");track(x,"DAILY SCORE",W/2,580,25,muted,f,"center");line(x,650,muted);metric(x,"MOVEMENT",d.weeklyWorkouts?"✓":"—",100,715,col,f);metric(x,"MIND",d.mindSessions?"✓":"—",330,715,col,f);metric(x,"NUTRITION",`${d.dailyScore}%`,560,715,col,f);metric(x,"DISCIPLINE",d.streak?"✓":"—",800,715,col,f)}
else if(t==="workout"){track(x,"TRAIN",72,300,22,muted,f);put(x,d.workoutName.slice(0,28),72,425,72,800,col,f);put(x,`${d.focus} • ${d.duration}`,72,480,25,500,muted,f);line(x,550,muted);metric(x,"MOVES",String(d.exerciseCount),92,635,col,f);metric(x,"LEVEL",String(d.level),340,635,col,f);metric(x,"STREAK",`${d.streak} DAYS`,588,635,col,f);metric(x,"COMPLETION","100%",836,635,col,f)}
else if(t==="streak"){put(x,String(d.streak),W/2,675,430,800,col,f,"center");track(x,"DAY STREAK",W/2,745,35,col,f,"center");line(x,800,muted);track(x,d.streak>=30?"STILL SHOWING UP.":"KEEP SHOWING UP.",W/2,865,18,muted,f,"center");put(x,d.displayName.slice(0,28),W/2,1115,27,600,col,f,"center")}
else if(t==="life"){track(x,"LIFE AREA",72,315,20,muted,f);put(x,"BODY",72,390,78,800,col,f);x.beginPath();x.arc(270,675,145,-Math.PI/2,-Math.PI/2+Math.PI*2*d.bodyScore/100);x.strokeStyle=d.tierColor||"#1769ff";x.lineWidth=28;x.stroke();put(x,`${d.bodyScore}%`,270,690,54,700,col,f,"center");[["MIND",d.mindSessions?78:0],["FOOD",d.dailyScore],["HOME",67],["ENVIRONMENT",71],["DISCIPLINE",d.streak?89:0]].forEach(([l,v],i)=>{track(x,String(l),520,550+i*72,14,muted,f);put(x,`${v}%`,950,550+i*72,18,600,col,f,"right")})}
else if(t==="weekly"){track(x,"THIS WEEK",72,330,22,muted,f);put(x,`+${Math.max(0,d.weeklyActive*3)}%`,72,510,150,800,col,f);track(x,"EVOLUTION SCORE",78,560,25,col,f);line(x,620,muted);metric(x,"WORKOUTS",String(d.weeklyWorkouts),92,700,col,f);metric(x,"DAYS ACTIVE",String(d.weeklyActive),380,700,col,f);metric(x,"MIND SESSIONS",String(d.mindSessions),680,700,col,f)}
else if(t==="milestone"){track(x,"MILESTONE",W/2,350,24,muted,f,"center");const m=d.streak>=100?100:d.streak>=30?30:7;put(x,String(m),W/2,760,360,800,col,f,"center");track(x,"DAYS OF SHOWING UP",W/2,850,24,col,f,"center")}
else if(t==="identity"){track(x,"LIVV IDENTITY",72,310,18,muted,f);put(x,d.displayName.slice(0,24),72,400,48,750,col,f);put(x,`@${d.username}`.slice(0,30),72,435,18,500,muted,f);line(x,500,muted);metric(x,"LIVV LEVEL",String(d.level),92,585,col,f);metric(x,"TIER",d.tierLabel.toUpperCase(),380,585,col,f);metric(x,"STREAK",`${d.streak} DAYS`,92,730,col,f);metric(x,"EVOLUTION SCORE",String(d.dailyScore),380,730,col,f)}
else {track(x,"PROGRESS",72,365,18,muted,f);put(x,"LOOKS GOOD",72,450,70,800,col,f);put(x,"ON YOU.",72,520,70,800,col,f);line(x,930,muted)}
return new Promise((ok,no)=>c.toBlob(b=>b?ok(b):no(Error("blob")),"image/png"))}
export const renderProfileShareCard=(d:ShareCardData)=>renderLIVVShareCard("evolution",d);export const renderWorkoutShareCard=(d:ShareCardData)=>renderLIVVShareCard("workout",d);
export async function shareOrDownloadBlob(blob:Blob,filename:string,title:string){const file=new File([blob],filename,{type:"image/png"});if(typeof navigator!=="undefined"&&navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title,text:title});return "shared"}catch{}}const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);return "downloaded"}
