export type VaultModule = {
  id: string;
  title: string;
  blurb: string;
  kind: "protocol" | "tool" | "program" | "series" | "lab";
  meta: string;
  downloadable?: boolean;
  steps?: string[];
  body?: string[];
};

export const VAULT_MODULES: VaultModule[] = [
  {
    id: "sleep-reset-7",
    title: "7-Day Sleep Reset",
    blurb: "One anchor time, less negotiation, better mornings.",
    kind: "protocol",
    meta: "7 days · printable",
    downloadable: true,
    steps: [
      "Pick a fixed wake time for all 7 days. Protect it like an appointment.",
      "Dim screens 45 minutes before bed. Charge the phone outside the room if you can.",
      "Same wind-down sequence every night: lights down, short stretch, one page of reading.",
      "No caffeine after 2pm for the full week.",
      "Log sleep quality each morning in Daily (1-5). Look for the pattern, not perfection.",
      "If you miss a night, keep the wake time. Do not sleep in to compensate.",
      "On day 7, keep the wake time that actually worked. That becomes your default.",
    ],
    body: [
      "This protocol is not about perfect sleep. It is about removing the daily argument with yourself.",
      "The goal is a repeatable night that survives ordinary stress, not a heroic weekend recovery.",
    ],
  },
  {
    id: "money-baseline-7",
    title: "7-Day Money Baseline",
    blurb: "See where money actually goes before you try to optimize it.",
    kind: "protocol",
    meta: "7 days · printable",
    downloadable: true,
    steps: [
      "Open your main accounts and list every recurring charge. Cancel one you do not use.",
      "Write down yesterday's spending in three lines: needs, wants, forgotten.",
      "Move a small fixed amount to savings on the same day you get paid - before anything else.",
      "Pick one category to watch this week (food, delivery, subscriptions). Track only that.",
      "No new non-essential purchases over $40 unless you wait 24 hours.",
      "Review the week in 10 minutes. Circle the one leak that surprised you.",
      "Set next week's single money rule based on that leak. One rule only.",
    ],
    body: ["Clarity beats complicated budgets. One week of honest observation is enough to start."],
  },
  {
    id: "discipline-stack-7",
    title: "7-Day Discipline Stack",
    blurb: "Three non-negotiables a day. Nothing heroic. Everything repeatable.",
    kind: "protocol",
    meta: "7 days · printable",
    downloadable: true,
    steps: [
      "Choose three daily anchors: move, make, recover (example: walk, one work block, phone away after 10).",
      "Write them where you will see them at the start of the day.",
      "Complete all three before entertainment. Order can flex. Completion cannot.",
      "If you miss one, do a minimum version the same day - 5 minutes counts.",
      "Do not add a fourth anchor this week.",
      "Log completion in Daily each night with one honest sentence.",
      "On day 7, keep the two anchors that stuck. Rebuild the third if needed.",
    ],
  },
  {
    id: "water-baseline-7",
    title: "7-Day Water Baseline",
    blurb: "Know your need. Store what you rotate. Practice once.",
    kind: "protocol",
    meta: "7 days · printable",
    downloadable: true,
    steps: [
      "Write how much drinking and cooking water your household uses in a quiet day. Multiply by three.",
      "Inspect containers you already own. Clean, dry, and label with fill date.",
      "Fill toward your three-day number. Cool, dark storage. No garage extremes if you can avoid them.",
      "Learn one treatment or filtration method that fits your home. Read the instructions once while calm.",
      "Practice that method on a small volume once this week so the motion is familiar.",
      "Set a calendar reminder to rotate or use stored water within a sensible window for your containers.",
      "On day 7, confirm labels, location, and that every adult in the home knows where it is.",
    ],
    body: ["Water readiness is a number, clean storage, and one practiced method - not a pile of unused equipment."],
  },
  {
    id: "garden-start-7",
    title: "7-Day Garden Start",
    blurb: "One crop you eat. Light, soil, and a watering habit.",
    kind: "protocol",
    meta: "7 days · printable",
    downloadable: true,
    steps: [
      "Pick one food you already buy weekly. That is the crop.",
      "Find a spot with roughly six hours of light - bed, pot, or sill.",
      "Prepare soil or potting mix. Remove debris. Water until damp, not flooded.",
      "Plant according to the packet for your climate. Label the date.",
      "Set a simple watering cue tied to something you already do daily.",
      "Check once for pests or dryness. Adjust water; do not rebuild the whole plan.",
      "On day 7, ask whether the site and schedule are realistic. Change one variable only if needed.",
    ],
    body: ["Competence at one plant beats a decorative garden you abandon. Eat what you grow."],
  },
  {
    id: "home-ready-7",
    title: "7-Day Home Ready",
    blurb: "Entries, light, first aid, and a one-page plan.",
    kind: "protocol",
    meta: "7 days · printable",
    downloadable: true,
    steps: [
      "Walk every exterior door and ground-floor window. Note what does not latch cleanly.",
      "Fix or schedule the weakest entry point. One improvement this week is enough to start.",
      "Place working lights where you would need them in the dark. Test batteries.",
      "Locate first aid and important documents. Tell everyone in the home the same locations.",
      "Write a one-page plan: power loss, medical need, and if you must leave. Keep it short.",
      "Review smoke and carbon monoxide alarms. Replace what is dead.",
      "On day 7, re-read the one-page plan aloud once. Update one line that was unclear.",
    ],
    body: ["A home that holds is maintained and known - not staged for a movie."],
  },
  {
    id: "awareness-stack-7",
    title: "7-Day Awareness Stack",
    blurb: "Exits, distance, and a body that can move - without looking for a fight.",
    kind: "protocol",
    meta: "7 days · printable",
    downloadable: true,
    steps: [
      "On one daily route, name three exits and the best-lit path. Do it silently.",
      "Practice giving yourself distance in ordinary spaces - step aside early, do not narrate it.",
      "Add one session of movement that raises heart rate and asks for control (walk hills, carries, or Train).",
      "Write your personal rules: when you leave, when you call for help, when you protect. One sentence each.",
      "Learn the basic self-defense law where you live from a reputable public source. No forums as primary.",
      "If you train contact skills, do it with qualified instruction. This protocol does not replace that.",
      "On day 7, re-walk your main route once with the same checklist. Notice what became automatic.",
    ],
    body: ["Vigilance is awareness and capability under integrity - not aggression as identity."],
  },
  {
    id: "focus-block-tool",
    title: "Focus Block Planner",
    blurb: "Plan one protected hour. Decide the outcome before the hour starts.",
    kind: "tool",
    meta: "Tool · printable",
    downloadable: true,
    steps: [
      "Name the single outcome for the block (one sentence).",
      "Set a start time and end time. Put it on the calendar.",
      "Silence nonessential notifications for that window.",
      "Work only on the named outcome until the timer ends.",
      "Write what moved and what is left for tomorrow.",
    ],
    body: ["One quiet hour beats a scattered day. This tool exists to make that hour concrete."],
  },
  {
    id: "member-mind-series",
    title: "Member Mind Series",
    blurb: "Deeper reads on attention, standards, and long-game habits.",
    kind: "series",
    meta: "Series · in Vault",
    body: [
      "Member series expand on the free Mind desk with longer, more practical playbooks.",
      "Start with attention, standards, and recovery. Open any protocol to put the idea into motion the same week.",
    ],
  },
  {
    id: "body-rebuild-28",
    title: "28-Day Body Rebuild",
    blurb: "Training, walking, and recovery in a plan that survives a normal month.",
    kind: "program",
    meta: "4 weeks · printable",
    downloadable: true,
    steps: [
      "Week 1: Establish 3 training sessions and a daily walk floor. Keep sessions under 45 minutes.",
      "Week 2: Add one harder set or slightly longer walk. Sleep remains non-negotiable.",
      "Week 3: Hold the schedule. Focus on form and consistency, not max effort.",
      "Week 4: Test a simple benchmark (same walk route time, or same lift weight for clean reps).",
      "Missed days: resume the next scheduled session. Do not double up.",
      "Protein at each meal. Water target stays on Daily trackers.",
      "End of week 4: keep the weekly structure. Only change one variable at a time afterward.",
    ],
    body: ["This is not a challenge that peaks on day 3 and dies on day 10. It is a month of showing up."],
  },
  {
    id: "deep-work-28",
    title: "28-Day Deep Work Program",
    blurb: "Build a reliable focus practice across four weeks.",
    kind: "program",
    meta: "4 weeks · printable",
    downloadable: true,
    steps: [
      "Week 1: One 45-minute focus block on your highest-value task, five days.",
      "Week 2: Two blocks on heavy days. Protect the calendar like a meeting with yourself.",
      "Week 3: Same volume. Improve the environment - fewer tabs, clearer outcome statements.",
      "Week 4: Review output. Keep the block times that produced real work.",
      "Phone out of reach during blocks. Notes only for the task at hand.",
      "End each block with a one-line handoff for tomorrow.",
    ],
  },
  {
    id: "meal-plan-builder",
    title: "Weekly Meal Plan Builder",
    blurb: "Turn Health recipes into a simple 7-day plan you can print.",
    kind: "tool",
    meta: "Tool · printable",
    downloadable: true,
    steps: [
      "Pick 3 breakfast options, 3 lunches, 3 dinners from the recipe library.",
      "Assign them across 7 days. Repeat is fine - repetition is the point.",
      "Write a single grocery list from those meals only.",
      "Batch one item on the weekend (protein, grains, or chopped vegetables).",
      "Leave one flexible meal for real life.",
    ],
  },
  {
    id: "progress-lab",
    title: "Progress Lab",
    blurb: "See patterns in consistency, weak days, and which rooms you actually use.",
    kind: "lab",
    meta: "Insights",
    body: [
      "Progress Lab turns your record into signal: which days slip, which rooms compound, where to simplify.",
      "Use it weekly. Adjust one behavior based on what the data shows - not on how motivated you feel today.",
    ],
  },
];

