export type WikiDesk = "body" | "mind" | "career" | "finance" | "social" | "system" | "sufficiency";
export type WikiSource = { label: string; href: string };
export type WikiArticle = {
  slug: string;
  desk: WikiDesk;
  title: string;
  hook: string;
  readMins: number;
  beats: { k: string; t: string }[];
  move: string;
  sources?: WikiSource[];
};

export const DESKS = [
  { id: "body" as WikiDesk, label: "Body", line: "Build a body you can rely on.", hex: "#3DDC97", glow: "rgba(61,220,151,.28)" },
  { id: "mind" as WikiDesk, label: "Mind", line: "Think clearly. Recover fully.", hex: "#7C6BFF", glow: "rgba(124,107,255,.32)" },
  { id: "career" as WikiDesk, label: "Career", line: "Do work that moves your life.", hex: "#4C8DFF", glow: "rgba(76,141,255,.32)" },
  { id: "finance" as WikiDesk, label: "Finance", line: "Make money easier to keep.", hex: "#F5C542", glow: "rgba(245,197,66,.28)" },
  { id: "social" as WikiDesk, label: "Social", line: "Build relationships that hold.", hex: "#FF5C8A", glow: "rgba(255,92,138,.28)" },
  { id: "system" as WikiDesk, label: "System", line: "Use LIVV without overthinking it.", hex: "#2EE0C0", glow: "rgba(46,224,192,.28)" },
  { id: "sufficiency" as WikiDesk, label: "Self Sufficiency", line: "Skills that work when systems lag.", hex: "#C4A574", glow: "rgba(196,165,116,.30)" },
];

export function deskMeta(id: WikiDesk) {
  return DESKS.find((d) => d.id === id) || DESKS[1];
}

export const WIKI: WikiArticle[] = [
  { slug: "sleep-is-the-first-lever", desk: "mind", title: "Sleep is the first lever.", hook: "A tired brain makes every other problem louder.", readMins: 4, beats: [{ k: "01", t: "Sleep changes how the rest of the day feels. When you are underslept, ordinary decisions require more effort and distractions become harder to ignore." }, { k: "02", t: "Do not build a complicated night routine. Pick a realistic bedtime, lower the lights, put the phone away, and make the same choice often enough for it to become normal." }, { k: "03", t: "If your schedule is chaotic, fix the anchor first. A consistent wake time gives the rest of the day somewhere to attach." }], move: "Choose one sleep anchor for the next seven days. Protect it like an appointment." },
  { slug: "implementation-intentions", desk: "mind", title: "Decide before the moment.", hook: "The best plan is the one that removes the argument with yourself.", readMins: 4, beats: [{ k: "01", t: "A vague intention leaves room for negotiation. A clear cue and action leave much less room for debate." }, { k: "02", t: "Use simple language: when this happens, I do that. When I finish breakfast, I open Train. When I get home, I take a ten minute walk." }, { k: "03", t: "Keep the experiment small. One cue. One action. Repeat it until the decision feels automatic." }], move: "Write one when-then rule for tomorrow and follow it once. Make the cue obvious." },
  { slug: "progressive-overload", desk: "body", title: "Give your body a reason to adapt.", hook: "Consistency builds the base. Progress gives the body a new problem to solve.", readMins: 4, beats: [{ k: "01", t: "Training works because the body responds to a challenge. Repeating the same effort forever eventually becomes maintenance." }, { k: "02", t: "Progress does not have to be dramatic. One extra rep, a little more resistance, better control, or another minute can be enough." }, { k: "03", t: "Keep the program stable long enough to learn from it. Constantly changing the plan makes it difficult to tell what actually worked." }], move: "At your next session, improve one measurable part of one exercise. Record it." },
  { slug: "easy-cardio-still-counts", desk: "body", title: "Easy cardio still counts.", hook: "Not every session needs to leave you wrecked.", readMins: 3, beats: [{ k: "01", t: "Easy movement builds your capacity without demanding the recovery cost of another hard session." }, { k: "02", t: "Use the talk test. If you can speak in normal sentences while moving, you are probably working at an easy enough pace." }, { k: "03", t: "Walking, cycling, swimming, and other steady activities all count. The useful part is that you actually keep doing them." }], move: "Schedule one easy thirty minute session this week. Treat it as training, not as an apology for not training harder." },
  { slug: "one-quiet-hour", desk: "career", title: "One quiet hour beats a heroic day.", hook: "Protect the part of the day where your brain can actually build something.", readMins: 4, beats: [{ k: "01", t: "Important work needs uninterrupted attention. Notifications turn a difficult task into a series of tiny restarts." }, { k: "02", t: "You do not need perfect focus all day. One protected hour can be enough to move the highest value task forward." }, { k: "03", t: "Decide what the hour is for before it starts. A clear target makes it easier to notice when you are drifting." }], move: "Put one protected hour on tomorrow's calendar. Pick one outcome before you begin." },
  { slug: "ship-before-perfect", desk: "career", title: "Ship before perfect.", hook: "Finished work can teach you. Unfinished work can only occupy you.", readMins: 3, beats: [{ k: "01", t: "Polishing feels productive because it is safe. Sending the work creates information, feedback, and consequences." }, { k: "02", t: "Make the smallest useful version. Put it in front of the person who can react to it." }, { k: "03", t: "The goal is not careless work. The goal is to stop confusing more preparation with more progress." }], move: "Find one thing that has been almost ready for too long. Reduce it to the smallest useful version and send it." },
  { slug: "pay-yourself-first", desk: "finance", title: "Make the first move automatic.", hook: "A system beats a promise you have to remember every week.", readMins: 4, beats: [{ k: "01", t: "Money disappears easily when saving is whatever remains after spending. Give saving a place in the sequence instead." }, { k: "02", t: "Start with an amount that is sustainable. The first goal is not to impress yourself. It is to make the behavior repeatable." }, { k: "03", t: "Once the habit works, increase it slowly. The system should survive ordinary months, not just your best month." }], move: "Set one automatic transfer that you can comfortably repeat. Then leave it alone." },
  { slug: "fees-are-real-money", desk: "finance", title: "Fees are real money.", hook: "Small costs become large when they repeat for years.", readMins: 3, beats: [{ k: "01", t: "A fee is not abstract. It is money that cannot compound for you because it went somewhere else." }, { k: "02", t: "Look at the accounts you already use. Know what you pay, why you pay it, and whether the service earns the cost." }, { k: "03", t: "You do not need to optimize everything at once. Finding one unnecessary recurring cost is already a useful win." }], move: "Open one financial account today and find every recurring fee. Write the amount down." },
  { slug: "one-real-message", desk: "social", title: "One real message matters.", hook: "A feed can show you people. A relationship requires contact.", readMins: 3, beats: [{ k: "01", t: "Likes are easy to give and easy to forget. A specific message takes more attention and creates an actual connection." }, { k: "02", t: "Reach out with something concrete. Ask how the interview went. Send the address. Invite them for a walk." }, { k: "03", t: "Do not wait until you need something. Relationships get stronger when contact is not always a transaction." }], move: "Send one specific message to someone you care about. No broadcast. One person." },
  { slug: "protect-your-attention", desk: "mind", title: "Attention is a resource.", hook: "What gets your attention eventually gets your life.", readMins: 4, beats: [{ k: "01", t: "Every notification asks for a tiny decision. Enough tiny decisions can make a day feel busy without making it meaningful." }, { k: "02", t: "Reduce the number of things that can interrupt you. Silence nonessential alerts. Put distracting apps somewhere inconvenient." }, { k: "03", t: "Then replace the empty space with something deliberate. Read. Train. Cook. Talk. Build. Rest." }], move: "Turn off one category of notification that regularly steals your attention." },
  { slug: "use-livv-simply", desk: "system", title: "Use LIVV simply.", hook: "Open the app to do something, not to admire the dashboard.", readMins: 3, beats: [{ k: "01", t: "Home shows the shape of your day. Daily gives you a few concrete actions. Train turns effort into a record. Mind gives you something useful to think about. Social gives your progress a place to meet other people." }, { k: "02", t: "You do not need to touch every feature every day. Use the part that solves the problem in front of you." }, { k: "03", t: "The point of a system is to make action easier. If you spend more time arranging the system than using it, simplify." }], move: "Open LIVV tomorrow and complete one useful action before you browse anything else." },
  { slug: "streaks-are-data", desk: "system", title: "A streak is data, not your identity.", hook: "Missing a day is information. It is not a verdict.", readMins: 3, beats: [{ k: "01", t: "A streak is a record of repeated behavior. It can motivate you, but it does not define your character." }, { k: "02", t: "If a streak breaks, ask what caused the break. Was the plan too large? Was the cue unclear? Did your environment make the action difficult?" }, { k: "03", t: "Use the answer to redesign the next attempt. Improvement comes from learning, not from pretending every day will be perfect." }], move: "If you missed recently, write one sentence explaining why. Then make tomorrow's action smaller." },
  { slug: "soil-before-seed", desk: "sufficiency", title: "Soil before seed.", hook: "A garden fails at the ground, not at the packet.", readMins: 4, beats: [{ k: "01", t: "Start with what you will actually eat. One bed of food you use weekly beats a decorative plot you abandon by July." }, { k: "02", t: "Sun, drainage, and soil matter more than seed variety. Fix the ground first. Compost, mulch, and water access turn effort into a system." }, { k: "03", t: "Grow in seasons your climate allows. Learn one crop well before you expand. Competence compounds faster than novelty." }], move: "Pick one crop you already eat. Mark where it gets six hours of light. That is your first bed." },
  { slug: "water-you-can-trust", desk: "sufficiency", title: "Water you can trust.", hook: "Store what you will rotate. Do not hoard what you will forget.", readMins: 4, beats: [{ k: "01", t: "Know your household baseline: how much drinking and cooking water you use in three quiet days. That number is more useful than a random bulk buy." }, { k: "02", t: "Clean containers, cool dark storage, and a rotation date beat complicated setups. Label everything. Use the oldest first." }, { k: "03", t: "Learn one simple filtration or treatment method that matches your situation. Practice it once so you are not reading instructions under stress." }], move: "Write your three-day water need on paper. Fill and label one container toward that number this week." },
  { slug: "awareness-before-force", desk: "sufficiency", title: "Awareness before force.", hook: "Most trouble is avoided earlier than it is fought.", readMins: 4, beats: [{ k: "01", t: "Notice exits, lighting, and who is near you when you move through public space. Habit, not paranoia." }, { k: "02", t: "Trust the early signal. Distance and a clear exit are skills. Escalation is a last resort, not a first identity." }, { k: "03", t: "Train your body so you are not helpless if avoidance fails. Strength, breath, and the ability to move under stress belong in the same system as awareness." }], move: "On your next walk outside, name three exits and one better-lit path. Make it ordinary, not dramatic." },
  { slug: "agency-is-not-aggression", desk: "sufficiency", title: "Agency is not aggression.", hook: "Offense in LIVV means you can act. It does not mean you look for a fight.", readMins: 4, beats: [{ k: "01", t: "Capability without character becomes a liability. The goal is to protect people and leave safely, not to win arguments with force." }, { k: "02", t: "Legal self-defense, de-escalation, and trained physical response are different layers. Learn the law where you live. Train with qualified instruction when you train contact skills." }, { k: "03", t: "Your standards stay: integrity first. Power without restraint is not vigilance. It is noise." }], move: "Write one sentence that defines when you leave, when you call for help, and when you protect. Keep it simple." },
  { slug: "a-body-that-can-leave", desk: "sufficiency", title: "A body that can leave.", hook: "Cardio, grip, and the ability to move under load are readiness, not aesthetics.", readMins: 3, beats: [{ k: "01", t: "If you cannot walk far, climb stairs, or carry what matters, theory does not help. Train the engine you will need." }, { k: "02", t: "Pair Train with real movement: hills, loaded carries, getting up from the ground without drama." }, { k: "03", t: "Recovery is part of readiness. An injured body is not a prepared body." }], move: "Add one loaded carry or long walk to this week's training. Treat it as skill, not punishment." },
  { slug: "home-that-holds", desk: "sufficiency", title: "A home that holds.", hook: "Locks, light, and a plan beat theater.", readMins: 4, beats: [{ k: "01", t: "Walk your doors, windows, and entry points once with attention. Fix what is weak. That is maintenance, not fear." }, { k: "02", t: "Know where flashlights, first aid, and important documents live. Everyone in the household should know the same map." }, { k: "03", t: "A short written plan for power loss, medical need, or needing to leave beats a drawer of unused gear." }], move: "In fifteen minutes, test one lock, place one working light, and write where the first-aid kit is." },
  { slug: "skills-before-gear", desk: "sufficiency", title: "Skills before gear.", hook: "Equipment without practice is weight. Practice without gear still moves.", readMins: 3, beats: [{ k: "01", t: "Buy after you have used a skill once with what you already have. Need becomes clear. Catalogs become quieter." }, { k: "02", t: "First aid, fire safety, basic navigation, and cooking from simple stores matter more than specialized kits you never open." }, { k: "03", t: "Schedule practice the way you schedule training. A skill you rehearsed is available under stress. A skill you only watched is not." }], move: "Pick one skill you already half-know. Rehearse it once this week with a timer and no phone tutorial mid-task." },
  { slug: "grow-what-you-eat", desk: "sufficiency", title: "Grow what you eat.", hook: "Food you harvest is training for patience and attention.", readMins: 3, beats: [{ k: "01", t: "Herbs and greens on a windowsill still count. Scale is secondary to the habit of tending something living." }, { k: "02", t: "Water on a schedule. Harvest before plants bolt. Failures teach soil and season faster than perfect diagrams." }, { k: "03", t: "Connect the garden to the kitchen. If it does not end up on a plate, it was decoration." }], move: "Plant or pot one edible plant this week. Put a reminder to water it next to something you already do daily." },
];

export function articleBySlug(slug: string) {
  return WIKI.find((a) => a.slug === slug) || null;
}

export function nextArticle(slug: string) {
  const i = WIKI.findIndex((a) => a.slug === slug);
  return WIKI[(i + 1 + WIKI.length) % WIKI.length] || WIKI[0];
}
