-- LIVV Supabase schema index
-- -----------------------------------------------------------------------------
-- A3-1 (current identity slice):
--   Run the full contents of:
--     supabase/migrations/a3_1_identity_profiles.sql
--   in the Supabase Dashboard → SQL Editor.
--
-- That migration creates:
--   - public.profiles (FK auth.users)
--   - unique username index
--   - handle_new_user trigger (anon_* placeholder username)
--   - RLS: select/insert/update own row only
--
-- Manual dashboard step (not SQL):
--   Authentication → Providers → Anonymous → Enable
--
-- Deferred (not part of A3-1):
--   records, pack_state, subscriptions
-- -----------------------------------------------------------------------------

-- Do not use psql \i here — the Supabase SQL Editor does not support it.
-- Copy/paste migrations/a3_1_identity_profiles.sql to apply.
