"use client";
import { useEffect, useMemo, useState } from "react";
const KEY="livv-sleep-v1";
type Entry={date:string;bedtime:string;wake:string;quality:number;note:string};
function today(){return new Date().toISOString().slice(0,10)}
function duration(b:string,w:string){if(!b||!w)return 0;const a=b.split(":").map(Number),c=w.split(":").map(Number);let s=a[0]*60+a[1],e=c[0]*60+c[1];if(e<=s)e+=1440;return Math.round((e-s)/60*10)/10}
export default function SleepPage(){
 const [entries,setEntries]=useState<Entry[]>([]),[bedtime,setBedtime]=useState(""),[wake,setWake]=useState(""),[quality,setQuality]=useState(3),[note,setNote]=useState("");
 useEffect(()=>{try{const r=localStorage.getItem(KEY);if(r)setEntries(JSON.parse(r))}catch{}},[]);
 const recent=useMemo(()=>entries.slice(-7).reverse(),[entries]); const average=recent.length?Math.round(recent.reduce((s,e)=>s+duration(e.bedtime,e.wake),0)/recent.length*10)/10:0; const current=duration(bedtime,wake);
 function save(){if(!bedtime||!wake)return;const next=[...entries.filter(e=>e.date!==today()),{date:today(),bedtime,wake,quality,note:note.trim()}].slice(-90);setEntries(next);localStorage.setItem(KEY,JSON.stringify(next))}
 return <main className="livv-page min-h-full"><div className="mx-auto max-w-xl px-5 pb-14 pt-6">
 <header className="border-b border-livv-line pb-7 text-center"><a href="/home/health" className="text-[10px] font-semibold uppercase tracking-[.2em] text-livv-muted">Health / Sleep</a><h1 className="mt-2 text-[clamp(1.8rem,8vw,2.5rem)] font-semibold tracking-[-.05em]">Sleep, remembered.</h1><p className="mx-auto mt-3 max-w-[36ch] text-sm leading-6 text-livv-muted">Log the night. Notice the pattern. No prescribed schedule.</p></header>
 <section className="border-b border-livv-line py-7"><div className="grid grid-cols-2 gap-3"><Stat label="Last 7 avg" value={average?average+"h":"—"}/><Stat label="Current" value={current?current+"h":"—"}/></div></section>
 <section className="border-b border-livv-line py-7"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-livv-muted">Log a night</p><div className="mt-5 grid grid-cols-2 gap-4"><Field label="Bedtime"><input type="time" value={bedtime} onChange={e=>setBedtime(e.target.value)} className="livv-product-control w-full rounded-xl px-3 py-3 outline-none"/></Field><Field label="Wake time"><input type="time" value={wake} onChange={e=>setWake(e.target.value)} className="livv-product-control w-full rounded-xl px-3 py-3 outline-none"/></Field></div><p className="mt-5 text-[10px] font-semibold uppercase tracking-[.16em] text-livv-muted">Sleep quality</p><div className="mt-3 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>setQuality(n)} className={"rounded-xl border py-3 text-sm "+(quality===n?"border-livv-ink bg-livv-ink text-livv-bg":"border-livv-line text-livv-muted")}>{n}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={180} placeholder="Optional note..." className="mt-5 min-h-24 w-full rounded-xl border border-livv-line bg-transparent p-3 text-sm outline-none placeholder:text-livv-muted"/><button type="button" onClick={save} disabled={!bedtime||!wake} className="mt-4 w-full rounded-full bg-livv-ink py-3.5 text-[10px] font-semibold uppercase tracking-[.14em] text-livv-bg disabled:opacity-30">Save sleep</button></section>
 <section className="py-7"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-livv-muted">History</p><div className="mt-4 divide-y divide-livv-line border-y border-livv-line">{recent.length===0&&<p className="py-5 text-sm text-livv-muted">Your first night will appear here.</p>}{recent.map(e=><div key={e.date} className="flex items-center gap-4 py-4"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{e.date}</p><p className="mt-1 text-xs text-livv-muted">{e.bedtime} → {e.wake} · quality {e.quality}/5</p></div><span className="text-sm font-semibold tabular-nums">{duration(e.bedtime,e.wake)}h</span></div>)}</div><p className="mt-5 text-center text-[9px] leading-5 text-livv-muted">Wellness tracking only; not medical advice.</p></section>
 </div></main>}
function Stat(p:{label:string;value:string}){return <div className="rounded-2xl border border-livv-line px-4 py-4"><p className="text-[9px] uppercase tracking-[.16em] text-livv-muted">{p.label}</p><p className="mt-2 text-2xl font-semibold">{p.value}</p></div>}
function Field(p:{label:string;children:React.ReactNode}){return <label className="block"><span className="text-[10px] font-semibold uppercase tracking-[.15em] text-livv-muted">{p.label}</span><div className="mt-2">{p.children}</div></label>}
