"use client";

import { useEffect, useRef, useState } from "react";
import { Container } from "@/components/ui/container";
import { Button } from "@/components/ui/button";
import { AmbientField } from "@/components/layout/ambient-field";
import { cn } from "@/lib/utils";
import { FOCUS_OPTIONS, LOCATION_OPTIONS, DURATION_OPTIONS, generateWorkout, type Focus, type Location, type Duration, type Workout, type Exercise } from "@/lib/train-data";
import { activityFromWorkout } from "@/lib/activity";
import { completeWorkout, loadRecord, type LastWorkout } from "@/lib/record";
import { feedback } from "@/lib/sensory";
import { Moment } from "@/components/ui/moment";

type Phase = "select" | "preview" | "session" | "rest" | "complete";
const FULL_KEY = "livv-last-workout-full";
function saveFullWorkout(w: Workout) { try { window.localStorage.setItem(FULL_KEY, JSON.stringify(w)); } catch {} }
function loadFullWorkout(): Workout | null { try { const raw = window.localStorage.getItem(FULL_KEY); return raw ? JSON.parse(raw) as Workout : null; } catch { return null; } }
function parseRestSeconds(rest: string) { const n = parseInt(rest, 10); return Number.isFinite(n) ? Math.min(120, Math.max(15, n)) : 40; }
function choiceLabel(value: string) { return value.replace(/-/g, " "); }

export default function TrainPage() {
  const [phase, setPhase] = useState<Phase>("select");
  const [focus, setFocus] = useState<Focus | null>(null);
  const [location, setLocation] = useState<Location | null>(null);
  const [duration, setDuration] = useState<Duration | null>(null);
  const [workout, setWorkout] = useState<Workout | null>(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [completedExercises, setCompletedExercises] = useState<string[]>([]);
  const [logged, setLogged] = useState(false);
  const [last, setLast] = useState<LastWorkout | null>(null);
  const [restLeft, setRestLeft] = useState(0);
  const [note, setNote] = useState("");
  const [showMoment, setShowMoment] = useState(false);
  const restRef = useRef<number | null>(null);

  useEffect(() => { setLast(loadRecord().lastWorkout); return () => { if (restRef.current) window.clearInterval(restRef.current); }; }, []);
  const canGenerate = Boolean(focus && location && duration);
  const handleGenerate = () => { if (!focus || !location || !duration) return; feedback("tick"); setWorkout(generateWorkout(focus, location, duration)); setPhase("preview"); };
  const repeatLast = () => { const full = loadFullWorkout(); if (!full) return; feedback("tick"); setWorkout(full); setPhase("preview"); };
  const handleStart = () => { feedback("tick"); setCurrentIndex(0); setCompletedExercises([]); setLogged(false); setNote(""); setPhase("session"); };
  const finishSession = (w: Workout) => { if (!logged) { activityFromWorkout({ workoutName: w.name, focus: w.focus, location: w.location, duration: w.duration, difficulty: w.difficulty, exerciseCount: w.exercises.length }); completeWorkout({ name: w.name, focus: w.focus, duration: w.duration, exercises: w.exercises.length }); saveFullWorkout(w); setLogged(true); feedback("complete"); setShowMoment(true); } setPhase("complete"); };
  const startRest = (seconds: number) => { setRestLeft(seconds); setPhase("rest"); if (restRef.current) window.clearInterval(restRef.current); restRef.current = window.setInterval(() => { setRestLeft(s => { if (s <= 1) { if (restRef.current) window.clearInterval(restRef.current); feedback("rest"); setPhase("session"); return 0; } return s - 1; }); }, 1000); };
  const handleCompleteExercise = (exercise: Exercise) => { feedback("tick"); setCompletedExercises(prev => [...prev, exercise.id]); if (workout && currentIndex < workout.exercises.length - 1) { setCurrentIndex(i => i + 1); startRest(parseRestSeconds(exercise.rest)); } else if (workout) finishSession(workout); };
  const handleReset = () => { if (restRef.current) window.clearInterval(restRef.current); setPhase("select"); setFocus(null); setLocation(null); setDuration(null); setWorkout(null); setCurrentIndex(0); setCompletedExercises([]); setLogged(false); setNote(""); setLast(loadRecord().lastWorkout); };

  if (phase === "select") return (
    <main className="relative min-h-full overflow-hidden pb-10 pt-5"><AmbientField intensity="strong" /><Container className="relative z-10">
      <header className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.32em] text-livv-accent-soft">Physical capability</p><h1 className="mt-2 text-[2.7rem] font-semibold leading-none tracking-[-0.05em]">Train</h1></div><div className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5 text-[10px] uppercase tracking-[0.2em] text-white/35">BODY / 01</div></header>
      <section className="relative mt-7 overflow-hidden rounded-[32px] border border-white/10 bg-gradient-to-br from-white/[0.08] to-white/[0.025] p-6 shadow-2xl backdrop-blur-xl"><div className="absolute -right-24 -top-28 h-64 w-64 rounded-full bg-livv-accent/10 blur-3xl" /><div className="relative"><div className="flex items-center justify-between"><p className="text-[10px] uppercase tracking-[0.28em] text-white/35">Training chamber</p><span className="text-[10px] text-livv-accent">READY</span></div><h2 className="mt-5 max-w-[310px] text-[2rem] font-medium leading-[1.02] tracking-tight">Build the body you want to live in.</h2><p className="mt-4 max-w-[310px] text-sm leading-relaxed text-white/45">LIVV turns a few decisions into a session, then turns the finish into proof.</p>{last && <button type="button" onClick={repeatLast} className="mt-6 flex w-full items-center justify-between rounded-2xl border border-livv-accent/20 bg-livv-accent/[0.08] px-4 py-3.5 text-left"><div><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-livv-accent-soft">Continue rhythm</p><p className="mt-1 text-sm font-medium text-white/85">{last.name} · {last.duration}</p></div><span className="text-xl text-livv-accent">↗</span></button>}</div></section>
      <section className="mt-8"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[0.28em] text-white/35">01 / Intent</p><p className="mt-1 text-sm text-white/65">What are we building today?</p></div><span className="text-[10px] text-white/20">{focus ? "LOCKED" : "SELECT"}</span></div><div className="grid grid-cols-2 gap-2.5">{FOCUS_OPTIONS.map(opt => <button key={opt} type="button" onClick={() => { feedback("tick"); setFocus(opt); }} className={cn("relative overflow-hidden rounded-2xl border p-4 text-left transition-all duration-300", focus === opt ? "border-livv-accent/60 bg-livv-accent/[0.13] shadow-[0_0_35px_rgba(255,255,255,0.04)]" : "border-white/[0.08] bg-white/[0.035] hover:border-white/15")}><span className="text-[9px] uppercase tracking-[0.2em] text-white/25">Focus</span><span className="mt-2 block text-sm font-medium capitalize text-white/80">{choiceLabel(opt)}</span>{focus === opt && <span className="absolute right-3 top-3 h-2 w-2 rounded-full bg-livv-accent shadow-[0_0_12px_rgba(255,255,255,0.6)]" />}</button>)}</div></section>
      <section className="mt-7"><div className="mb-3"><p className="text-[10px] uppercase tracking-[0.28em] text-white/35">02 / Environment</p><p className="mt-1 text-sm text-white/65">Choose your arena.</p></div><div className="flex gap-2.5">{LOCATION_OPTIONS.map(opt => <button key={opt} type="button" onClick={() => { feedback("tick"); setLocation(opt); }} className={cn("flex-1 rounded-2xl border px-3 py-4 text-left transition-all duration-300", location === opt ? "border-livv-accent/60 bg-livv-accent/[0.13]" : "border-white/[0.08] bg-white/[0.035] hover:border-white/15")}><span className="text-[9px] uppercase tracking-[0.2em] text-white/25">Space</span><span className="mt-2 block text-sm font-medium capitalize text-white/80">{choiceLabel(opt)}</span></button>)}</div></section>
      <section className="mt-7"><div className="mb-3"><p className="text-[10px] uppercase tracking-[0.28em] text-white/35">03 / Time</p><p className="mt-1 text-sm text-white/65">How much are you willing to give?</p></div><div className="flex flex-wrap gap-2">{DURATION_OPTIONS.map(opt => <button key={opt.value} type="button" onClick={() => { feedback("tick"); setDuration(opt.value); }} className={cn("rounded-full border px-4 py-2.5 text-xs font-medium transition-all duration-300", duration === opt.value ? "border-livv-accent/60 bg-livv-accent/[0.13] text-white" : "border-white/[0.08] bg-white/[0.035] text-white/50 hover:border-white/15")}>{opt.label}</button>)}</div></section>
      <div className="mt-9"><Button variant="accent" size="lg" className="w-full shadow-[0_0_42px_rgba(255,255,255,0.08)]" disabled={!canGenerate} onClick={handleGenerate}>{canGenerate ? "Assemble Training Session ↗" : "Complete the setup"}</Button><p className="mt-3 text-center text-[10px] uppercase tracking-[0.2em] text-white/20">Zero equipment · full commitment</p></div>
    </Container></main>
  );

  if (phase === "preview" && workout) return (
    <main className="relative min-h-full overflow-hidden pb-10 pt-5"><AmbientField intensity="strong" /><Container className="relative z-10"><button onClick={() => setPhase("select")} className="mb-5 text-[10px] uppercase tracking-[0.22em] text-white/35">← Reconfigure chamber</button><div className="rounded-[32px] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl"><p className="text-[10px] uppercase tracking-[0.28em] text-livv-accent-soft">Session assembled</p><h1 className="mt-3 text-3xl font-semibold leading-tight tracking-tight">{workout.name}</h1><div className="mt-4 flex flex-wrap gap-2">{[workout.duration, workout.difficulty, workout.location].map(item => <span key={item} className="rounded-full border border-white/10 bg-black/20 px-3 py-1.5 text-[10px] uppercase tracking-[0.16em] text-white/45">{item}</span>)}</div></div><div className="mt-7 space-y-2.5">{workout.exercises.map((ex,i)=><div key={ex.id} className="flex items-center gap-4 rounded-2xl border border-white/[0.07] bg-white/[0.03] p-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-white/10 text-[10px] text-white/30">{String(i+1).padStart(2,"0")}</div><div className="min-w-0 flex-1"><p className="font-medium text-white/85">{ex.name}</p><p className="mt-1 text-xs text-white/35">{ex.sets && `${ex.sets} sets`}{ex.reps && ` · ${ex.reps}`}{ex.duration && ` · ${ex.duration}`}</p></div><span className="text-[10px] text-white/25">{ex.rest} rest</span></div>)}</div><div className="mt-8"><Button variant="accent" size="lg" className="w-full" onClick={handleStart}>Enter Training Mode</Button></div></Container></main>
  );

  if (phase === "rest" && workout) { const maxRest = 120; const pct = Math.round((restLeft/maxRest)*100); return <main className="relative flex min-h-full flex-col items-center justify-center overflow-hidden pb-10"><AmbientField intensity="strong" /><Container className="relative z-10"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.32em] text-livv-accent-soft">Recovery window</p><div className="mx-auto mt-7 flex h-56 w-56 items-center justify-center rounded-full border border-white/10 bg-white/[0.025]" style={{ background: `conic-gradient(rgb(255 255 255 / .8) ${pct}%, rgb(255 255 255 / .05) ${pct}%)` }}><div className="flex h-48 w-48 flex-col items-center justify-center rounded-full bg-[#090909]"><span className="text-6xl font-semibold tracking-tight">{restLeft}</span><span className="mt-1 text-[9px] uppercase tracking-[0.3em] text-white/30">seconds</span></div></div><p className="mt-7 text-lg font-medium">Breathe. Reset. Go again.</p><p className="mt-2 text-sm text-white/35">Next movement is waiting.</p><Button variant="secondary" className="mt-8" onClick={() => { if (restRef.current) window.clearInterval(restRef.current); setPhase("session"); }}>Skip recovery</Button></div></Container></main>; }

  if (phase === "session" && workout) { const current = workout.exercises[currentIndex]; const progress = ((currentIndex + 1) / workout.exercises.length) * 100; return <main className="relative flex min-h-full flex-col overflow-hidden pb-8 pt-5"><AmbientField intensity="strong" /><Container className="relative z-10 flex flex-1 flex-col"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[0.28em] text-white/30">Training mode</p><p className="mt-1 text-xs text-white/45">{workout.name}</p></div><span className="text-[10px] uppercase tracking-[0.2em] text-livv-accent">{currentIndex+1}/{workout.exercises.length}</span></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-white/[0.08]"><div className="h-full rounded-full bg-livv-accent transition-all duration-500" style={{width:`${progress}%`}} /></div><div className="flex flex-1 flex-col justify-center py-8"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.35em] text-livv-accent-soft">Now</p><h1 className="mt-4 text-[2.7rem] font-semibold leading-[.98] tracking-[-0.05em]">{current.name}</h1><div className="mx-auto mt-7 h-px w-16 bg-white/15"/><p className="mt-6 text-lg text-white/60">{current.sets && `${current.sets} sets`}{current.reps && ` · ${current.reps}`}{current.duration && ` · ${current.duration}`}</p><p className="mt-2 text-xs uppercase tracking-[0.18em] text-white/25">Rest {current.rest} after</p></div></div><div className="space-y-3"><Button variant="accent" size="lg" className="w-full h-14 text-base" onClick={() => handleCompleteExercise(current)}>Mark Exercise Complete ✓</Button><Button variant="ghost" className="w-full" onClick={handleReset}>End Training</Button></div></Container></main>; }

  return <main className="relative min-h-full overflow-hidden pb-10 pt-5"><AmbientField intensity="strong" />{showMoment && <Moment title="Training complete" subtitle={workout ? `${workout.name} added to your evolution record` : undefined} onDone={() => setShowMoment(false)} />}<Container className="relative z-10"><div className="pt-6 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-livv-accent/40 bg-livv-accent/10 text-2xl shadow-[0_0_45px_rgba(255,255,255,0.08)]">✓</div><p className="mt-7 text-[10px] uppercase tracking-[0.32em] text-livv-accent-soft">Proof added</p><h1 className="mt-3 text-[2.7rem] font-semibold leading-none tracking-[-0.05em]">Session complete.</h1><p className="mt-4 text-sm text-white/40">{workout?.name} · {completedExercises.length} exercises</p><div className="mt-8 rounded-3xl border border-white/[0.08] bg-white/[0.035] p-5 text-left"><p className="text-[10px] uppercase tracking-[0.2em] text-white/25">Reflection</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="One line. How did it feel?" rows={3} className="mt-3 w-full resize-none bg-transparent text-sm text-white/80 outline-none placeholder:text-white/20" /></div><div className="mt-6 space-y-3"><Button variant="accent" size="lg" className="w-full" onClick={() => { if (note.trim() && workout) { try { const notes=JSON.parse(window.localStorage.getItem("livv-session-notes")||"[]"); notes.unshift({at:Date.now(),name:workout.name,note:note.trim()}); window.localStorage.setItem("livv-session-notes",JSON.stringify(notes.slice(0,30))); } catch {} } handleReset(); }}>Train Again</Button><Button variant="secondary" className="w-full" onClick={() => window.location.href="/home/progress"}>View Evolution ↗</Button></div></div></Container></main>;
}
