import { getSupabaseBrowserClient,isSupabaseConfigured } from "./client";
const SHADOW_KEY="livv-cloud-state-shadow-v1";const SIGNING_OUT_KEY="livv-signing-out-v1";const MAX_STATE_BYTES=900_000;const EXCLUDED_KEYS=new Set(["livv-session-v1","livv-accounts-v1","livv-cloud-account-v1","livv-cloud-state-shadow-v1","livv-supabase-auth",SIGNING_OUT_KEY]);
function canSync(){return typeof window!=="undefined"&&isSupabaseConfigured()&&window.localStorage.getItem(SIGNING_OUT_KEY)!=="1";}
function readLocalState():Record<string,string>{const state:Record<string,string>={};for(let i=0;i<window.localStorage.length;i++){const key=window.localStorage.key(i);if(!key||!key.startsWith("livv-")||EXCLUDED_KEYS.has(key)||/(token|password|secret|credential|auth)/i.test(key))continue;const value=window.localStorage.getItem(key);if(value!==null)state[key]=value;}return state;}
function stateBytes(state:Record<string,string>){return new TextEncoder().encode(JSON.stringify(state)).byteLength;}
function writeLocalState(state:Record<string,string>){for(const[key,value]of Object.entries(state))window.localStorage.setItem(key,value);}
function notifyStateHydrated(){for(const event of ["livv-record","livv-daily","livv-identity","livv-billing"])window.dispatchEvent(new Event(event));}
function clearLocalStateExceptAuth(){const keys:string[]=[];for(let i=0;i<window.localStorage.length;i++){const key=window.localStorage.key(i);if(key?.startsWith("livv-")&&!EXCLUDED_KEYS.has(key)&&!/(token|password|secret|credential|auth)/i.test(key))keys.push(key);}for(const key of keys)window.localStorage.removeItem(key);}
export function markSigningOut(){if(typeof window!=="undefined")window.localStorage.setItem(SIGNING_OUT_KEY,"1");}
export function clearLocalCloudSyncedState(){if(typeof window==="undefined")return;clearLocalStateExceptAuth();for(const key of [SHADOW_KEY,"livv-cloud-account-v1","livv-session-v1","livv-accounts-v1","livv-usernames-v1","livv-identity-v1",SIGNING_OUT_KEY])window.localStorage.removeItem(key);notifyStateHydrated();}
function snapshot(state:Record<string,string>){return JSON.stringify(Object.keys(state).sort().reduce<Record<string,string>>((out,key)=>{out[key]=state[key];return out;},{}));}
function loadShadow():Record<string,string>|null{try{const raw=window.localStorage.getItem(SHADOW_KEY);return raw?(JSON.parse(raw)as Record<string,string>):null;}catch{return null;}}
function saveShadow(state:Record<string,string>){window.localStorage.setItem(SHADOW_KEY,JSON.stringify(state));}
async function currentUserId(){const client=getSupabaseBrowserClient();if(!client)return null;const{data,error}=await client.auth.getUser();if(error||!data.user||data.user.is_anonymous)return null;return data.user.id;}
async function readCloud(userId:string){const client=getSupabaseBrowserClient();if(!client)return null;const{data,error}=await client.from("member_state").select("state, updated_at").eq("user_id",userId).maybeSingle();if(error)throw error;return data as{state:Record<string,string>;updated_at:string}|null;}
async function writeCloud(userId:string,state:Record<string,string>){const client=getSupabaseBrowserClient();if(!client)return false;if(stateBytes(state)>MAX_STATE_BYTES)throw new Error("LIVV cloud state is too large to sync safely");const{error}=await client.from("member_state").upsert({user_id:userId,state},{onConflict:"user_id"});if(error)throw error;return true;}
function mergeOnlyChanged(local:Record<string,string>,shadow:Record<string,string>,cloud:Record<string,string>){const merged={...cloud};const keys=new Set([...Object.keys(local),...Object.keys(shadow)]);for(const key of keys)if(local[key]!==shadow[key]){if(local[key]===undefined)delete merged[key];else merged[key]=local[key];}return merged;}
export async function bootstrapCloudMemberState(){if(!canSync())return;const userId=await currentUserId();if(!userId)return;const local=readLocalState();const cloud=await readCloud(userId);if(!cloud){if(Object.keys(local).length){await writeCloud(userId,local);saveShadow(local);}return;}const cloudState=cloud.state||{};const shadow=loadShadow();if(!Object.keys(local).length){writeLocalState(cloudState);saveShadow(cloudState);notifyStateHydrated();return;}if(!shadow){clearLocalStateExceptAuth();writeLocalState(cloudState);saveShadow(cloudState);notifyStateHydrated();return;}const merged=mergeOnlyChanged(local,shadow,cloudState);if(snapshot(merged)!==snapshot(cloudState))await writeCloud(userId,merged);clearLocalStateExceptAuth();writeLocalState(merged);saveShadow(merged);notifyStateHydrated();}
let syncInFlight:Promise<void>|null=null;async function syncCloudMemberStateInternal(){if(!canSync())return;const userId=await currentUserId();if(!userId)return;const local=readLocalState();const shadow=loadShadow();if(shadow&&snapshot(local)===snapshot(shadow))return;await writeCloud(userId,local);saveShadow(local);}
export async function syncCloudMemberState(){if(syncInFlight)return syncInFlight;syncInFlight=syncCloudMemberStateInternal().catch(error=>{throw error;}).finally(()=>{syncInFlight=null;});return syncInFlight;}
export function startCloudMemberStateSync(){if(!canSync())return()=>{};let stopped=false;let retryMs=3000;let timer:number|null=null;const schedule=()=>{if(stopped)return;timer=window.setTimeout(()=>void tick(),retryMs);};const tick=async()=>{if(stopped||window.localStorage.getItem(SIGNING_OUT_KEY)==="1"||!navigator.onLine){schedule();return;}try{await syncCloudMemberState();retryMs=3000;}catch(error){retryMs=Math.min(60000,Math.max(3000,retryMs*2));console.warn("[LIVV cloud state] sync deferred",error);}schedule();};const begin=async()=>{try{await bootstrapCloudMemberState();retryMs=3000;}catch(error){retryMs=6000;console.warn("[LIVV cloud state] bootstrap deferred",error);}finally{if(!stopped)void tick();}};void begin();const onVisibility=()=>{if(document.visibilityState==="visible"){retryMs=3000;void tick();}};const onPageHide=()=>{if(window.localStorage.getItem(SIGNING_OUT_KEY)!=="1")void tick();};const onOnline=()=>{retryMs=3000;void tick();};window.addEventListener("visibilitychange",onVisibility);window.addEventListener("pagehide",onPageHide);window.addEventListener("online",onOnline);return()=>{stopped=true;if(timer!==null)window.clearTimeout(timer);window.removeEventListener("visibilitychange",onVisibility);window.removeEventListener("pagehide",onPageHide);window.removeEventListener("online",onOnline);};}
