import type { Recipe } from "./types";

export const BREAKFAST_PART_1: Recipe[] = [
  {"id": "sweet-potato-hash", "title": "Sweet Potato Breakfast Hash", "time": 25, "tag": "Fiber", "category": "Breakfast", "servings": "2 servings", "blurb": "Root vegetables, eggs, and greens.", "ingredients": ["1 sweet potato diced", "1/2 onion", "2 eggs", "1 cup spinach", "1 tbsp oil", "Paprika"], "steps": ["Cook potato and onion 12–15 min. Cook eggs. Wilt spinach."], "tip": "Dice potato small."},
  {"id": "turkey-breakfast-skillet", "title": "Turkey Breakfast Skillet", "time": 18, "tag": "Lean protein", "category": "Breakfast", "servings": "2 servings", "blurb": "Savory morning protein without heavy grease.", "ingredients": ["6 oz ground turkey", "1/2 bell pepper", "1/4 onion", "2 eggs", "Cumin, salt"], "steps": ["Brown turkey with vegetables. Crack eggs in wells. Cover until set."], "tip": "Drain excess liquid."},
  {"id": "apple-cinnamon-oats", "title": "Apple Cinnamon Oats", "time": 12, "tag": "Comfort", "category": "Breakfast", "servings": "1 bowl", "blurb": "Warm apples and cinnamon on oats.", "ingredients": ["1/2 cup oats", "1 cup liquid", "1 apple diced", "1/2 tsp cinnamon", "Pinch salt"], "steps": ["Simmer oats with apple and cinnamon until thick."], "tip": "Leave skin on for fiber."},
  {"id": "tofu-scramble", "title": "Tofu Scramble", "time": 15, "tag": "Plant protein", "category": "Breakfast", "servings": "2 servings", "blurb": "Plant-based scramble with real seasoning.", "ingredients": ["14 oz firm tofu", "1 cup vegetables", "1 tsp oil", "1/2 tsp turmeric", "Garlic powder"], "steps": ["Sauté vegetables. Add tofu and seasonings 5–7 min."], "tip": "Press tofu so it browns."},
  {"id": "breakfast-burrito", "title": "Breakfast Burrito", "time": 15, "tag": "Portable", "category": "Breakfast", "servings": "1 burrito", "blurb": "Eggs, beans, salsa — eat now or freeze.", "ingredients": ["2 eggs", "1 tortilla", "1/4 cup black beans", "Salsa"], "steps": ["Scramble eggs. Fill tortilla. Roll and toast in dry pan."], "tip": "Wrap in foil for the road."},
  {"id": "quinoa-breakfast-bowl", "title": "Quinoa Breakfast Bowl", "time": 20, "tag": "Complete protein", "category": "Breakfast", "servings": "1 bowl", "blurb": "Warm quinoa with fruit and nuts.", "ingredients": ["1/2 cup cooked quinoa", "1/2 cup milk", "1/2 banana", "2 tbsp nuts", "Cinnamon"], "steps": ["Warm quinoa with milk. Top with banana and nuts."], "tip": "Batch-cook quinoa on Sunday."},
  {"id": "spinach-feta-omelette", "title": "Spinach Feta Omelette", "time": 12, "tag": "Protein", "category": "Breakfast", "servings": "1 omelette", "blurb": "Classic omelette with greens and cheese.", "ingredients": ["3 eggs", "1 cup spinach", "2 tbsp feta", "Oil"], "steps": ["Whisk eggs. Wilt spinach. Add eggs and feta. Fold."], "tip": "Pull while center is soft."},
  {"id": "protein-pancakes", "title": "Protein Pancakes", "time": 15, "tag": "Training day", "category": "Breakfast", "servings": "6 pancakes", "blurb": "Pancakes that deliver protein.", "ingredients": ["1 scoop protein", "1 banana", "2 eggs", "1/4 cup oats"], "steps": ["Blend. Cook small pancakes 2 min per side."], "tip": "Medium heat for cooked centers."},
  {"id": "miso-soup-egg", "title": "Miso Soup with Egg", "time": 10, "tag": "Light", "category": "Breakfast", "servings": "1 bowl", "blurb": "Warm savory light morning option.", "ingredients": ["1 tbsp miso", "1 1/2 cups water", "1 egg", "Scallion"], "steps": ["Heat water. Whisk in miso. Add egg and scallion."], "tip": "Don't hard-boil miso."},
  {"id": "ricotta-toast-honey", "title": "Ricotta Toast with Honey", "time": 7, "tag": "Simple", "category": "Breakfast", "servings": "1 plate", "blurb": "Creamy ricotta on toast with fruit.", "ingredients": ["1 slice bread", "1/3 cup ricotta", "Honey", "Berries"], "steps": ["Toast. Spread ricotta. Drizzle honey. Add fruit."], "tip": "Whole-milk ricotta tastes better."},
];
