import type { Recipe } from "./types";

export const BREAKFAST_PART_3: Recipe[] = [
  {"id": "huevos-rancheros", "title": "Simple Huevos Rancheros", "time": 20, "tag": "Savory", "category": "Breakfast", "servings": "1 plate", "blurb": "Eggs, beans, salsa basics.", "ingredients": ["2 eggs", "1/2 cup black beans", "Salsa", "1 tortilla", "Avocado optional"], "steps": ["Warm beans and tortilla. Fry eggs. Stack with salsa."], "tip": "Char tortilla in dry pan."},
  {"id": "buckwheat-porridge", "title": "Buckwheat Porridge", "time": 20, "tag": "Gluten-free", "category": "Breakfast", "servings": "1 bowl", "blurb": "Earthy porridge with nutty bite.", "ingredients": ["1/2 cup buckwheat", "1 1/2 cups liquid", "Salt", "Fruit, nuts"], "steps": ["Simmer 15–20 min. Top as desired."], "tip": "Rinse groats first."},
  {"id": "egg-white-veggie", "title": "Egg White Veggie Cup", "time": 12, "tag": "Lean", "category": "Breakfast", "servings": "1 serving", "blurb": "Lighter eggs with vegetable volume.", "ingredients": ["1 cup egg whites", "1 cup spinach and peppers", "Herbs"], "steps": ["Sauté vegetables. Add egg whites until set."], "tip": "Add one whole egg for richness."},
  {"id": "chia-oat-overnight", "title": "Chia-Oat Overnight Mix", "time": 5, "tag": "Prep-ahead", "category": "Breakfast", "servings": "1 jar", "blurb": "Oats plus chia for extra fiber.", "ingredients": ["1/3 cup oats", "1 tbsp chia", "3/4 cup milk", "1/4 cup yogurt"], "steps": ["Mix. Refrigerate overnight. Top with fruit."], "tip": "Add protein powder if training."},
  {"id": "smashed-pea-toast", "title": "Smashed Pea Toast", "time": 12, "tag": "Plant protein", "category": "Breakfast", "servings": "1 plate", "blurb": "Bright peas on toast with lemon and mint.", "ingredients": ["1 cup peas", "1 slice bread", "Lemon, mint, oil"], "steps": ["Mash warm peas with oil and lemon. Spread on toast."], "tip": "Frozen peas work perfectly."},
  {"id": "quinoa-egg-bowl", "title": "Savory Quinoa Egg Bowl", "time": 15, "tag": "Balanced", "category": "Breakfast", "servings": "1 bowl", "blurb": "Savory quinoa with a soft egg.", "ingredients": ["3/4 cup cooked quinoa", "1 egg", "Greens", "Olive oil"], "steps": ["Warm quinoa. Cook egg. Toss greens. Assemble."], "tip": "Meal-prep quinoa keeps this fast."},
  {"id": "cinnamon-raisin-oats", "title": "Cinnamon Raisin Oats", "time": 10, "tag": "Comfort", "category": "Breakfast", "servings": "1 bowl", "blurb": "Classic flavors, better ingredients.", "ingredients": ["1/2 cup oats", "1 cup liquid", "2 tbsp raisins", "1/2 tsp cinnamon"], "steps": ["Simmer everything until thick."], "tip": "Soak dry raisins first."},
  {"id": "turkey-sausage-eggs", "title": "Turkey Sausage & Eggs", "time": 15, "tag": "High protein", "category": "Breakfast", "servings": "1 plate", "blurb": "Lean sausage with eggs and greens.", "ingredients": ["2 turkey sausage links", "2 eggs", "Greens or tomatoes"], "steps": ["Cook sausage. Cook eggs. Serve with greens."], "tip": "Watch sodium on labels."},
  {"id": "green-smoothie-bowl", "title": "Green Smoothie Bowl", "time": 8, "tag": "Micronutrients", "category": "Breakfast", "servings": "1 bowl", "blurb": "Thick blended greens eaten with a spoon.", "ingredients": ["1 frozen banana", "1 cup spinach", "1/2 cup frozen mango", "1/2 cup milk"], "steps": ["Blend very thick. Top with seeds and berries."], "tip": "Less liquid = spoonable."},
  {"id": "polenta-breakfast", "title": "Creamy Polenta Breakfast", "time": 20, "tag": "Comfort", "category": "Breakfast", "servings": "2 servings", "blurb": "Soft corn porridge, sweet or savory.", "ingredients": ["1/2 cup polenta", "2 cups liquid", "Salt", "Egg or honey"], "steps": ["Whisk polenta into simmering liquid. Cook until creamy."], "tip": "Stir often to prevent lumps."},
];
