import type { Recipe } from "./types";

export const BREAKFAST_PART_0: Recipe[] = [
  {"id": "overnight-oats", "title": "Overnight Oats", "time": 5, "tag": "Prep-ahead", "category": "Breakfast", "servings": "1 jar", "blurb": "Prep once, eat for days.", "ingredients": ["1/2 cup rolled oats", "3/4 cup milk", "1/3 cup Greek yogurt", "1/2 banana", "1/2 cup berries", "1 tsp chia", "Cinnamon"], "steps": ["Mix oats, milk, yogurt, chia, cinnamon in a jar.", "Refrigerate 4+ hours.", "Top with banana and berries."], "tip": "Prep three jars at once."},
  {"id": "greek-yogurt-bowl", "title": "Greek Yogurt Protein Bowl", "time": 5, "tag": "High protein", "category": "Breakfast", "servings": "1 bowl", "blurb": "Fast protein with fruit and crunch.", "ingredients": ["1 cup Greek yogurt", "1/2 cup berries", "1 tbsp honey", "2 tbsp nuts or granola"], "steps": ["Spoon yogurt. Top with berries, honey, crunch."], "tip": "Full-fat keeps you fuller."},
  {"id": "veggie-egg-scramble", "title": "Veggie Egg Scramble", "time": 12, "tag": "Protein", "category": "Breakfast", "servings": "1 plate", "blurb": "Eggs and vegetables, simple and reliable.", "ingredients": ["3 eggs", "1 cup mixed vegetables", "1 tsp oil", "Salt and pepper"], "steps": ["Whisk eggs. Sauté vegetables. Scramble eggs until just set."], "tip": "Cook vegetables first."},
  {"id": "avocado-toast-egg", "title": "Avocado Toast with Egg", "time": 10, "tag": "Balanced", "category": "Breakfast", "servings": "1 plate", "blurb": "Fiber, fat, and protein without a long cook.", "ingredients": ["1 slice whole-grain bread", "1/2 avocado", "1–2 eggs", "Salt, pepper, chili"], "steps": ["Toast bread. Mash avocado. Cook eggs. Assemble."], "tip": "Add smoked salmon for more protein."},
  {"id": "banana-protein-smoothie", "title": "Banana Protein Smoothie", "time": 5, "tag": "Recovery", "category": "Breakfast", "servings": "1 glass", "blurb": "Blend-and-go fuel after training.", "ingredients": ["1 banana", "1 scoop protein or 3/4 cup Greek yogurt", "1 cup milk", "1 tbsp nut butter"], "steps": ["Blend until smooth."], "tip": "Frozen banana thickens it."},
  {"id": "chia-pudding", "title": "Chia Pudding", "time": 5, "tag": "Prep-ahead", "category": "Breakfast", "servings": "1 jar", "blurb": "Fiber-forward make-ahead breakfast.", "ingredients": ["3 tbsp chia", "1 cup milk", "1 tsp vanilla", "1 tsp honey", "Fruit"], "steps": ["Stir all. Rest 5 min, stir again. Refrigerate 2+ hours."], "tip": "Stir twice to avoid clumps."},
  {"id": "oatmeal-peanut-butter", "title": "Peanut Butter Oatmeal", "time": 10, "tag": "Sustaining", "category": "Breakfast", "servings": "1 bowl", "blurb": "Warm oats with protein and fat.", "ingredients": ["1/2 cup oats", "1 cup liquid", "1 tbsp peanut butter", "1/2 banana", "Pinch salt"], "steps": ["Simmer oats. Stir in peanut butter. Top with banana."], "tip": "Salt makes peanut butter taste fuller."},
  {"id": "egg-muffin-cups", "title": "Egg Muffin Cups", "time": 25, "tag": "Meal prep", "category": "Breakfast", "servings": "6 muffins", "blurb": "Bake once, reheat all week.", "ingredients": ["6 eggs", "1 cup chopped vegetables", "Cheese optional", "Salt and pepper"], "steps": ["Heat oven 375°F. Whisk eggs with vegetables. Bake 18–22 min."], "tip": "Reheat 30–45 seconds."},
  {"id": "smoked-salmon-plate", "title": "Smoked Salmon Breakfast Plate", "time": 8, "tag": "Omega-3", "category": "Breakfast", "servings": "1 plate", "blurb": "No-cook protein with healthy fats.", "ingredients": ["3–4 oz smoked salmon", "2 eggs or avocado", "Cucumber", "Bread", "Lemon, dill"], "steps": ["Arrange on a plate. Finish with lemon and dill."], "tip": "Quality ingredients do the work."},
  {"id": "cottage-cheese-bowl", "title": "Cottage Cheese Berry Bowl", "time": 5, "tag": "High protein", "category": "Breakfast", "servings": "1 bowl", "blurb": "High-protein and actually filling.", "ingredients": ["1 cup cottage cheese", "1/2 cup berries", "1 tbsp honey", "2 tbsp nuts"], "steps": ["Top cottage cheese with berries, honey, nuts."], "tip": "Blend if texture bothers you."},
];
