import type { Recipe } from "./types";

export const BREAKFAST_PART_2: Recipe[] = [
  {"id": "steel-cut-oats", "title": "Steel-Cut Oats", "time": 25, "tag": "Slow carb", "category": "Breakfast", "servings": "2 servings", "blurb": "Chewier oats with longer energy.", "ingredients": ["1/2 cup steel-cut oats", "2 cups water", "Pinch salt"], "steps": ["Simmer 20–25 min until creamy."], "tip": "Batch and reheat with milk."},
  {"id": "shakshuka-single", "title": "Single-Serve Shakshuka", "time": 20, "tag": "Savory", "category": "Breakfast", "servings": "1 serving", "blurb": "Eggs poached in spiced tomato sauce.", "ingredients": ["1/2 cup tomato sauce", "Cumin, paprika", "2 eggs", "Bread"], "steps": ["Simmer sauce with spices. Crack eggs. Cover until set."], "tip": "Don't overcook yolks."},
  {"id": "berry-baked-oats", "title": "Berry Baked Oats", "time": 30, "tag": "Meal prep", "category": "Breakfast", "servings": "2 servings", "blurb": "Oats baked like a soft cake.", "ingredients": ["1 cup oats", "1 banana", "1 egg", "1/2 cup milk", "1/2 cup berries", "1 tsp baking powder"], "steps": ["Mix. Bake 350°F 25–30 min."], "tip": "Slice and reheat all week."},
  {"id": "lox-toast", "title": "Open-Face Lox Toast", "time": 8, "tag": "Omega-3", "category": "Breakfast", "servings": "1 plate", "blurb": "Classic flavors, lighter base.", "ingredients": ["1 slice bread", "2 oz smoked salmon", "1 tbsp cream cheese or yogurt", "Dill, cucumber"], "steps": ["Toast. Spread. Layer salmon and toppings."], "tip": "Yogurt works for less richness."},
  {"id": "coffee-protein-smoothie", "title": "Coffee Protein Smoothie", "time": 5, "tag": "Caffeine + protein", "category": "Breakfast", "servings": "1 glass", "blurb": "Breakfast and coffee in one.", "ingredients": ["1 cup cold coffee", "1 scoop protein", "1/2 banana", "1/2 cup milk", "Ice"], "steps": ["Blend until frothy."], "tip": "Brew coffee the night before."},
  {"id": "mushroom-egg-saute", "title": "Mushroom Egg Sauté", "time": 15, "tag": "Savory", "category": "Breakfast", "servings": "1 plate", "blurb": "Earthy mushrooms with soft eggs.", "ingredients": ["2 cups mushrooms", "2–3 eggs", "Oil", "Garlic, thyme"], "steps": ["Brown mushrooms. Scramble eggs soft. Combine."], "tip": "High heat so mushrooms don't steam."},
  {"id": "almond-butter-banana-toast", "title": "Almond Butter Banana Toast", "time": 5, "tag": "Quick fuel", "category": "Breakfast", "servings": "1 plate", "blurb": "Three ingredients, solid energy.", "ingredients": ["1 slice bread", "1 tbsp almond butter", "1/2 banana"], "steps": ["Toast. Spread. Add banana."], "tip": "Choose natural almond butter."},
  {"id": "veggie-frittata", "title": "Veggie Frittata", "time": 30, "tag": "Meal prep", "category": "Breakfast", "servings": "4 slices", "blurb": "One pan, four breakfasts.", "ingredients": ["6 eggs", "2 cups vegetables", "1/4 cup milk", "Cheese optional"], "steps": ["Sauté vegetables. Add eggs. Bake 350°F 20–25 min."], "tip": "Cool before slicing."},
  {"id": "tropical-yogurt-bowl", "title": "Tropical Yogurt Bowl", "time": 5, "tag": "Fresh", "category": "Breakfast", "servings": "1 bowl", "blurb": "Coconut, pineapple, mango energy.", "ingredients": ["1 cup yogurt", "1/2 cup pineapple or mango", "Coconut flakes", "Seeds"], "steps": ["Assemble yogurt and toppings."], "tip": "Unsweetened yogurt keeps sugar down."},
  {"id": "sardine-toast", "title": "Sardine Toast", "time": 7, "tag": "Omega-3", "category": "Breakfast", "servings": "1 plate", "blurb": "Underrated, cheap, nutrient-dense.", "ingredients": ["1 can sardines", "1 slice bread", "Lemon", "Pepper"], "steps": ["Toast. Top with sardines, lemon, pepper."], "tip": "Mash into a spread if preferred."},
];
