import type { Recipe } from "./types";

export const BREAKFAST_PART_4: Recipe[] = [
  {"id": "kimchi-rice-egg", "title": "Kimchi Fried Rice with Egg", "time": 15, "tag": "Gut-friendly", "category": "Breakfast", "servings": "1 bowl", "blurb": "Fermented heat with leftover rice.", "ingredients": ["1 cup cooked rice", "1/3 cup kimchi", "1 egg", "Oil", "Scallion"], "steps": ["Stir-fry kimchi and rice. Top with fried egg."], "tip": "Day-old rice fries best."},
  {"id": "protein-overnight-oats", "title": "Protein Overnight Oats", "time": 5, "tag": "High protein", "category": "Breakfast", "servings": "1 jar", "blurb": "Overnight oats with a protein scoop.", "ingredients": ["1/2 cup oats", "1 scoop protein", "1 cup milk", "1 tbsp chia"], "steps": ["Mix. Refrigerate overnight. Top with fruit."], "tip": "Whey mixes smoother."},
  {"id": "asparagus-eggs", "title": "Asparagus & Soft Eggs", "time": 15, "tag": "Spring plate", "category": "Breakfast", "servings": "1 plate", "blurb": "Tender asparagus with jammy eggs.", "ingredients": ["1 bunch asparagus", "2 eggs", "Oil, lemon, salt"], "steps": ["Cook asparagus. Soft-boil eggs 6 min. Plate with lemon."], "tip": "6-minute eggs for jammy yolks."},
  {"id": "cottage-pancakes", "title": "Cottage Cheese Pancakes", "time": 15, "tag": "High protein", "category": "Breakfast", "servings": "6 pancakes", "blurb": "Pancakes with built-in protein.", "ingredients": ["1/2 cup cottage cheese", "2 eggs", "1/4 cup oats", "Cinnamon"], "steps": ["Blend. Cook small pancakes on medium."], "tip": "Blend fully for smooth batter."},
  {"id": "mediterranean-breakfast", "title": "Mediterranean Breakfast Plate", "time": 10, "tag": "Balanced", "category": "Breakfast", "servings": "1 plate", "blurb": "Olives, cucumber, tomato, egg, bread.", "ingredients": ["1–2 eggs", "Cucumber, tomato, olives", "Hummus", "Bread"], "steps": ["Arrange everything. Serve hummus on the side."], "tip": "Pre-boil eggs for zero cooking."},
  {"id": "matcha-chia", "title": "Matcha Chia Pudding", "time": 5, "tag": "Focus", "category": "Breakfast", "servings": "1 jar", "blurb": "Chia pudding with gentle caffeine.", "ingredients": ["3 tbsp chia", "1 cup milk", "1 tsp matcha", "1 tsp honey"], "steps": ["Whisk matcha into milk. Mix all. Refrigerate 2+ hours."], "tip": "Sift matcha to avoid clumps."},
  {"id": "black-bean-tacos-b", "title": "Black Bean Breakfast Tacos", "time": 15, "tag": "Fiber", "category": "Breakfast", "servings": "2 tacos", "blurb": "Savory tacos before noon.", "ingredients": ["2 corn tortillas", "1/2 cup black beans", "2 eggs", "Salsa"], "steps": ["Warm tortillas and beans. Scramble eggs. Assemble."], "tip": "Double beans if training."},
  {"id": "zucchini-frittata", "title": "Zucchini Frittata", "time": 25, "tag": "Vegetable-forward", "category": "Breakfast", "servings": "4 servings", "blurb": "Light frittata for summer zucchini.", "ingredients": ["6 eggs", "2 cups grated zucchini", "1/4 onion", "Cheese optional"], "steps": ["Squeeze zucchini dry. Mix with eggs. Bake 350°F 20–25 min."], "tip": "Dry zucchini or it gets watery."},
  {"id": "berry-compote-yogurt", "title": "Warm Berry Compote Yogurt", "time": 8, "tag": "Antioxidants", "category": "Breakfast", "servings": "1 bowl", "blurb": "Warm berries over cold yogurt.", "ingredients": ["1 cup berries", "1 tsp honey", "1 cup Greek yogurt", "Nuts"], "steps": ["Simmer berries 3–5 min. Spoon over yogurt."], "tip": "Frozen berries work year-round."},
  {"id": "rice-porridge", "title": "Savory Rice Porridge", "time": 15, "tag": "Comfort", "category": "Breakfast", "servings": "1 bowl", "blurb": "Congee-style from leftover rice.", "ingredients": ["1 cup cooked rice", "2 cups broth", "Ginger, scallion, soy", "Optional egg"], "steps": ["Simmer rice in broth until creamy. Season and top."], "tip": "Mash some rice for thickness."},
];
