import type { Recipe } from "./types";

export const DESSERT_PART_2: Recipe[] = [
  {"id": "cocoa-roasted-almonds", "title": "Cocoa Roasted Almonds", "time": 20, "tag": "Crunchy", "category": "Dessert", "servings": "2 servings", "blurb": "Chocolate-dusted roasted almonds.", "ingredients": ["1 cup almonds", "1 tbsp cocoa", "1 tsp honey", "Pinch salt"], "steps": ["Toss. Roast 300F 15 min."], "tip": "Cool completely.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}},
  {"id": "mango-sorbet-blend", "title": "Mango Sorbet Blend", "time": 5, "tag": "Dairy-free", "category": "Dessert", "servings": "1 bowl", "blurb": "Frozen mango blended smooth.", "ingredients": ["2 cups frozen mango", "Splash of juice or water"], "steps": ["Blend until sorbet texture."], "tip": "No added sugar needed.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "baked-pears-yogurt", "title": "Baked Pears with Yogurt", "time": 30, "tag": "Warm", "category": "Dessert", "servings": "2 servings", "blurb": "Soft pears over cool yogurt.", "ingredients": ["2 pears", "Cinnamon", "Greek yogurt"], "steps": ["Bake pears 350F 25 min. Serve over yogurt."], "tip": "A drizzle of honey is enough.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean"]},
  {"id": "oat-bars", "title": "Homemade Oat Bars", "time": 30, "tag": "Meal prep", "category": "Dessert", "servings": "8 bars", "blurb": "Chewy oat bars you control.", "ingredients": ["2 cups oats", "1/2 cup nut butter", "1/3 cup honey", "Optional chocolate"], "steps": ["Mix. Press into pan. Bake 325F 20 min. Cool. Cut."], "tip": "Store airtight.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["meal-prep"]},
  {"id": "cinnamon-sugar-apple", "title": "Cinnamon Apple Slices", "time": 5, "tag": "Simple", "category": "Dessert", "servings": "1 apple", "blurb": "Raw apple that feels like dessert.", "ingredients": ["1 apple", "Cinnamon"], "steps": ["Slice. Dust with cinnamon."], "tip": "Microwave 1 min for a warm version.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "ricotta-honey-bowl", "title": "Ricotta Honey Bowl", "time": 5, "tag": "Creamy", "category": "Dessert", "servings": "1 bowl", "blurb": "Sweet ricotta with honey and nuts.", "ingredients": ["1/2 cup ricotta", "Honey", "Nuts", "Optional cocoa"], "steps": ["Sweeten and top."], "tip": "Whole-milk ricotta tastes best.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "frozen-yogurt-bark", "title": "Yogurt Bark", "time": 10, "tag": "Prep-ahead", "category": "Dessert", "servings": "6 pieces", "blurb": "Yogurt frozen with fruit and chocolate.", "ingredients": ["1 cup Greek yogurt", "Berries", "Dark chocolate drizzle"], "steps": ["Spread yogurt. Top. Freeze. Break."], "tip": "Store in freezer bag.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "mediterranean", "meal-prep", "quick"]},
  {"id": "chai-poached-apples", "title": "Chai Poached Apples", "time": 25, "tag": "Warm", "category": "Dessert", "servings": "2 servings", "blurb": "Apples in spiced tea.", "ingredients": ["2 apples", "Chai tea", "Honey"], "steps": ["Poach apples in strong chai 15-20 min."], "tip": "Reduce liquid to a syrup.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}},
  {"id": "almond-butter-cups-home", "title": "Homemade Almond Butter Cups", "time": 20, "tag": "Rich", "category": "Dessert", "servings": "6 cups", "blurb": "Dark chocolate and almond butter.", "ingredients": ["Dark chocolate", "Almond butter", "Pinch salt"], "steps": ["Melt half chocolate into liners. Add almond butter. Cap with chocolate. Chill."], "tip": "Mini muffin liners work.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}},
  {"id": "berry-crisp-single", "title": "Single-Serve Berry Crisp", "time": 25, "tag": "Warm", "category": "Dessert", "servings": "1 serving", "blurb": "Personal crisp in a ramekin.", "ingredients": ["1 cup berries", "1 tbsp oats", "1 tsp butter", "Cinnamon"], "steps": ["Top berries with oat mix. Bake 350F 20 min."], "tip": "Use frozen berries.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}},
];
