import type { Recipe } from "./types";

export const DESSERT_PART_4: Recipe[] = [
  {"id": "sesame-dates", "title": "Sesame Date Bites", "time": 10, "tag": "No-bake", "category": "Dessert", "servings": "6 bites", "blurb": "Dates, sesame, a little salt.", "ingredients": ["6 dates", "Sesame seeds", "Pinch salt"], "steps": ["Roll dates in sesame."], "tip": "Toast sesame first.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "baked-banana", "title": "Baked Banana", "time": 15, "tag": "Warm", "category": "Dessert", "servings": "1 banana", "blurb": "Banana roasted until soft and caramelized.", "ingredients": ["1 banana", "Cinnamon", "Optional dark chocolate"], "steps": ["Bake 375F 12-15 min in peel or sliced."], "tip": "Split and add yogurt.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}},
  {"id": "fruit-gelatin-home", "title": "Home Fruit Gelatin", "time": 15, "tag": "Light", "category": "Dessert", "servings": "4 servings", "blurb": "Gelatin with real fruit juice.", "ingredients": ["2 cups fruit juice", "Gelatin powder", "Fruit pieces"], "steps": ["Bloom gelatin. Dissolve in warm juice. Add fruit. Chill."], "tip": "Avoid fresh pineapple in gelatin.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}},
  {"id": "cocoa-chia-bark", "title": "Cocoa Chia Bark", "time": 10, "tag": "Crunchy", "category": "Dessert", "servings": "6 pieces", "blurb": "Set chocolate with chia and nuts.", "ingredients": ["Dark chocolate", "Chia", "Nuts"], "steps": ["Melt chocolate. Stir in chia and nuts. Spread. Chill."], "tip": "Break into shards.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["quick"]},
  {"id": "peach-yogurt", "title": "Peach & Yogurt", "time": 5, "tag": "Simple", "category": "Dessert", "servings": "1 bowl", "blurb": "Ripe peach over yogurt.", "ingredients": ["1 peach", "3/4 cup Greek yogurt", "Honey optional"], "steps": ["Slice peach over yogurt."], "tip": "Best with ripe summer peaches.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "spiced-baked-milk", "title": "Warm Spiced Milk", "time": 5, "tag": "Comfort", "category": "Dessert", "servings": "1 cup", "blurb": "Hot milk with cinnamon and honey.", "ingredients": ["1 cup milk", "Cinnamon", "1 tsp honey"], "steps": ["Warm. Stir. Sip."], "tip": "Turmeric optional.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "fig-and-ricotta", "title": "Fig & Ricotta", "time": 5, "tag": "Elegant", "category": "Dessert", "servings": "1 plate", "blurb": "Fresh figs with ricotta and honey.", "ingredients": ["2-3 figs", "Ricotta", "Honey"], "steps": ["Plate and drizzle."], "tip": "Dried figs work when fresh aren't in season.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "chocolate-avocado-pops", "title": "Chocolate Avocado Pops", "time": 10, "tag": "Frozen", "category": "Dessert", "servings": "4 pops", "blurb": "Blended avocado chocolate frozen in molds.", "ingredients": ["1 avocado", "Cocoa", "Honey", "Milk"], "steps": ["Blend. Freeze in molds."], "tip": "Run mold under water to release.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "berry-compote-dessert", "title": "Berry Compote over Yogurt", "time": 8, "tag": "Warm-cold", "category": "Dessert", "servings": "1 bowl", "blurb": "Warm berries over cold yogurt.", "ingredients": ["1 cup berries", "Honey", "Greek yogurt"], "steps": ["Simmer berries. Spoon over yogurt."], "tip": "Works as breakfast too.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "almond-cantaloupe", "title": "Cantaloupe with Almonds", "time": 5, "tag": "Fresh", "category": "Dessert", "servings": "1 plate", "blurb": "Sweet melon with crunchy almonds.", "ingredients": ["Cantaloupe", "Handful almonds"], "steps": ["Cube. Top."], "tip": "Slightly salted almonds contrast well.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
];
