import type { Recipe } from "./types";

export const DESSERT_PART_1: Recipe[] = [
  {"id": "oatmeal-cookie-energy", "title": "Energy Cookie Balls", "time": 15, "tag": "No-bake", "category": "Dessert", "servings": "8 balls", "blurb": "Oats, nut butter, honey - rolled.", "ingredients": ["1 cup oats", "1/2 cup nut butter", "2 tbsp honey", "Optional chocolate chips"], "steps": ["Mix. Roll. Chill."], "tip": "Keep refrigerated.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "cinnamon-roasted-pears", "title": "Cinnamon Roasted Pears", "time": 30, "tag": "Warm", "category": "Dessert", "servings": "2 servings", "blurb": "Roasted pear halves with cinnamon.", "ingredients": ["2 pears", "Cinnamon", "Honey"], "steps": ["Halve. Roast 375F 25 min. Drizzle honey."], "tip": "Add walnuts.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}},
  {"id": "coconut-macaroons-light", "title": "Light Coconut Macaroons", "time": 25, "tag": "Chewy", "category": "Dessert", "servings": "8 cookies", "blurb": "Coconut cookies with less guilt.", "ingredients": ["2 cups shredded coconut", "2 egg whites", "2 tbsp honey", "Vanilla"], "steps": ["Mix. Scoop. Bake 325F 15-18 min."], "tip": "Use unsweetened coconut.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}},
  {"id": "grilled-peach", "title": "Grilled Peach", "time": 10, "tag": "Summer", "category": "Dessert", "servings": "2 halves", "blurb": "Caramelized peach, warm and sweet.", "ingredients": ["1 peach", "Honey optional", "Yogurt"], "steps": ["Halve. Grill cut-side down 3-4 min. Serve with yogurt."], "tip": "Nectarines work too.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "avocado-chocolate-mousse", "title": "Avocado Chocolate Mousse", "time": 10, "tag": "Rich", "category": "Dessert", "servings": "2 servings", "blurb": "Silky mousse from avocado and cocoa.", "ingredients": ["1 ripe avocado", "2 tbsp cocoa", "2 tbsp honey or maple", "Splash of milk"], "steps": ["Blend until completely smooth. Chill."], "tip": "Ripe avocado is essential.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "apple-crumble-mini", "title": "Mini Apple Crumble", "time": 30, "tag": "Comfort", "category": "Dessert", "servings": "2 servings", "blurb": "Small-batch crumble.", "ingredients": ["2 apples", "2 tbsp oats", "1 tbsp butter", "Cinnamon", "1 tsp honey"], "steps": ["Cook apples. Top with oat mix. Bake 350F 15 min."], "tip": "Serve with yogurt not ice cream.", "macros": {"protein": 8, "carbs": 40, "fat": 14, "calories": 318}},
  {"id": "watermelon-mint", "title": "Watermelon with Mint", "time": 5, "tag": "Hydrating", "category": "Dessert", "servings": "2 cups", "blurb": "Cold, sweet, refreshing.", "ingredients": ["Watermelon", "Fresh mint", "Lime"], "steps": ["Cube. Toss with mint and lime."], "tip": "Keep very cold.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "protein-cheesecake-cup", "title": "Protein Cheesecake Cup", "time": 10, "tag": "High protein", "category": "Dessert", "servings": "1 cup", "blurb": "Cheesecake flavor from Greek yogurt.", "ingredients": ["1 cup Greek yogurt", "1 tbsp cream cheese optional", "Honey", "Vanilla", "Berry topping"], "steps": ["Mix base. Chill. Top with berries."], "tip": "Strain yogurt for thicker texture.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "dark-chocolate-strawberries", "title": "Chocolate-Dipped Strawberries", "time": 15, "tag": "Classic", "category": "Dessert", "servings": "8 strawberries", "blurb": "Fruit with a thin chocolate shell.", "ingredients": ["Strawberries", "2 oz dark chocolate"], "steps": ["Melt chocolate. Dip. Set on parchment."], "tip": "Dry strawberries fully before dipping.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "banana-nice-cream-pb", "title": "Peanut Butter Nice Cream", "time": 5, "tag": "Rich", "category": "Dessert", "servings": "1 bowl", "blurb": "Banana soft-serve with peanut butter.", "ingredients": ["2 frozen bananas", "1 tbsp peanut butter"], "steps": ["Blend until creamy."], "tip": "Pinch of salt helps.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
];
