import type { Recipe } from "./types";

export const DESSERT_PART_3: Recipe[] = [
  {"id": "matcha-pudding", "title": "Matcha Chia Dessert", "time": 5, "tag": "Focus", "category": "Dessert", "servings": "1 jar", "blurb": "Chia pudding with matcha and honey.", "ingredients": ["3 tbsp chia", "1 cup milk", "1 tsp matcha", "Honey"], "steps": ["Mix. Refrigerate 2+ hours."], "tip": "Sift matcha.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["meal-prep", "quick"]},
  {"id": "grilled-pineapple", "title": "Grilled Pineapple", "time": 10, "tag": "Caramelized", "category": "Dessert", "servings": "2 servings", "blurb": "Hot grill marks on sweet pineapple.", "ingredients": ["Pineapple rings", "Optional cinnamon"], "steps": ["Grill 2-3 min per side."], "tip": "Serve with yogurt.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "cocoa-banana", "title": "Cocoa Dusted Banana", "time": 3, "tag": "Simple", "category": "Dessert", "servings": "1 banana", "blurb": "Banana that tastes like dessert.", "ingredients": ["1 banana", "1 tsp cocoa"], "steps": ["Slice. Dust with cocoa."], "tip": "Add a spoon of nut butter.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "date-chocolate", "title": "Chocolate-Stuffed Dates", "time": 10, "tag": "Sweet", "category": "Dessert", "servings": "4 dates", "blurb": "Dates filled with dark chocolate.", "ingredients": ["4 dates", "Dark chocolate pieces", "Optional sea salt"], "steps": ["Pit. Stuff. Optional melt-and-set."], "tip": "Medjool dates preferred.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "lemon-yogurt-mousse", "title": "Lemon Yogurt Mousse", "time": 10, "tag": "Bright", "category": "Dessert", "servings": "2 servings", "blurb": "Light, tangy, cold.", "ingredients": ["1 cup Greek yogurt", "Lemon zest and juice", "Honey"], "steps": ["Mix. Chill."], "tip": "Zest makes it perfume-y.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "pumpkin-pudding", "title": "Pumpkin Pudding", "time": 10, "tag": "Seasonal", "category": "Dessert", "servings": "2 servings", "blurb": "Pumpkin, spice, yogurt.", "ingredients": ["1/2 cup pumpkin puree", "1/2 cup Greek yogurt", "Cinnamon, ginger", "Honey"], "steps": ["Mix until smooth. Chill."], "tip": "Canned pumpkin is fine.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "coconut-chia", "title": "Coconut Chia Pudding", "time": 5, "tag": "Dairy-free", "category": "Dessert", "servings": "1 jar", "blurb": "Tropical chia pudding.", "ingredients": ["3 tbsp chia", "1 cup coconut milk", "Honey", "Fruit"], "steps": ["Mix. Refrigerate 2+ hours."], "tip": "Shake the can of coconut milk.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["meal-prep", "quick"]},
  {"id": "brownie-bite-black-bean", "title": "Black Bean Brownie Bites", "time": 30, "tag": "Hidden fiber", "category": "Dessert", "servings": "12 bites", "blurb": "Brownies with a can of black beans.", "ingredients": ["1 can black beans", "Cocoa", "Eggs", "Honey", "Vanilla"], "steps": ["Blend. Bake 350F 20-25 min in mini tin."], "tip": "They freeze well.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["plant-forward"]},
  {"id": "sliced-orange-cinnamon", "title": "Orange with Cinnamon", "time": 3, "tag": "Bright", "category": "Dessert", "servings": "1 orange", "blurb": "Simple, fragrant, complete.", "ingredients": ["1 orange", "Cinnamon"], "steps": ["Slice. Dust."], "tip": "Blood oranges are excellent.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "affogato-yogurt", "title": "Yogurt Affogato", "time": 5, "tag": "Coffee dessert", "category": "Dessert", "servings": "1 serving", "blurb": "Hot espresso over cold yogurt or nice cream.", "ingredients": ["1/2 cup frozen yogurt or nice cream", "1 shot espresso"], "steps": ["Pour espresso over. Eat."], "tip": "Real espresso hits harder.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
];
