import type { Recipe } from "./types";

export const DESSERT_PART_0: Recipe[] = [
  {"id": "dark-chocolate-square", "title": "Dark Chocolate Square", "time": 1, "tag": "Simple", "category": "Dessert", "servings": "1-2 squares", "blurb": "Satisfy the craving without a spiral.", "ingredients": ["1-2 squares 70%+ dark chocolate"], "steps": ["Eat slowly."], "tip": "Buy bars, not bags of chips.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["quick"]},
  {"id": "frozen-banana-nice-cream", "title": "Banana Nice Cream", "time": 5, "tag": "Dairy-free", "category": "Dessert", "servings": "1 bowl", "blurb": "Blended frozen banana soft-serve.", "ingredients": ["2 frozen bananas", "Splash of milk", "Optional cocoa or peanut butter"], "steps": ["Blend until creamy. Serve immediately."], "tip": "Freeze bananas in chunks.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "greek-yogurt-parfait-dessert", "title": "Yogurt Berry Parfait", "time": 5, "tag": "High protein", "category": "Dessert", "servings": "1 cup", "blurb": "Dessert structure, breakfast macros.", "ingredients": ["Greek yogurt", "Berries", "Honey", "Granola sprinkle"], "steps": ["Layer."], "tip": "Keep granola light.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "baked-apple", "title": "Baked Apple", "time": 30, "tag": "Warm", "category": "Dessert", "servings": "1 apple", "blurb": "Cinnamon-soft apple, simple and comforting.", "ingredients": ["1 apple", "Cinnamon", "1 tsp butter or oil", "Optional raisins"], "steps": ["Core. Fill with cinnamon. Bake 350F 25-30 min."], "tip": "Serve with yogurt.", "macros": {"protein": 20, "carbs": 25, "fat": 18, "calories": 342}},
  {"id": "chia-chocolate-pudding", "title": "Chocolate Chia Pudding", "time": 5, "tag": "Prep-ahead", "category": "Dessert", "servings": "1 jar", "blurb": "Chocolate pudding with fiber.", "ingredients": ["3 tbsp chia", "1 cup milk", "1 tbsp cocoa", "1 tsp honey"], "steps": ["Mix. Refrigerate 2+ hours."], "tip": "Whisk cocoa in thoroughly.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["meal-prep", "quick"]},
  {"id": "fruit-salad", "title": "Fresh Fruit Salad", "time": 10, "tag": "Light", "category": "Dessert", "servings": "2 servings", "blurb": "Mixed fruit, bright and cold.", "ingredients": ["Mixed seasonal fruit", "Lime or mint"], "steps": ["Chop. Toss. Chill."], "tip": "No syrup needed.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}, "diet": ["quick"]},
  {"id": "protein-mug-cake", "title": "Protein Mug Cake", "time": 5, "tag": "Training sweet", "category": "Dessert", "servings": "1 mug", "blurb": "Single-serve cake in a mug.", "ingredients": ["1 scoop protein", "1 egg", "1 tbsp cocoa", "Splash of milk"], "steps": ["Mix in mug. Microwave 60-90 sec."], "tip": "Don't overcook or it dries.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "poached-pear", "title": "Poached Pear", "time": 25, "tag": "Elegant", "category": "Dessert", "servings": "2 servings", "blurb": "Pears simmered until tender.", "ingredients": ["2 pears", "Water", "Cinnamon stick", "Honey"], "steps": ["Simmer pears until tender 15-20 min."], "tip": "Serve with yogurt.", "macros": {"protein": 8, "carbs": 32, "fat": 14, "calories": 286}},
  {"id": "rice-pudding-light", "title": "Light Rice Pudding", "time": 30, "tag": "Comfort", "category": "Dessert", "servings": "3 servings", "blurb": "Creamy rice with less sugar.", "ingredients": ["1/2 cup rice", "2 cups milk", "1 tbsp honey", "Cinnamon", "Vanilla"], "steps": ["Simmer until thick. Sweeten lightly."], "tip": "Arborio makes it creamier.", "macros": {"protein": 8, "carbs": 40, "fat": 12, "calories": 300}},
  {"id": "strawberry-frozen-yogurt", "title": "Strawberry Frozen Yogurt", "time": 5, "tag": "High protein", "category": "Dessert", "servings": "1 bowl", "blurb": "Blended frozen strawberries and yogurt.", "ingredients": ["2 cups frozen strawberries", "1/2 cup Greek yogurt", "Honey optional"], "steps": ["Blend until soft-serve."], "tip": "Eat immediately.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
];
