import type { Recipe } from "./types";

export const DINNER_PART_2: Recipe[] = [
  {"id": "miso-glazed-salmon", "title": "Miso Glazed Salmon", "time": 20, "tag": "Omega-3", "category": "Dinner", "servings": "2 servings", "blurb": "Sweet-savory miso crust on salmon.", "ingredients": ["2 salmon fillets", "1 tbsp miso", "1 tsp honey", "1 tsp soy"], "steps": ["Mix glaze. Spread on salmon. Bake 400F 12-15 min."], "tip": "Broil last minute for caramelization.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein"]},
  {"id": "chicken-fajitas", "title": "Chicken Fajitas", "time": 25, "tag": "High protein", "category": "Dinner", "servings": "3 servings", "blurb": "Sizzling peppers and chicken.", "ingredients": ["1 lb chicken strips", "Peppers, onion", "Fajita spices", "Tortillas"], "steps": ["Cook chicken hot. Add peppers. Serve with tortillas."], "tip": "High heat for char.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein"]},
  {"id": "mushroom-risotto", "title": "Mushroom Risotto", "time": 40, "tag": "Comfort", "category": "Dinner", "servings": "3 servings", "blurb": "Creamy rice without needing fancy technique.", "ingredients": ["1 cup arborio rice", "Mushrooms", "Broth", "Parmesan", "Onion"], "steps": ["Toast rice. Add broth ladle by ladle. Finish with parmesan."], "tip": "Stir often; keep broth warm.", "macros": {"protein": 20, "carbs": 40, "fat": 12, "calories": 348}},
  {"id": "turkey-burgers", "title": "Turkey Burgers", "time": 25, "tag": "Lean protein", "category": "Dinner", "servings": "4 burgers", "blurb": "Juicy turkey burgers with smart mix-ins.", "ingredients": ["1 lb ground turkey", "Grated onion", "Garlic, salt", "Buns or lettuce wraps"], "steps": ["Mix gently. Grill or pan 5-6 min per side to 165F."], "tip": "Don't overwork the meat.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein"]},
  {"id": "sheet-pan-salmon", "title": "Sheet-Pan Salmon & Asparagus", "time": 20, "tag": "Omega-3", "category": "Dinner", "servings": "2 servings", "blurb": "One sheet, twenty minutes.", "ingredients": ["2 salmon fillets", "Asparagus", "Lemon, oil", "Salt and pepper"], "steps": ["Arrange on sheet. Roast 400F 12-15 min."], "tip": "Add cherry tomatoes if you want.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein", "mediterranean"]},
  {"id": "beef-stew", "title": "Classic Beef Stew", "time": 90, "tag": "Hearty", "category": "Dinner", "servings": "6 servings", "blurb": "Slow, rich, worth the wait.", "ingredients": ["1.5 lb stewing beef", "Carrots, potato, onion", "Broth", "Tomato paste"], "steps": ["Brown beef. Simmer with vegetables 1.5 hours until tender."], "tip": "Better the next day.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein"]},
  {"id": "chicken-tikka-home", "title": "Home Chicken Tikka", "time": 35, "tag": "Spice", "category": "Dinner", "servings": "3 servings", "blurb": "Yogurt-marinated chicken, roasted hot.", "ingredients": ["1 lb chicken", "Yogurt", "Tikka spices", "Lemon"], "steps": ["Marinate 20+ min. Roast 425F 20-25 min."], "tip": "Broil at the end for char.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein"]},
  {"id": "zucchini-lasagna", "title": "Zucchini Lasagna", "time": 50, "tag": "Lower carb", "category": "Dinner", "servings": "6 servings", "blurb": "Lasagna structure with zucchini sheets.", "ingredients": ["Zucchini sliced long", "Meat or lentil sauce", "Ricotta", "Mozzarella"], "steps": ["Layer and bake 375F 35-40 min. Rest 10 min."], "tip": "Salt zucchini to release water.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["plant-forward"]},
  {"id": "grilled-swordfish", "title": "Grilled Swordfish", "time": 20, "tag": "Seafood", "category": "Dinner", "servings": "2 servings", "blurb": "Meaty fish that handles the grill.", "ingredients": ["2 swordfish steaks", "Lemon, oil", "Herbs"], "steps": ["Oil and season. Grill 4-5 min per side."], "tip": "Don't cook past medium.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein", "mediterranean"]},
  {"id": "chickpea-curry", "title": "Chickpea Curry", "time": 25, "tag": "Plant protein", "category": "Dinner", "servings": "3 servings", "blurb": "Pantry curry in under 30 minutes.", "ingredients": ["2 cans chickpeas", "Tomato", "Onion, garlic", "Curry spices", "Rice"], "steps": ["Saute aromatics. Add chickpeas and tomato. Simmer 15 min."], "tip": "Finish with spinach.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "mediterranean", "plant-forward"]},
];
