import type { Recipe } from "./types";

export const DINNER_PART_1: Recipe[] = [
  {"id": "salmon-teriyaki", "title": "Salmon Teriyaki", "time": 25, "tag": "Omega-3", "category": "Dinner", "servings": "2 servings", "blurb": "Glazed salmon with simple sides.", "ingredients": ["2 salmon fillets", "Teriyaki or soy-honey", "Rice", "Greens"], "steps": ["Bake or pan salmon. Glaze last few minutes."], "tip": "Watch sugar in bottled sauces.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein"]},
  {"id": "stuffed-peppers", "title": "Stuffed Peppers", "time": 45, "tag": "Balanced", "category": "Dinner", "servings": "4 peppers", "blurb": "Peppers filled with protein and grains.", "ingredients": ["4 bell peppers", "1 lb ground turkey or beef", "Rice", "Tomato sauce"], "steps": ["Brown filling. Stuff peppers. Bake 375F 30 min."], "tip": "Pre-boil peppers 5 min for softer texture.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein", "mediterranean"]},
  {"id": "tofu-curry", "title": "Tofu Coconut Curry", "time": 30, "tag": "Plant protein", "category": "Dinner", "servings": "3 servings", "blurb": "Creamy curry without the takeout oil load.", "ingredients": ["14 oz tofu", "Curry paste", "Coconut milk", "Vegetables", "Rice"], "steps": ["Brown tofu. Simmer with curry and vegetables 15 min."], "tip": "Full-fat coconut milk tastes better.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "plant-forward"]},
  {"id": "pork-tenderloin", "title": "Pork Tenderloin with Apples", "time": 35, "tag": "Lean protein", "category": "Dinner", "servings": "3 servings", "blurb": "Lean pork with sweet-savory apples.", "ingredients": ["1 pork tenderloin", "2 apples", "Onion", "Mustard, thyme"], "steps": ["Sear pork. Roast 400F with apples ~20 min to 145F."], "tip": "Don't overcook past 145F.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein"]},
  {"id": "fish-tacos", "title": "Fish Tacos", "time": 25, "tag": "Seafood", "category": "Dinner", "servings": "3 tacos", "blurb": "Crisp-tender fish with cabbage and lime.", "ingredients": ["8 oz white fish", "Tortillas", "Cabbage", "Lime, yogurt sauce"], "steps": ["Season and cook fish. Assemble tacos."], "tip": "Mahimahi, cod, or tilapia all work.", "macros": {"protein": 20, "carbs": 40, "fat": 12, "calories": 348}},
  {"id": "eggplant-parmesan-light", "title": "Light Eggplant Parmesan", "time": 45, "tag": "Vegetarian", "category": "Dinner", "servings": "4 servings", "blurb": "Baked, not fried, still satisfying.", "ingredients": ["1 large eggplant", "Tomato sauce", "Mozzarella", "Breadcrumbs"], "steps": ["Roast eggplant slices. Layer with sauce and cheese. Bake."], "tip": "Salt eggplant first to reduce bitterness.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["mediterranean", "plant-forward"]},
  {"id": "chicken-thigh-skillet", "title": "Chicken Thigh Skillet", "time": 30, "tag": "Juicy", "category": "Dinner", "servings": "2 servings", "blurb": "Bone-in or boneless thighs with pan sauce.", "ingredients": ["4 chicken thighs", "Garlic, lemon", "Oil", "Optional olives or capers"], "steps": ["Sear thighs skin-side down. Finish in oven or covered pan."], "tip": "Thighs forgive slight overcooking.", "macros": {"protein": 35, "carbs": 25, "fat": 18, "calories": 402}, "diet": ["high-protein", "mediterranean"]},
  {"id": "black-bean-tacos", "title": "Black Bean Tacos", "time": 20, "tag": "Plant-based", "category": "Dinner", "servings": "3 tacos", "blurb": "Weeknight tacos from the pantry.", "ingredients": ["Black beans", "Tortillas", "Salsa, cabbage", "Avocado"], "steps": ["Warm beans with spices. Assemble tacos."], "tip": "Mash some beans for better texture.", "macros": {"protein": 20, "carbs": 40, "fat": 18, "calories": 402}, "diet": ["plant-forward"]},
  {"id": "lamb-chops-herbs", "title": "Herb Lamb Chops", "time": 25, "tag": "Iron", "category": "Dinner", "servings": "2 servings", "blurb": "Quick-cook chops with rosemary and garlic.", "ingredients": ["4 lamb chops", "Rosemary, garlic", "Oil, salt, pepper"], "steps": ["Season. Sear 3-4 min per side for medium. Rest."], "tip": "Serve with a simple salad.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}},
  {"id": "baked-ziti-light", "title": "Lighter Baked Ziti", "time": 45, "tag": "Comfort", "category": "Dinner", "servings": "6 servings", "blurb": "Pasta bake with more vegetable, less heaviness.", "ingredients": ["12 oz ziti", "Tomato sauce", "Ricotta", "Mozzarella", "Spinach"], "steps": ["Mix pasta with sauce, ricotta, spinach. Bake 375F 25 min."], "tip": "Whole-wheat pasta holds up well.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["mediterranean"]},
];
