import type { Recipe } from "./types";

export const DINNER_PART_0: Recipe[] = [
  {"id": "livv-chicken-rice-bowl", "title": "LIVV Chicken Rice Bowl", "time": 30, "tag": "High protein", "category": "Dinner", "servings": "1 bowl", "blurb": "Clean protein, rice, and greens - the weekday default.", "ingredients": ["8 oz chicken breast", "1 cup cooked rice", "1 cup broccoli", "1 tsp oil", "Garlic, salt, pepper"], "steps": ["Season and cook chicken to 165F. Steam broccoli. Build bowl."], "tip": "Cook two portions at once.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein"]},
  {"id": "salmon-green-bowl", "title": "Salmon Green Bowl", "time": 25, "tag": "Omega-3", "category": "Dinner", "servings": "1 bowl", "blurb": "Salmon, greens, lemon - recovery food.", "ingredients": ["6 oz salmon", "Rice or quinoa", "Spinach", "Cucumber", "Lemon, oil"], "steps": ["Cook salmon to 145F. Build bowl. Finish with lemon."], "tip": "Keep components separate for meal prep.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein", "mediterranean"]},
  {"id": "steak-vegetables", "title": "Steak with Roasted Vegetables", "time": 30, "tag": "Iron", "category": "Dinner", "servings": "1 plate", "blurb": "Simple steak dinner done right.", "ingredients": ["6 oz steak", "Mixed vegetables", "Oil, salt, pepper", "Optional herb butter"], "steps": ["Roast vegetables 425F. Sear steak. Rest and slice."], "tip": "Rest steak 5 minutes.", "macros": {"protein": 42, "carbs": 25, "fat": 18, "calories": 430}, "diet": ["high-protein"]},
  {"id": "baked-cod-potatoes", "title": "Baked Cod & Potatoes", "time": 35, "tag": "Lean protein", "category": "Dinner", "servings": "2 servings", "blurb": "Mild fish with crispy potatoes.", "ingredients": ["2 cod fillets", "Potatoes", "Lemon, garlic, oil", "Herbs"], "steps": ["Roast potatoes first. Add cod last 12-15 min."], "tip": "Don't overcook cod - it flakes when done.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "mediterranean"]},
  {"id": "turkey-meatloaf", "title": "Turkey Meatloaf", "time": 50, "tag": "Meal prep", "category": "Dinner", "servings": "4 servings", "blurb": "Lighter meatloaf that slices clean for leftovers.", "ingredients": ["1.5 lb ground turkey", "Oats or breadcrumbs", "Egg, onion, ketchup", "Seasonings"], "steps": ["Mix. Shape. Bake 375F ~45 min to 165F."], "tip": "Great cold in sandwiches.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein", "meal-prep"]},
  {"id": "chicken-stir-fry", "title": "Chicken Stir-Fry", "time": 20, "tag": "Fast dinner", "category": "Dinner", "servings": "2 servings", "blurb": "Hot pan, lots of vegetables, short cook.", "ingredients": ["8 oz chicken", "3 cups vegetables", "Soy, garlic, ginger", "Rice"], "steps": ["Sear chicken. Stir-fry vegetables. Sauce and serve over rice."], "tip": "Prep everything before heat.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein"]},
  {"id": "veggie-chili", "title": "Vegetable Chili", "time": 40, "tag": "Plant-based", "category": "Dinner", "servings": "4 servings", "blurb": "Bean-heavy chili without the meat.", "ingredients": ["2 cans beans", "Tomatoes", "Peppers, onion", "Chili spices"], "steps": ["Saute aromatics. Add the rest. Simmer 25 min."], "tip": "Top with yogurt and cilantro.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["mediterranean", "plant-forward"]},
  {"id": "shrimp-garlic-pasta", "title": "Garlic Shrimp Pasta", "time": 20, "tag": "Seafood", "category": "Dinner", "servings": "2 servings", "blurb": "Fast pasta with garlicky shrimp.", "ingredients": ["8 oz shrimp", "6 oz pasta", "Garlic, chili, lemon", "Parsley, oil"], "steps": ["Cook pasta. Saute shrimp with garlic. Toss together."], "tip": "Save pasta water for the sauce.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "mediterranean"]},
  {"id": "roast-chicken-tray", "title": "Sheet-Pan Roast Chicken", "time": 45, "tag": "Classic", "category": "Dinner", "servings": "4 servings", "blurb": "One pan, minimal cleanup.", "ingredients": ["4 chicken thighs", "Potatoes, carrots", "Oil, herbs, salt"], "steps": ["Toss everything. Roast 425F 35-40 min."], "tip": "Use bone-in thighs for juicier meat.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein"]},
  {"id": "beef-and-broccoli", "title": "Beef and Broccoli", "time": 20, "tag": "High protein", "category": "Dinner", "servings": "2 servings", "blurb": "Takeout classic, cleaner version.", "ingredients": ["8 oz beef", "Broccoli", "Soy, garlic, ginger", "Cornstarch optional"], "steps": ["Sear beef. Steam broccoli. Combine with sauce."], "tip": "Slice beef thin against the grain.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein"]},
];
