import type { Recipe } from "./types";

export const DINNER_PART_3: Recipe[] = [
  {"id": "roast-pork-loin", "title": "Roast Pork Loin", "time": 55, "tag": "Lean protein", "category": "Dinner", "servings": "6 servings", "blurb": "Sunday roast that feeds the week.", "ingredients": ["2 lb pork loin", "Garlic, herbs", "Vegetables"], "steps": ["Season. Roast 375F to 145F. Rest 10 min."], "tip": "Slice thin for leftovers.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "meal-prep"]},
  {"id": "sesame-crusted-tuna", "title": "Sesame Tuna", "time": 15, "tag": "Omega-3", "category": "Dinner", "servings": "2 servings", "blurb": "Seared rare tuna with sesame crust.", "ingredients": ["2 tuna steaks", "Sesame seeds", "Soy, oil"], "steps": ["Press sesame on tuna. Sear 1-2 min per side."], "tip": "Serve with greens and rice.", "macros": {"protein": 42, "carbs": 25, "fat": 18, "calories": 430}, "diet": ["high-protein", "quick"]},
  {"id": "vegetable-paella", "title": "Vegetable Paella", "time": 45, "tag": "Spanish-inspired", "category": "Dinner", "servings": "4 servings", "blurb": "Saffron rice with vegetables.", "ingredients": ["1.5 cups rice", "Saffron or turmeric", "Mixed vegetables", "Broth"], "steps": ["Toast rice. Add broth and vegetables. Don't stir once simmering."], "tip": "Socarrat (crust) is a feature.", "macros": {"protein": 20, "carbs": 40, "fat": 12, "calories": 348}, "diet": ["plant-forward"]},
  {"id": "honey-garlic-chicken", "title": "Honey Garlic Chicken", "time": 30, "tag": "Sweet-savory", "category": "Dinner", "servings": "3 servings", "blurb": "Sticky glaze, simple sides.", "ingredients": ["1 lb chicken", "Honey, garlic, soy", "Rice", "Vegetables"], "steps": ["Cook chicken. Add glaze and reduce. Serve."], "tip": "Watch the glaze so it doesn't burn.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein"]},
  {"id": "baked-meatballs-sauce", "title": "Baked Meatballs in Sauce", "time": 40, "tag": "High protein", "category": "Dinner", "servings": "4 servings", "blurb": "Oven meatballs, less mess.", "ingredients": ["1 lb ground beef or turkey", "Egg, crumbs, garlic", "Tomato sauce"], "steps": ["Form meatballs. Bake 400F 15 min. Simmer in sauce."], "tip": "Serve with pasta or zucchini noodles.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein", "mediterranean"]},
  {"id": "lemon-herb-trout", "title": "Lemon Herb Trout", "time": 20, "tag": "Omega-3", "category": "Dinner", "servings": "2 servings", "blurb": "Delicate trout with bright herbs.", "ingredients": ["2 trout fillets", "Lemon, dill, parsley", "Oil"], "steps": ["Bake 400F 10-12 min with lemon and herbs."], "tip": "Trout cooks fast - watch it.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein", "mediterranean"]},
  {"id": "stuffed-squash", "title": "Stuffed Acorn Squash", "time": 50, "tag": "Seasonal", "category": "Dinner", "servings": "2 servings", "blurb": "Sweet squash with savory filling.", "ingredients": ["1 acorn squash", "Quinoa or sausage", "Cranberries or apple", "Nuts"], "steps": ["Roast squash halves. Fill and warm through."], "tip": "Microwave squash to soften before roasting.", "macros": {"protein": 20, "carbs": 40, "fat": 12, "calories": 348}},
  {"id": "chicken-cacciatore", "title": "Chicken Cacciatore", "time": 45, "tag": "Italian", "category": "Dinner", "servings": "4 servings", "blurb": "Braised chicken in tomato and peppers.", "ingredients": ["4 chicken pieces", "Peppers, onion", "Tomato", "Herbs"], "steps": ["Brown chicken. Simmer with vegetables and tomato 30 min."], "tip": "Bone-in stays juicier.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "mediterranean"]},
  {"id": "tempeh-stir-fry", "title": "Tempeh Stir-Fry", "time": 20, "tag": "Plant protein", "category": "Dinner", "servings": "2 servings", "blurb": "Crispy tempeh with vegetables.", "ingredients": ["8 oz tempeh", "Vegetables", "Soy, garlic, maple"], "steps": ["Cube and brown tempeh. Stir-fry vegetables. Combine."], "tip": "Steam tempeh first if bitter.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "plant-forward"]},
  {"id": "garlic-butter-shrimp", "title": "Garlic Butter Shrimp", "time": 15, "tag": "Fast dinner", "category": "Dinner", "servings": "2 servings", "blurb": "Restaurant flavors in one pan.", "ingredients": ["1 lb shrimp", "Butter or oil", "Garlic, lemon", "Parsley"], "steps": ["Saute garlic. Cook shrimp 2-3 min. Finish with lemon."], "tip": "Serve over rice or with bread.", "macros": {"protein": 35, "carbs": 25, "fat": 18, "calories": 402}, "diet": ["high-protein", "mediterranean", "quick"]},
];
