import type { Recipe } from "./types";

export const DINNER_PART_4: Recipe[] = [
  {"id": "roast-duck-simple", "title": "Simple Roast Duck Breast", "time": 30, "tag": "Rich", "category": "Dinner", "servings": "2 servings", "blurb": "Crispy skin, rendered fat, special dinner.", "ingredients": ["2 duck breasts", "Salt, pepper", "Optional cherry sauce"], "steps": ["Score skin. Start cold pan skin-side down. Finish medium-rare."], "tip": "Pour off rendered fat as you go.", "macros": {"protein": 35, "carbs": 25, "fat": 18, "calories": 402}, "diet": ["high-protein"]},
  {"id": "cauliflower-tikka", "title": "Cauliflower Tikka Masala", "time": 35, "tag": "Plant-based", "category": "Dinner", "servings": "3 servings", "blurb": "Cauliflower in creamy spiced sauce.", "ingredients": ["1 head cauliflower", "Tikka sauce or spices + tomato + yogurt", "Rice"], "steps": ["Roast cauliflower. Simmer in sauce. Serve over rice."], "tip": "Roast until edges char.", "macros": {"protein": 20, "carbs": 40, "fat": 12, "calories": 348}, "diet": ["plant-forward"]},
  {"id": "grilled-ribeye", "title": "Grilled Ribeye", "time": 20, "tag": "Occasion", "category": "Dinner", "servings": "2 servings", "blurb": "Do less - good steak needs restraint.", "ingredients": ["1 ribeye", "Salt, pepper", "Optional butter"], "steps": ["Salt ahead. Grill high heat. Rest 5-10 min."], "tip": "Don't sauce a great steak.", "macros": {"protein": 42, "carbs": 25, "fat": 18, "calories": 430}, "diet": ["high-protein"]},
  {"id": "sausage-white-beans", "title": "Sausage & White Beans", "time": 25, "tag": "Hearty", "category": "Dinner", "servings": "3 servings", "blurb": "One-pan rustic dinner.", "ingredients": ["4 sausages", "2 cans white beans", "Garlic, rosemary", "Greens"], "steps": ["Brown sausages. Add beans and aromatics. Simmer. Wilt greens."], "tip": "Chicken sausage keeps it lighter.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "plant-forward"]},
  {"id": "baked-falafel-dinner", "title": "Baked Falafel Dinner", "time": 35, "tag": "Plant protein", "category": "Dinner", "servings": "3 servings", "blurb": "Falafel with salad and tahini.", "ingredients": ["Falafel mix or homemade", "Salad", "Tahini", "Pita"], "steps": ["Bake falafel. Serve with salad and sauce."], "tip": "Homemade: chickpeas, herbs, garlic, cumin.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "mediterranean", "plant-forward"]},
  {"id": "chicken-mole-simple", "title": "Simple Chicken Mole", "time": 40, "tag": "Deep flavor", "category": "Dinner", "servings": "4 servings", "blurb": "Shortcut mole with depth.", "ingredients": ["1.5 lb chicken", "Mole paste or cocoa+chili+spices", "Broth", "Rice"], "steps": ["Simmer chicken in sauce until tender."], "tip": "Jarred mole paste is acceptable.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein"]},
  {"id": "seared-scallops", "title": "Seared Scallops", "time": 15, "tag": "Special", "category": "Dinner", "servings": "2 servings", "blurb": "Hard sear, soft center.", "ingredients": ["8-10 sea scallops", "Oil, butter", "Lemon"], "steps": ["Dry scallops well. Sear hard 2 min per side."], "tip": "Moisture is the enemy of crust.", "macros": {"protein": 20, "carbs": 25, "fat": 18, "calories": 342}, "diet": ["mediterranean", "quick"]},
  {"id": "vegetable-lasagna", "title": "Vegetable Lasagna", "time": 55, "tag": "Vegetarian", "category": "Dinner", "servings": "8 servings", "blurb": "Layered pasta with roasted vegetables.", "ingredients": ["Lasagna noodles", "Roasted vegetables", "Ricotta", "Tomato sauce", "Mozzarella"], "steps": ["Layer and bake 375F 40 min. Rest."], "tip": "Roast vegetables first for flavor.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["mediterranean"]},
  {"id": "korean-beef-bowl", "title": "Korean-Inspired Beef Bowl", "time": 20, "tag": "High protein", "category": "Dinner", "servings": "2 servings", "blurb": "Sweet-savory beef over rice.", "ingredients": ["8 oz ground beef", "Soy, garlic, sesame, brown sugar", "Rice", "Greens"], "steps": ["Cook beef with sauce. Serve over rice with greens."], "tip": "Add a fried egg.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein"]},
  {"id": "herb-roast-salmon", "title": "Herb Roast Salmon Side", "time": 25, "tag": "Omega-3", "category": "Dinner", "servings": "4 servings", "blurb": "Whole side of salmon for the table.", "ingredients": ["1.5 lb salmon side", "Herbs, lemon", "Oil, salt"], "steps": ["Roast 275-300F until just opaque. Rest."], "tip": "Low and slow stays moist.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein", "mediterranean"]},
];
