import type { Recipe } from "./types";

export const EVERYDAY_PART_2: Recipe[] = [
  {"id": "egg-fried-rice", "title": "Egg Fried Rice", "time": 12, "tag": "Pantry", "category": "Quick", "servings": "1 bowl", "blurb": "Cold leftover rice, eggs, and soy sauce. The emergency meal that still works.", "ingredients": ["1 cup cooked cold rice", "2 eggs", "1 tsp oil", "1 tbsp soy sauce", "Optional: frozen peas, scallion"], "steps": ["Whisk the eggs with a pinch of salt.", "Heat oil in a pan over medium-high. Scramble the eggs until just set. Remove.", "Add the cold rice to the pan. Break up clumps. Cook 2 to 3 minutes until hot.", "Add soy sauce and peas if using. Stir. Return the eggs. Toss. Top with scallion."], "tip": "Only cold leftover rice works. Fresh rice turns mushy.", "diet": ["high-protein", "quick"]},
  {"id": "cottage-toast", "title": "Cottage Cheese Toast", "time": 5, "tag": "High protein", "category": "Quick", "servings": "1 plate", "blurb": "Toast topped with cottage cheese and tomato or fruit.", "ingredients": ["1 slice whole-grain bread", "1/2 cup cottage cheese", "Tomato slices or berries", "Black pepper"], "steps": ["Toast the bread.", "Spread or spoon on the cottage cheese.", "Top with tomato and pepper, or berries for a sweet version."], "tip": "Everything bagel seasoning is excellent on the savory version.", "diet": ["high-protein", "quick"]},
  {"id": "protein-shake", "title": "Simple Protein Shake", "time": 3, "tag": "Training", "category": "Quick", "servings": "1 shake", "blurb": "Protein powder and liquid. Done.", "ingredients": ["1 scoop protein powder", "1 cup milk or water", "Optional: banana, ice"], "steps": ["Add protein and liquid to a shaker or blender.", "Shake or blend until smooth. Add banana or ice if you want it thicker."], "tip": "Useful right after training when you do not want a full meal.", "diet": ["high-protein", "quick"]},
  {"id": "hummus-veg-plate", "title": "Hummus and Vegetable Plate", "time": 5, "tag": "No cook", "category": "Quick", "servings": "1 plate", "blurb": "Hummus with raw vegetables and a few crackers. Fast, clean snack-meal.", "ingredients": ["1/3 cup hummus", "Carrot sticks, cucumber, bell pepper", "Optional: whole-grain crackers, boiled egg"], "steps": ["Spoon the hummus into a small bowl or onto a plate.", "Arrange the vegetables around it.", "Add crackers or a boiled egg if you need more staying power."], "tip": "Homemade or store-bought both work. Check the label for short ingredients.", "diet": ["mediterranean", "quick", "plant-forward"]},
  {"id": "microwave-potato", "title": "Loaded Microwave Potato", "time": 10, "tag": "Fast", "category": "Quick", "servings": "1 potato", "blurb": "A full meal from one potato and what you already have.", "ingredients": ["1 medium russet or sweet potato", "1/3 cup Greek yogurt or cottage cheese", "Salt, black pepper", "Optional: beans, cheese, scallion, salsa"], "steps": ["Scrub the potato. Pierce it several times with a fork.", "Microwave on high 4 minutes. Flip. Microwave another 3 to 5 minutes until soft in the center.", "Split open. Season with salt. Load with yogurt or cottage cheese and any extras."], "tip": "Flip halfway so it cooks evenly.", "diet": ["quick", "plant-forward"]},
  {"id": "tuna-cucumber", "title": "Tuna Cucumber Boats", "time": 8, "tag": "No cook", "category": "Quick", "servings": "1 plate", "blurb": "Cucumber halves filled with seasoned tuna. Light and high protein.", "ingredients": ["1 can tuna, drained", "2 tbsp Greek yogurt", "1 cucumber", "Salt, black pepper, lemon"], "steps": ["Mix tuna with yogurt, salt, pepper, and a squeeze of lemon.", "Halve the cucumber lengthwise. Scoop out some seeds if you want more room.", "Fill with the tuna mix. Serve."], "tip": "Pat the cucumber dry so the filling does not slide off.", "diet": ["high-protein", "quick"]},
  {"id": "deli-plate", "title": "Turkey Cheese Plate", "time": 5, "tag": "High protein", "category": "Quick", "servings": "1 plate", "blurb": "Sliced turkey, cheese, vegetables, and mustard. No bread required.", "ingredients": ["3 to 4 oz sliced turkey", "1 oz cheese", "Pickles, cucumber, or carrots", "Mustard"], "steps": ["Arrange turkey, cheese, and vegetables on a plate.", "Serve with mustard for dipping."], "tip": "Skip processed cheese if you can. A real cheddar or swiss slice is better.", "diet": ["high-protein", "quick"]},
  {"id": "edamame-bowl", "title": "Salted Edamame", "time": 5, "tag": "Plant protein", "category": "Quick", "servings": "1 bowl", "blurb": "Frozen edamame, salt, done. Surprisingly filling.", "ingredients": ["1.5 cups frozen edamame (shelled or in pods)", "Sea salt"], "steps": ["Microwave or steam the edamame according to the package, usually 3 to 5 minutes.", "Drain. Toss with sea salt. Eat warm."], "tip": "Shelled edamame is easier if this is a full mini-meal.", "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "black-bean-bowl", "title": "Black Bean Bowl", "time": 15, "tag": "Plant protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Rice, black beans, salsa, and avocado. Pantry lunch that hits protein and fiber.", "ingredients": ["3/4 cup cooked rice", "1/2 can black beans, rinsed", "1/4 avocado", "2 tbsp salsa", "Optional: Greek yogurt, cilantro, lime"], "steps": ["Warm the rice and beans.", "Build the bowl with rice, beans, avocado, and salsa.", "Add yogurt, cilantro, and lime if you have them."], "tip": "Rinse canned beans to cut sodium.", "diet": ["plant-forward", "quick"]},
  {"id": "egg-salad-plate", "title": "Egg Salad Plate", "time": 15, "tag": "High protein", "category": "Lunch", "servings": "1 plate", "blurb": "Egg salad with yogurt instead of heavy mayo. Served with vegetables or toast.", "ingredients": ["3 hard-boiled eggs", "2 tbsp Greek yogurt", "1 tsp mustard", "Salt, black pepper, paprika", "Celery optional", "Toast or vegetables for serving"], "steps": ["Peel and chop the eggs.", "Mix with yogurt, mustard, salt, pepper, and celery if using.", "Serve on toast or with raw vegetables."], "tip": "Make the hard-boiled eggs ahead so this takes 5 minutes at lunch.", "diet": ["high-protein", "quick"]},
  {"id": "chicken-soup-simple", "title": "Simple Chicken Soup", "time": 40, "tag": "Comfort", "category": "Lunch", "servings": "4 servings", "blurb": "Chicken, vegetables, and broth. The basic soup everyone should know.", "ingredients": ["1 lb chicken breast or thighs", "6 cups broth", "2 carrots, sliced", "2 celery stalks, sliced", "1 onion, diced", "Salt, black pepper, dried thyme", "Optional: handful of egg noodles or rice"], "steps": ["Add broth, onion, carrot, celery, and chicken to a pot. Bring to a simmer.", "Cook 20 to 25 minutes until the chicken is cooked through.", "Remove the chicken. Shred it. Return it to the pot.", "Add noodles if using and cook until tender. Season with salt, pepper, and thyme."], "tip": "Skim any foam off the top for a cleaner broth.", "diet": ["high-protein", "meal-prep"]},
  {"id": "spinach-salad-egg", "title": "Spinach Salad with Soft Egg", "time": 12, "tag": "Light", "category": "Lunch", "servings": "1 bowl", "blurb": "Warm soft-boiled egg over spinach with olive oil and lemon.", "ingredients": ["3 cups baby spinach", "2 eggs", "1 tbsp olive oil", "Lemon juice", "Salt, black pepper", "Optional: cherry tomatoes"], "steps": ["Boil eggs 6 to 7 minutes for a soft center. Cool under cold water and peel.", "Toss spinach with olive oil, lemon, salt, and pepper.", "Top with halved eggs and tomatoes if using."], "tip": "Dress the greens lightly. You can always add more oil.", "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "oatmeal-eggs", "title": "Savory Oatmeal with Egg", "time": 12, "tag": "Sustaining", "category": "Breakfast", "servings": "1 bowl", "blurb": "Oatmeal topped with a fried egg and black pepper. Savory, not sweet.", "ingredients": ["1/2 cup rolled oats", "1 cup water or broth", "1 egg", "Salt, black pepper", "Optional: scallion, hot sauce"], "steps": ["Cook oats with water or broth and a pinch of salt until thick, about 5 minutes.", "Fry an egg in a nonstick pan to your liking.", "Spoon oats into a bowl. Top with the egg, black pepper, and scallion or hot sauce."], "tip": "Broth instead of water makes it taste like a full meal.", "diet": ["high-protein", "quick"]},
  {"id": "banana-pb-toast", "title": "Peanut Butter Banana Toast", "time": 5, "tag": "Fast fuel", "category": "Breakfast", "servings": "1 plate", "blurb": "Toast, peanut butter, banana. The classic that still works.", "ingredients": ["1 slice whole-grain bread", "1 tbsp peanut butter", "1/2 banana, sliced", "Optional: cinnamon"], "steps": ["Toast the bread.", "Spread peanut butter. Top with banana slices and cinnamon."], "tip": "Use natural peanut butter with peanuts and salt only.", "diet": ["quick"]},
];
