import type { Recipe } from "./types";

export const EVERYDAY_PART_0: Recipe[] = [
  {"id": "scramble-eggs-spinach", "title": "Scrambled Eggs with Spinach", "time": 12, "tag": "High protein", "category": "Breakfast", "servings": "1 plate", "blurb": "Soft scrambled eggs with wilted spinach. A weekday default that actually fills you up.", "ingredients": ["3 eggs", "1 large handful fresh spinach", "1 tsp olive oil or butter", "Salt and black pepper", "Optional: 1 tbsp grated cheese"], "steps": ["Crack the eggs into a bowl. Add a pinch of salt and a splash of water. Whisk until the yolks and whites are fully mixed.", "Set a nonstick pan over medium-low heat. Add the oil or butter and let it warm for 20 seconds.", "Add the spinach and cook 30 to 60 seconds until just wilted. Push it to the side of the pan.", "Pour in the eggs. Let them sit for 10 seconds, then stir slowly with a spatula, folding from the edges toward the center.", "Pull the pan off the heat while the eggs still look slightly wet. They will finish cooking on the plate.", "Season with black pepper. Add cheese if you want it. Serve right away."], "tip": "Low heat keeps the eggs soft. High heat makes them rubbery.", "diet": ["high-protein", "quick"]},
  {"id": "oatmeal-banana-pb", "title": "Peanut Butter Banana Oatmeal", "time": 10, "tag": "Sustaining", "category": "Breakfast", "servings": "1 bowl", "blurb": "Warm oats with banana and peanut butter. Simple fuel that lasts until lunch.", "ingredients": ["1/2 cup rolled oats", "1 cup water or milk", "1 small banana", "1 tbsp peanut butter", "Pinch of salt", "Optional: cinnamon"], "steps": ["Add the oats, liquid, and salt to a small pot. Bring to a gentle simmer over medium heat.", "Cook 4 to 6 minutes, stirring often, until the oats are thick and creamy.", "Slice half the banana into the pot and stir for 30 seconds so it softens.", "Spoon into a bowl. Top with peanut butter, the rest of the banana, and cinnamon if you use it."], "tip": "A pinch of salt makes the peanut butter taste fuller.", "diet": ["quick"]},
  {"id": "greek-yogurt-berries", "title": "Greek Yogurt with Berries", "time": 5, "tag": "High protein", "category": "Breakfast", "servings": "1 bowl", "blurb": "Thick yogurt, fruit, and a little crunch. No cooking required.", "ingredients": ["1 cup plain Greek yogurt", "1/2 cup mixed berries", "1 tsp honey", "2 tbsp chopped nuts or granola"], "steps": ["Spoon the yogurt into a bowl.", "Top with berries, honey, and nuts or granola.", "Eat cold."], "tip": "Full-fat Greek yogurt keeps you fuller than nonfat.", "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "avocado-toast-egg", "title": "Avocado Toast with Egg", "time": 12, "tag": "Balanced", "category": "Breakfast", "servings": "1 plate", "blurb": "Toast, mashed avocado, and a cooked egg. Fast and complete.", "ingredients": ["1 slice whole-grain bread", "1/2 ripe avocado", "1 or 2 eggs", "Salt, black pepper, chili flakes", "Optional: lemon juice"], "steps": ["Toast the bread until crisp.", "Mash the avocado with a pinch of salt and a squeeze of lemon if you have it.", "Cook the eggs your way: fried in a lightly oiled pan, or boiled for 6 to 7 minutes for a soft center.", "Spread the avocado on the toast. Top with the egg. Finish with pepper and chili flakes."], "tip": "Add smoked salmon if you want more protein.", "diet": ["quick"]},
  {"id": "egg-muffin-cups", "title": "Baked Egg Muffin Cups", "time": 30, "tag": "Meal prep", "category": "Breakfast", "servings": "6 muffins", "blurb": "Bake once, reheat all week. Eggs, vegetables, and seasoning in muffin form.", "ingredients": ["6 eggs", "1 cup chopped vegetables (bell pepper, spinach, onion)", "1/4 cup grated cheese optional", "Salt and black pepper", "Oil or spray for the tin"], "steps": ["Heat the oven to 375 F. Lightly oil a 6-cup muffin tin.", "Whisk the eggs in a bowl with salt and pepper.", "Divide the chopped vegetables among the cups. Pour the eggs over the top. Add cheese if using.", "Bake 18 to 22 minutes until the centers are set.", "Cool 5 minutes, then loosen with a knife. Store in the fridge up to 4 days. Reheat 30 to 45 seconds in the microwave."], "tip": "Do not overfill the cups or they will spill.", "diet": ["high-protein", "meal-prep"]},
  {"id": "cottage-cheese-bowl", "title": "Cottage Cheese Berry Bowl", "time": 5, "tag": "High protein", "category": "Breakfast", "servings": "1 bowl", "blurb": "High protein, almost no work. Cottage cheese with fruit and nuts.", "ingredients": ["1 cup cottage cheese", "1/2 cup berries", "1 tsp honey", "2 tbsp chopped nuts"], "steps": ["Spoon the cottage cheese into a bowl.", "Top with berries, honey, and nuts.", "Eat cold."], "tip": "If the texture bothers you, blend the cottage cheese smooth first.", "diet": ["high-protein", "quick"]},
  {"id": "overnight-oats", "title": "Overnight Oats", "time": 5, "tag": "Prep ahead", "category": "Breakfast", "servings": "1 jar", "blurb": "Mix at night, eat in the morning. No stove required.", "ingredients": ["1/2 cup rolled oats", "1/2 cup milk", "1/3 cup Greek yogurt", "1 tsp chia seeds", "1/2 banana or 1/2 cup berries", "Pinch of cinnamon"], "steps": ["Add oats, milk, yogurt, chia, and cinnamon to a jar. Stir well.", "Seal and refrigerate at least 4 hours, or overnight.", "In the morning, stir again. Top with banana or berries."], "tip": "Prep three jars on Sunday and you are set for the work week.", "diet": ["meal-prep", "quick"]},
  {"id": "veggie-omelette", "title": "Vegetable Omelette", "time": 15, "tag": "High protein", "category": "Breakfast", "servings": "1 plate", "blurb": "A folded omelette filled with vegetables. Clean protein for mornings or nights.", "ingredients": ["3 eggs", "1/2 cup chopped vegetables", "1 tsp oil", "Salt and black pepper", "Optional: 2 tbsp cheese"], "steps": ["Whisk the eggs with salt and pepper.", "Warm the oil in a nonstick pan over medium heat. Cook the vegetables 2 to 3 minutes until soft.", "Pour in the eggs. Let them set around the edges, then lift the edges with a spatula so uncooked egg runs underneath.", "When the top is mostly set, add cheese if using. Fold in half and slide onto a plate."], "tip": "Cook vegetables first so the eggs do not overcook waiting on them.", "diet": ["high-protein", "quick"]},
];
