import type { Recipe } from "./types";

export const EVERYDAY_PART_3: Recipe[] = [
  {"id": "apple-almond-butter", "title": "Apple with Almond Butter", "time": 3, "tag": "Balanced", "category": "Snacks", "servings": "1 serving", "blurb": "Crunch, fiber, and a little fat. The standard afternoon snack.", "ingredients": ["1 apple", "1 tbsp almond butter"], "steps": ["Slice the apple.", "Dip in almond butter or spread it on the slices."], "tip": "Natural almond butter with one ingredient is ideal.", "diet": ["quick"]},
  {"id": "hard-boiled-eggs", "title": "Hard-Boiled Eggs", "time": 15, "tag": "Protein", "category": "Snacks", "servings": "2 eggs", "blurb": "Make a batch on Sunday. Snack protein all week.", "ingredients": ["Eggs", "Salt"], "steps": ["Place eggs in a pot. Cover with cold water by 1 inch.", "Bring to a boil. Turn off the heat, cover, and sit 10 to 11 minutes.", "Transfer to ice water for 5 minutes. Peel when ready to eat. Season with salt."], "tip": "Slightly older eggs peel easier than very fresh ones.", "diet": ["high-protein", "meal-prep", "quick"]},
  {"id": "greek-yogurt-honey", "title": "Greek Yogurt with Honey", "time": 3, "tag": "High protein", "category": "Snacks", "servings": "1 cup", "blurb": "Plain yogurt sweetened lightly. Beats most flavored cups.", "ingredients": ["3/4 cup plain Greek yogurt", "1 tsp honey"], "steps": ["Stir honey into the yogurt.", "Eat cold."], "tip": "Add cinnamon if you want more flavor without more sugar.", "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "carrot-hummus", "title": "Carrots and Hummus", "time": 3, "tag": "Fiber", "category": "Snacks", "servings": "1 serving", "blurb": "Crunchy vegetables with plant protein dip.", "ingredients": ["1 cup carrot sticks", "1/4 cup hummus"], "steps": ["Serve carrots with hummus for dipping."], "tip": "Add cucumber and bell pepper for more volume.", "diet": ["mediterranean", "quick", "plant-forward"]},
  {"id": "handful-almonds", "title": "Handful of Almonds", "time": 1, "tag": "Healthy fat", "category": "Snacks", "servings": "1 oz", "blurb": "Portion it. Do not eat from the bag.", "ingredients": ["1 oz almonds (about 23 nuts)"], "steps": ["Measure 1 ounce. Eat slowly."], "tip": "Pre-portion into small bags so you do not overeat.", "diet": ["quick"]},
  {"id": "celery-pb", "title": "Celery and Peanut Butter", "time": 3, "tag": "Classic", "category": "Snacks", "servings": "1 serving", "blurb": "Crunch and protein. Old-school for a reason.", "ingredients": ["Celery sticks", "1 to 2 tbsp peanut butter"], "steps": ["Fill the celery grooves with peanut butter.", "Eat."], "tip": "A few raisins on top makes ants on a log if you want it.", "diet": ["quick"]},
  {"id": "cottage-pineapple", "title": "Cottage Cheese and Pineapple", "time": 3, "tag": "High protein", "category": "Snacks", "servings": "1 bowl", "blurb": "Sweet and savory protein bowl.", "ingredients": ["3/4 cup cottage cheese", "1/2 cup pineapple chunks"], "steps": ["Combine in a bowl. Eat cold."], "tip": "Use pineapple canned in juice, not heavy syrup.", "diet": ["high-protein", "quick"]},
  {"id": "berry-cup", "title": "Fresh Berries", "time": 2, "tag": "Antioxidants", "category": "Snacks", "servings": "1 cup", "blurb": "Sweet without the crash.", "ingredients": ["1 cup fresh or thawed berries"], "steps": ["Wash if fresh. Eat."], "tip": "Frozen berries work fine thawed in the fridge.", "diet": ["quick"]},
  {"id": "cucumber-yogurt", "title": "Cucumber Yogurt Bowl", "time": 5, "tag": "Cooling", "category": "Snacks", "servings": "1 bowl", "blurb": "Savory yogurt with cucumber and salt. Like a simplified tzatziki.", "ingredients": ["3/4 cup Greek yogurt", "1/2 cucumber, diced", "Salt, black pepper", "Optional: dill, olive oil, garlic powder"], "steps": ["Mix yogurt with cucumber, salt, and pepper.", "Add dill, a drizzle of oil, or garlic powder if you have them.", "Eat cold."], "tip": "Salt the cucumber first and blot if you want less water in the bowl.", "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "roasted-chickpeas-snack", "title": "Roasted Chickpeas", "time": 35, "tag": "Crunchy", "category": "Snacks", "servings": "2 servings", "blurb": "Crispy seasoned chickpeas. Better than chips when you get them dry enough.", "ingredients": ["1 can chickpeas, drained and rinsed", "1 tbsp oil", "Salt, paprika, garlic powder"], "steps": ["Heat the oven to 400 F.", "Dry the chickpeas very well with a towel. Remove loose skins.", "Toss with oil and spices. Spread on a sheet pan.", "Roast 25 to 30 minutes, shaking once, until crisp. Cool before storing."], "tip": "Dryness is everything. Wet chickpeas never get crisp.", "diet": ["plant-forward", "mediterranean"]},
  {"id": "dark-chocolate", "title": "Dark Chocolate Square", "time": 1, "tag": "Simple", "category": "Dessert", "servings": "1 to 2 squares", "blurb": "Satisfy the craving without a spiral. Keep it small.", "ingredients": ["1 to 2 squares dark chocolate (70% cacao or higher)"], "steps": ["Eat slowly. Let it melt."], "tip": "Buy bars, not bags of chips. Easier to portion.", "diet": ["quick"]},
  {"id": "baked-apple", "title": "Baked Cinnamon Apple", "time": 30, "tag": "Warm", "category": "Dessert", "servings": "1 apple", "blurb": "Soft cinnamon apple. Comforting and simple.", "ingredients": ["1 apple", "1/2 tsp cinnamon", "1 tsp butter or coconut oil", "Optional: raisins, yogurt to serve"], "steps": ["Heat the oven to 350 F.", "Core the apple. Place in a small baking dish. Fill the center with cinnamon, butter, and raisins if using.", "Add a splash of water to the dish. Bake 25 to 30 minutes until soft.", "Serve warm, with yogurt if you want."], "tip": "Honeycrisp and Granny Smith both hold up well in the oven.", "diet": []},
  {"id": "yogurt-parfait-dessert", "title": "Berry Yogurt Parfait", "time": 5, "tag": "High protein", "category": "Dessert", "servings": "1 cup", "blurb": "Dessert structure with breakfast macros.", "ingredients": ["3/4 cup Greek yogurt", "1/2 cup berries", "1 tsp honey", "1 tbsp granola"], "steps": ["Layer yogurt, berries, and honey in a glass or bowl.", "Top with a light sprinkle of granola."], "tip": "Keep the granola light so it stays a topping, not a sugar bomb.", "diet": ["high-protein", "quick"]},
  {"id": "frozen-banana", "title": "Blended Frozen Banana", "time": 5, "tag": "Dairy-free", "category": "Dessert", "servings": "1 bowl", "blurb": "Frozen banana blended until it looks like soft serve.", "ingredients": ["1 to 2 frozen bananas, sliced", "Splash of milk if needed", "Optional: cocoa powder or peanut butter"], "steps": ["Add frozen banana to a blender or food processor.", "Blend, scraping down the sides, until creamy. Add a splash of milk only if it will not move.", "Stir in cocoa or peanut butter if using. Eat right away."], "tip": "Freeze ripe bananas in chunks so they blend easier.", "diet": ["quick"]},
  {"id": "cinnamon-apple-slices", "title": "Cinnamon Apple Slices", "time": 3, "tag": "Simple", "category": "Dessert", "servings": "1 apple", "blurb": "Raw apple that feels like dessert.", "ingredients": ["1 apple", "Cinnamon"], "steps": ["Slice the apple. Dust with cinnamon.", "For a warm version, microwave 45 to 60 seconds."], "tip": "No sugar needed. The cinnamon does the work.", "diet": ["quick"]},
  {"id": "strawberries-chocolate", "title": "Strawberries with Dark Chocolate", "time": 10, "tag": "Classic", "category": "Dessert", "servings": "8 strawberries", "blurb": "Fruit with a thin chocolate shell. Portioned and done.", "ingredients": ["8 strawberries", "1 oz dark chocolate"], "steps": ["Wash and fully dry the strawberries.", "Melt the chocolate in a microwave in 20-second bursts, stirring between each.", "Dip each strawberry. Set on parchment. Chill 10 minutes until set."], "tip": "Any water on the berries will seize the chocolate. Dry them well.", "diet": ["quick"]},
  {"id": "fruit-yogurt-dessert", "title": "Sliced Fruit with Yogurt", "time": 5, "tag": "Light", "category": "Dessert", "servings": "1 bowl", "blurb": "Whatever fruit is ripe, with a spoon of yogurt on the side.", "ingredients": ["1 cup sliced fruit (apple, berries, peach, or melon)", "1/3 cup Greek yogurt", "Optional: cinnamon or honey"], "steps": ["Slice the fruit into a bowl.", "Add yogurt on the side or on top.", "Dust with cinnamon or a thin drizzle of honey if needed."], "tip": "Ripe fruit needs almost no sweetener.", "diet": ["high-protein", "quick"]},
];
