import type { Recipe } from "./types";

export const LUNCH_PART_4: Recipe[] = [
  {"id": "chicken-fried-rice", "title": "Chicken Fried Rice", "time": 20, "tag": "Balanced", "category": "Lunch", "servings": "2 servings", "blurb": "Better-than-takeout fried rice.", "ingredients": ["1 cup cooked rice", "6 oz chicken", "Eggs", "Vegetables", "Soy"], "steps": ["Scramble egg. Cook chicken. Stir-fry rice and vegetables. Combine."], "tip": "Cold leftover rice is essential.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein"]},
  {"id": "tomato-mozzarella-plate", "title": "Tomato Mozzarella Plate", "time": 5, "tag": "No-cook", "category": "Lunch", "servings": "1 plate", "blurb": "Caprese as a full light lunch.", "ingredients": ["Tomato", "Fresh mozzarella", "Basil", "Olive oil, salt"], "steps": ["Slice and arrange. Dress simply."], "tip": "Add bread and prosciutto if needed.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["mediterranean", "quick"]},
  {"id": "curry-lentil-bowl", "title": "Curry Lentil Bowl", "time": 30, "tag": "Plant protein", "category": "Lunch", "servings": "2 servings", "blurb": "Spiced lentils over rice.", "ingredients": ["1 cup red lentils", "Curry spices", "Coconut milk or broth", "Rice"], "steps": ["Simmer lentils with spices and liquid 15–20 min. Serve over rice."], "tip": "Red lentils cook fastest.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "plant-forward"]},
  {"id": "grilled-cheese-tomato", "title": "Upgraded Grilled Cheese", "time": 12, "tag": "Comfort", "category": "Lunch", "servings": "1 sandwich", "blurb": "Grilled cheese with tomato and better bread.", "ingredients": ["2 slices whole-grain bread", "Cheese", "Tomato", "Butter or oil"], "steps": ["Assemble and griddle until golden."], "tip": "Add mustard for sharpness.", "macros": {"protein": 20, "carbs": 40, "fat": 18, "calories": 402}, "diet": ["quick"]},
  {"id": "sausage-pepper-plate", "title": "Chicken Sausage & Peppers", "time": 20, "tag": "High protein", "category": "Lunch", "servings": "1 plate", "blurb": "Sausage with sweet peppers and onions.", "ingredients": ["2 chicken sausages", "Peppers, onion", "Oil", "Optional mustard"], "steps": ["Slice and sauté sausages with peppers and onions."], "tip": "Choose sausages with short ingredient lists.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein"]},
  {"id": "nourish-bowl", "title": "Nourish Bowl", "time": 20, "tag": "Balanced", "category": "Lunch", "servings": "1 bowl", "blurb": "Template bowl: grain + protein + veg + sauce.", "ingredients": ["3/4 cup grain", "4 oz protein", "2 cups vegetables", "Sauce of choice"], "steps": ["Assemble warm or cold components with sauce."], "tip": "Change the protein daily to avoid boredom.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein"]},
  {"id": "clam-chowder-light", "title": "Light Clam Chowder", "time": 30, "tag": "Seafood", "category": "Lunch", "servings": "2 servings", "blurb": "Chowder without the heavy cream load.", "ingredients": ["1 can clams", "Potato, celery, onion", "Milk or half broth/milk", "Thyme"], "steps": ["Sauté aromatics. Add potato and liquid. Simmer. Add clams."], "tip": "Blend a little potato to thicken.", "macros": {"protein": 20, "carbs": 40, "fat": 12, "calories": 348}},
  {"id": "turkey-club-open", "title": "Open-Face Turkey Club", "time": 10, "tag": "Classic", "category": "Lunch", "servings": "1 plate", "blurb": "Club flavors, less bread.", "ingredients": ["4 oz turkey", "Tomato, lettuce", "1 slice bread", "Mustard or avocado", "Optional bacon"], "steps": ["Toast. Layer ingredients open-face."], "tip": "One slice of bread still satisfies.", "macros": {"protein": 42, "carbs": 40, "fat": 18, "calories": 490}, "diet": ["high-protein", "quick"]},
  {"id": "edamame-rice-bowl", "title": "Edamame Rice Bowl", "time": 12, "tag": "Plant protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Shelled edamame over rice with sesame.", "ingredients": ["1 cup edamame", "1 cup rice", "Sesame oil, soy", "Scallion"], "steps": ["Warm edamame. Season. Serve over rice."], "tip": "Frozen shelled edamame is ideal.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "chicken-shawarma-plate", "title": "Chicken Shawarma Plate", "time": 25, "tag": "Spice", "category": "Lunch", "servings": "1 plate", "blurb": "Warm spices, yogurt sauce, vegetables.", "ingredients": ["6 oz chicken", "Shawarma spices", "Yogurt sauce", "Cucumber, tomato", "Rice or pita"], "steps": ["Season and cook chicken. Serve with sauce and vegetables."], "tip": "Spice blend: cumin, paprika, coriander, garlic.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "mediterranean"]},
];
