import type { Recipe } from "./types";

export const LUNCH_PART_1: Recipe[] = [
  {"id": "caprese-chicken", "title": "Caprese Chicken", "time": 25, "tag": "Balanced", "category": "Lunch", "servings": "1 plate", "blurb": "Chicken with tomato, mozzarella, basil.", "ingredients": ["6 oz chicken", "Tomato", "Mozzarella", "Basil", "Balsamic"], "steps": ["Cook chicken. Top with tomato and mozzarella. Melt briefly. Finish with basil and balsamic."], "tip": "Pound chicken for even cooking.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "mediterranean"]},
  {"id": "miso-glazed-tofu-bowl", "title": "Miso Glazed Tofu Bowl", "time": 25, "tag": "Plant protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Caramelized miso tofu over rice and greens.", "ingredients": ["8 oz tofu", "1 tbsp miso", "1 tsp honey", "Rice", "Greens"], "steps": ["Press tofu. Bake or pan with miso-honey. Serve over rice."], "tip": "Press tofu 10 minutes.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "plant-forward"]},
  {"id": "turkey-chili", "title": "Turkey Chili", "time": 40, "tag": "Meal prep", "category": "Lunch", "servings": "4 servings", "blurb": "Lean chili that freezes well.", "ingredients": ["1 lb ground turkey", "1 can beans", "1 can tomatoes", "Chili spices", "Onion, garlic"], "steps": ["Brown turkey and onion. Add tomatoes, beans, spices. Simmer 25 min."], "tip": "Better the next day.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein", "meal-prep", "plant-forward"]},
  {"id": "greek-salad-chicken", "title": "Greek Salad with Chicken", "time": 15, "tag": "Mediterranean", "category": "Lunch", "servings": "1 bowl", "blurb": "Cucumber, tomato, olives, feta, chicken.", "ingredients": ["4 oz chicken", "Cucumber, tomato, olives", "Feta", "Olive oil, oregano", "Greens"], "steps": ["Cook or use leftover chicken. Toss salad. Top with chicken and feta."], "tip": "Leftover chicken makes this 5 minutes.", "macros": {"protein": 35, "carbs": 25, "fat": 18, "calories": 402}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "poke-style-bowl", "title": "Poke-Style Bowl", "time": 15, "tag": "Omega-3", "category": "Lunch", "servings": "1 bowl", "blurb": "Cubed fish or tofu over rice with vegetables.", "ingredients": ["4 oz sushi-grade tuna or tofu", "1 cup rice", "Cucumber, avocado", "Soy, sesame"], "steps": ["Cube protein. Season. Build bowl over rice."], "tip": "Use cooked salmon if raw fish isn't available.", "macros": {"protein": 35, "carbs": 40, "fat": 18, "calories": 462}, "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "black-bean-burrito-bowl", "title": "Black Bean Burrito Bowl", "time": 15, "tag": "Fiber", "category": "Lunch", "servings": "1 bowl", "blurb": "Burrito fillings without the wrap.", "ingredients": ["1/2 cup black beans", "1/2 cup rice", "Salsa, corn, lettuce", "Optional chicken or cheese"], "steps": ["Warm beans and rice. Assemble with toppings."], "tip": "Add Greek yogurt instead of sour cream.", "macros": {"protein": 35, "carbs": 40, "fat": 18, "calories": 462}, "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "soup-and-salad", "title": "Tomato Soup & Side Salad", "time": 15, "tag": "Simple", "category": "Lunch", "servings": "1 meal", "blurb": "Classic combo, upgraded ingredients.", "ingredients": ["2 cups tomato soup", "Side salad greens", "Olive oil, vinegar"], "steps": ["Heat soup. Toss salad. Serve together."], "tip": "Add a grilled cheese only if it fits your day.", "macros": {"protein": 20, "carbs": 25, "fat": 18, "calories": 342}, "diet": ["mediterranean", "quick"]},
  {"id": "leftover-roast-plate", "title": "Leftover Roast Plate", "time": 10, "tag": "Zero waste", "category": "Lunch", "servings": "1 plate", "blurb": "Last night's protein with fresh vegetables.", "ingredients": ["4–6 oz leftover roast meat", "Vegetables", "Mustard or sauce"], "steps": ["Reheat protein gently. Add fresh or roasted vegetables."], "tip": "Slice cold for sandwiches too.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["high-protein", "meal-prep", "quick"]},
  {"id": "soba-noodle-bowl", "title": "Soba Noodle Bowl", "time": 20, "tag": "Balanced", "category": "Lunch", "servings": "1 bowl", "blurb": "Buckwheat noodles with vegetables and protein.", "ingredients": ["2 oz soba", "Vegetables", "4 oz protein of choice", "Soy, sesame, scallion"], "steps": ["Cook soba. Assemble cold or warm with toppings."], "tip": "Rinse soba after cooking.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein"]},
  {"id": "egg-salad-lettuce", "title": "Egg Salad Lettuce Wraps", "time": 12, "tag": "Protein", "category": "Lunch", "servings": "2 wraps", "blurb": "Egg salad without the heavy bread load.", "ingredients": ["3 hard-boiled eggs", "2 tbsp yogurt", "Mustard, celery", "Lettuce leaves"], "steps": ["Mash eggs with yogurt and mustard. Serve in lettuce."], "tip": "Make eggs ahead.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "quick"]},
];
