import type { Recipe } from "./types";

export const LUNCH_PART_3: Recipe[] = [
  {"id": "blt-turkey", "title": "Turkey BLT", "time": 12, "tag": "Classic", "category": "Lunch", "servings": "1 sandwich", "blurb": "BLT structure with leaner turkey bacon.", "ingredients": ["Turkey bacon", "Lettuce, tomato", "Bread", "Yogurt-mayo or avocado"], "steps": ["Cook bacon. Assemble sandwich."], "tip": "Toast the bread.", "macros": {"protein": 42, "carbs": 40, "fat": 18, "calories": 490}, "diet": ["high-protein", "quick"]},
  {"id": "couscous-chicken", "title": "Couscous Chicken Bowl", "time": 15, "tag": "Fast grain", "category": "Lunch", "servings": "1 bowl", "blurb": "Fluffy couscous with lemon chicken.", "ingredients": ["1/2 cup couscous", "4 oz chicken", "Lemon, herbs", "Vegetables"], "steps": ["Pour hot liquid over couscous. Rest 5 min. Add chicken and vegetables."], "tip": "Couscous is mostly wait time.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "minestrone", "title": "Minestrone Soup", "time": 35, "tag": "Vegetable-forward", "category": "Lunch", "servings": "4 servings", "blurb": "Italian vegetable soup with beans and pasta.", "ingredients": ["Mixed vegetables", "1 can beans", "Broth", "Small pasta", "Tomato"], "steps": ["Sauté vegetables. Add broth, tomato, beans, pasta. Simmer."], "tip": "Freeze without pasta; add pasta when reheating.", "macros": {"protein": 20, "carbs": 40, "fat": 12, "calories": 348}, "diet": ["mediterranean", "plant-forward"]},
  {"id": "shrimp-tacos", "title": "Shrimp Tacos", "time": 15, "tag": "Lean protein", "category": "Lunch", "servings": "2 tacos", "blurb": "Fast tacos with cabbage crunch.", "ingredients": ["6 oz shrimp", "2 tortillas", "Cabbage", "Lime, yogurt sauce"], "steps": ["Sauté shrimp. Assemble tacos with slaw and sauce."], "tip": "Season shrimp with chili and cumin.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "quick"]},
  {"id": "roast-veg-hummus-plate", "title": "Roast Veg & Hummus Plate", "time": 30, "tag": "Plant-based", "category": "Lunch", "servings": "1 plate", "blurb": "Roasted vegetables with hummus and bread.", "ingredients": ["Mixed vegetables", "Hummus", "Olive oil", "Bread or crackers"], "steps": ["Roast vegetables 425°F 25 min. Serve with hummus."], "tip": "Make extra vegetables for the week.", "macros": {"protein": 20, "carbs": 40, "fat": 18, "calories": 402}, "diet": ["mediterranean", "plant-forward"]},
  {"id": "chicken-pesto-pasta", "title": "Chicken Pesto Pasta", "time": 20, "tag": "Balanced", "category": "Lunch", "servings": "2 servings", "blurb": "Pasta with pesto and chicken — portion-aware.", "ingredients": ["4 oz pasta", "6 oz chicken", "2 tbsp pesto", "Cherry tomatoes"], "steps": ["Cook pasta and chicken. Toss with pesto and tomatoes."], "tip": "Use zucchini noodles for half the pasta.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "mediterranean"]},
  {"id": "white-bean-kale-stew", "title": "White Bean & Kale Stew", "time": 30, "tag": "Fiber", "category": "Lunch", "servings": "4 servings", "blurb": "Creamy beans without cream.", "ingredients": ["2 cans white beans", "Kale", "Garlic, rosemary", "Broth"], "steps": ["Sauté garlic. Add beans, broth, kale. Simmer 15 min. Mash some beans."], "tip": "Mashing beans thickens the stew.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["plant-forward"]},
  {"id": "beef-barley-soup", "title": "Beef Barley Soup", "time": 50, "tag": "Hearty", "category": "Lunch", "servings": "4 servings", "blurb": "Slow, filling, classic.", "ingredients": ["8 oz stewing beef", "1/2 cup barley", "Vegetables", "Broth"], "steps": ["Brown beef. Add vegetables, barley, broth. Simmer 40 min."], "tip": "Worth the time; freezes well.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein"]},
  {"id": "smoked-trout-salad", "title": "Smoked Trout Salad", "time": 10, "tag": "Omega-3", "category": "Lunch", "servings": "1 bowl", "blurb": "Delicate smoked fish over greens.", "ingredients": ["3 oz smoked trout", "Greens", "Lemon, dill", "Cucumber"], "steps": ["Flake trout over dressed greens."], "tip": "Keep lemon bright and simple.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["mediterranean", "quick"]},
  {"id": "falafel-bowl", "title": "Falafel Bowl", "time": 25, "tag": "Plant protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Crispy falafel with salad and tahini.", "ingredients": ["4–6 falafel", "Greens, tomato, cucumber", "Tahini sauce", "Optional rice"], "steps": ["Warm or bake falafel. Build bowl with sauce."], "tip": "Baked falafel is lighter than deep-fried.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "mediterranean", "plant-forward"]},
];
