import type { Recipe } from "./types";

export const LUNCH_PART_2: Recipe[] = [
  {"id": "chicken-tortilla-soup", "title": "Chicken Tortilla Soup", "time": 30, "tag": "Comfort", "category": "Lunch", "servings": "4 servings", "blurb": "Brothy, spiced, satisfying.", "ingredients": ["2 cups shredded chicken", "Broth", "Tomatoes, beans, corn", "Cumin, chili", "Tortilla strips"], "steps": ["Simmer everything 15–20 min. Top with tortilla strips."], "tip": "Use rotisserie chicken.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "plant-forward"]},
  {"id": "farro-vegetable-bowl", "title": "Farro Vegetable Bowl", "time": 30, "tag": "Fiber", "category": "Lunch", "servings": "1 bowl", "blurb": "Chewy farro with roasted vegetables.", "ingredients": ["3/4 cup cooked farro", "Roasted vegetables", "Olive oil, lemon", "Optional feta or chicken"], "steps": ["Toss farro with vegetables and dressing."], "tip": "Cook farro in bulk.", "macros": {"protein": 35, "carbs": 25, "fat": 18, "calories": 402}, "diet": ["high-protein", "mediterranean"]},
  {"id": "sardine-salad", "title": "Sardine Salad", "time": 8, "tag": "Omega-3", "category": "Lunch", "servings": "1 bowl", "blurb": "Fastest nutrient-dense lunch in the pantry.", "ingredients": ["1 can sardines", "Greens", "Lemon, olive oil", "Mustard optional"], "steps": ["Flake sardines over greens. Dress simply."], "tip": "Try smoked sardines for variety.", "macros": {"protein": 35, "carbs": 25, "fat": 18, "calories": 402}, "diet": ["mediterranean", "quick"]},
  {"id": "turkey-meatball-bowl", "title": "Turkey Meatball Bowl", "time": 30, "tag": "High protein", "category": "Lunch", "servings": "2 servings", "blurb": "Lean meatballs over greens or grains.", "ingredients": ["8 oz ground turkey", "Breadcrumbs or oats", "Egg, garlic", "Sauce of choice"], "steps": ["Mix and form meatballs. Bake 400°F 15–18 min. Serve with sauce."], "tip": "Make a double batch and freeze.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein"]},
  {"id": "avocado-chickpea-toast", "title": "Avocado Chickpea Toast", "time": 10, "tag": "Plant protein", "category": "Lunch", "servings": "1 plate", "blurb": "Mashed chickpeas and avocado on toast.", "ingredients": ["1/2 avocado", "1/3 cup chickpeas", "1 slice bread", "Lemon, chili"], "steps": ["Mash together. Spread on toast."], "tip": "Add a soft egg if you want more protein.", "macros": {"protein": 35, "carbs": 40, "fat": 18, "calories": 462}, "diet": ["high-protein", "mediterranean", "quick", "plant-forward"]},
  {"id": "pho-inspired-bowl", "title": "Pho-Inspired Bowl", "time": 25, "tag": "Brothy", "category": "Lunch", "servings": "1 bowl", "blurb": "Aromatic broth with noodles and protein.", "ingredients": ["Broth with star anise/ginger", "Rice noodles", "4 oz protein", "Herbs, lime, chili"], "steps": ["Simmer broth with aromatics. Cook noodles. Assemble with herbs."], "tip": "Store-bought broth works with extra ginger.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein"]},
  {"id": "spinach-salmon-salad", "title": "Spinach Salmon Salad", "time": 12, "tag": "Omega-3", "category": "Lunch", "servings": "1 bowl", "blurb": "Warm or cold salmon on spinach.", "ingredients": ["4 oz salmon", "Spinach", "Olive oil, lemon", "Optional berries or nuts"], "steps": ["Cook or flake salmon. Toss spinach. Top."], "tip": "Canned works on busy days.", "macros": {"protein": 42, "carbs": 25, "fat": 18, "calories": 430}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "stuffed-sweet-potato", "title": "Stuffed Sweet Potato", "time": 45, "tag": "Fiber", "category": "Lunch", "servings": "1 potato", "blurb": "Baked sweet potato with savory fillings.", "ingredients": ["1 sweet potato", "Black beans or turkey", "Greek yogurt", "Salsa, greens"], "steps": ["Bake potato 400°F 40 min. Split and stuff."], "tip": "Microwave potato 8–10 min if rushed.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein", "plant-forward"]},
  {"id": "chicken-noodle-simple", "title": "Simple Chicken Noodle", "time": 25, "tag": "Comfort", "category": "Lunch", "servings": "2 servings", "blurb": "Classic soup, clean ingredients.", "ingredients": ["2 cups chicken broth", "3 oz noodles", "1 cup shredded chicken", "Carrot, celery"], "steps": ["Simmer vegetables and noodles in broth. Add chicken."], "tip": "Use leftover rotisserie.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein"]},
  {"id": "tempeh-grain-bowl", "title": "Tempeh Grain Bowl", "time": 25, "tag": "Plant protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Marinated tempeh with grains and vegetables.", "ingredients": ["4 oz tempeh", "3/4 cup grains", "Vegetables", "Soy, garlic, maple"], "steps": ["Marinate and pan-sear tempeh. Build bowl."], "tip": "Steam tempeh first to reduce bitterness.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "plant-forward"]},
];
