import type { Recipe } from "./types";

export const LUNCH_PART_0: Recipe[] = [
  {"id": "steak-egg-plate", "title": "Steak & Egg Plate", "time": 20, "tag": "Protein", "category": "Lunch", "servings": "1 plate", "blurb": "Steak, eggs, potatoes — simple fuel.", "ingredients": ["5–6 oz lean steak", "2 eggs", "1 cup diced potatoes", "1 tsp oil", "Salt and pepper"], "steps": ["Cook potatoes until browned. Sear steak. Cook eggs. Plate."], "tip": "Rest steak before slicing.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein"]},
  {"id": "chicken-caesar-light", "title": "Chicken Caesar Salad (Light)", "time": 20, "tag": "High protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Classic caesar with grilled chicken, lighter dressing.", "ingredients": ["4 oz chicken", "Romaine", "Parmesan", "Light caesar or yogurt dressing", "Croutons optional"], "steps": ["Grill chicken. Toss greens with dressing. Top with sliced chicken and parmesan."], "tip": "Make dressing with Greek yogurt.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein"]},
  {"id": "turkey-power-wrap", "title": "Turkey Power Wrap", "time": 10, "tag": "Quick", "category": "Lunch", "servings": "1 wrap", "blurb": "Ten minutes, real protein.", "ingredients": ["1 wrap", "4 oz turkey", "Spinach", "Tomato, cucumber", "2 tbsp hummus or yogurt"], "steps": ["Spread hummus. Layer fillings. Roll tight."], "tip": "Keep wet ingredients inward.", "macros": {"protein": 42, "carbs": 25, "fat": 12, "calories": 376}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "salmon-salad-bowl", "title": "Salmon Salad Bowl", "time": 15, "tag": "Omega-3", "category": "Lunch", "servings": "1 bowl", "blurb": "Flaked salmon over greens with lemon.", "ingredients": ["1 can or 4 oz cooked salmon", "Greens", "Cucumber", "Lemon, olive oil", "Optional quinoa"], "steps": ["Flake salmon. Toss greens with oil and lemon. Top with salmon."], "tip": "Canned salmon is underrated.", "macros": {"protein": 42, "carbs": 40, "fat": 18, "calories": 490}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "lentil-soup", "title": "Hearty Lentil Soup", "time": 35, "tag": "Fiber", "category": "Lunch", "servings": "4 servings", "blurb": "Protein-rich soup that reheats all week.", "ingredients": ["1 cup lentils", "1 carrot", "1 celery", "1/2 onion", "4 cups broth", "Cumin, garlic"], "steps": ["Sauté aromatics. Add lentils and broth. Simmer 25–30 min."], "tip": "Freeze portions.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["high-protein", "meal-prep", "plant-forward"]},
  {"id": "chicken-rice-bowl-lunch", "title": "Chicken Rice Bowl", "time": 30, "tag": "High protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Clean protein, rice, and greens.", "ingredients": ["8 oz chicken", "1 cup cooked rice", "1 cup broccoli", "Oil, garlic, salt"], "steps": ["Cook chicken to 165°F. Steam broccoli. Build bowl."], "tip": "Cook extra for tomorrow.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein"]},
  {"id": "tuna-white-bean", "title": "Tuna & White Bean Salad", "time": 10, "tag": "Protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Pantry protein salad, no stove needed.", "ingredients": ["1 can tuna", "1/2 cup white beans", "Olive oil, lemon", "Parsley, red onion", "Greens"], "steps": ["Mix tuna, beans, oil, lemon, onion. Serve over greens."], "tip": "Drain tuna well.", "macros": {"protein": 35, "carbs": 25, "fat": 18, "calories": 402}, "diet": ["high-protein", "mediterranean", "quick", "plant-forward"]},
  {"id": "beef-stir-fry-bowl", "title": "Beef Stir-Fry Bowl", "time": 20, "tag": "Iron", "category": "Lunch", "servings": "2 servings", "blurb": "Quick seared beef with vegetables over rice.", "ingredients": ["8 oz beef strips", "2 cups mixed vegetables", "2 tbsp soy", "Garlic, ginger", "Rice"], "steps": ["Sear beef hot. Stir-fry vegetables. Combine with sauce. Serve over rice."], "tip": "Slice beef thin against the grain.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein"]},
  {"id": "chickpea-salad-sandwich", "title": "Chickpea Salad Sandwich", "time": 10, "tag": "Plant protein", "category": "Lunch", "servings": "1 sandwich", "blurb": "Mashed chickpeas like tuna salad.", "ingredients": ["1 can chickpeas", "2 tbsp yogurt or mayo", "Celery, lemon, mustard", "Bread or lettuce wraps"], "steps": ["Mash chickpeas. Mix with the rest. Serve on bread."], "tip": "Leave some chickpeas chunky.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "mediterranean", "quick", "plant-forward"]},
  {"id": "shrimp-quinoa-bowl", "title": "Shrimp Quinoa Bowl", "time": 20, "tag": "Lean protein", "category": "Lunch", "servings": "1 bowl", "blurb": "Fast shrimp with quinoa and vegetables.", "ingredients": ["6 oz shrimp", "3/4 cup cooked quinoa", "Vegetables", "Garlic, lemon, oil"], "steps": ["Sauté shrimp with garlic 3–4 min. Assemble bowl with lemon."], "tip": "Don't overcook shrimp.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "mediterranean"]},
];
