import type { Recipe } from "./types";

export const QUICK_PART_1: Recipe[] = [
  {"id": "wrap-leftovers", "title": "Leftover Wrap", "time": 5, "tag": "Zero waste", "category": "Quick", "servings": "1 wrap", "blurb": "Last night's protein in a tortilla.", "ingredients": ["Tortilla", "Leftover protein", "Greens", "Sauce"], "steps": ["Wrap tightly. Toast optional."], "tip": "Works with almost anything.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "meal-prep", "quick"]},
  {"id": "avocado-eggs", "title": "Avocado with Soft Eggs", "time": 10, "tag": "Balanced", "category": "Quick", "servings": "1 plate", "blurb": "Halved avocado with jammy eggs.", "ingredients": ["1 avocado", "2 eggs", "Salt, chili, lemon"], "steps": ["Soft-boil eggs. Serve in or beside avocado."], "tip": "6-minute eggs.", "macros": {"protein": 35, "carbs": 25, "fat": 18, "calories": 402}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "edamame-bowl", "title": "Salted Edamame", "time": 5, "tag": "Plant protein", "category": "Quick", "servings": "1 bowl", "blurb": "Simple, filling, high protein.", "ingredients": ["1.5 cups edamame", "Sea salt", "Optional chili"], "steps": ["Steam or microwave. Salt heavily."], "tip": "Shelled is easier to eat as a meal.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "smoked-salmon-roll", "title": "Smoked Salmon Roll-Ups", "time": 5, "tag": "Omega-3", "category": "Quick", "servings": "4 rolls", "blurb": "Salmon rolled with cream cheese or cucumber.", "ingredients": ["Smoked salmon", "Cream cheese or avocado", "Cucumber"], "steps": ["Spread and roll."], "tip": "Toothpicks help hold them.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "bean-tostada", "title": "Bean Tostada", "time": 10, "tag": "Fiber", "category": "Quick", "servings": "2 tostadas", "blurb": "Crispy tortilla, refried beans, toppings.", "ingredients": ["2 tortillas", "Refried or mashed beans", "Salsa", "Cabbage"], "steps": ["Toast tortillas. Top with warm beans and salsa."], "tip": "Oven-crisp tortillas at 400F.", "macros": {"protein": 20, "carbs": 40, "fat": 12, "calories": 348}, "diet": ["quick", "plant-forward"]},
  {"id": "protein-shake", "title": "Simple Protein Shake", "time": 3, "tag": "Training", "category": "Quick", "servings": "1 shake", "blurb": "Protein and liquid. No excuses.", "ingredients": ["1 scoop protein", "1 cup milk or water", "Ice optional"], "steps": ["Shake or blend."], "tip": "Add banana if you need calories.", "macros": {"protein": 18, "carbs": 20, "fat": 8, "calories": 224}, "diet": ["high-protein", "quick"]},
  {"id": "tomato-soup-grilled", "title": "Soup & Mini Melt", "time": 12, "tag": "Comfort", "category": "Quick", "servings": "1 meal", "blurb": "Tomato soup with a small grilled cheese.", "ingredients": ["Tomato soup", "Bread", "Cheese"], "steps": ["Heat soup. Make a small grilled cheese."], "tip": "One sandwich half is often enough.", "macros": {"protein": 20, "carbs": 40, "fat": 18, "calories": 402}, "diet": ["mediterranean", "quick"]},
  {"id": "shrimp-cocktail-plate", "title": "Shrimp Plate", "time": 5, "tag": "Lean protein", "category": "Quick", "servings": "1 plate", "blurb": "Cold shrimp with lemon and vegetables.", "ingredients": ["6-8 cooked shrimp", "Lemon", "Cocktail sauce or yogurt-horseradish", "Vegetables"], "steps": ["Arrange and serve."], "tip": "Buy pre-cooked shrimp.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "nacho-plate-light", "title": "Loaded Nacho Plate", "time": 12, "tag": "Sharing", "category": "Quick", "servings": "2 servings", "blurb": "Chips, beans, cheese, salsa - portioned.", "ingredients": ["Tortilla chips", "Black beans", "Cheese", "Salsa", "Yogurt"], "steps": ["Layer chips, beans, cheese. Melt. Top with salsa and yogurt."], "tip": "Bake instead of frying more chips.", "macros": {"protein": 20, "carbs": 40, "fat": 18, "calories": 402}, "diet": ["quick", "plant-forward"]},
  {"id": "egg-drop-soup", "title": "Egg Drop Soup", "time": 8, "tag": "Light", "category": "Quick", "servings": "1 bowl", "blurb": "Silky egg ribbons in seasoned broth.", "ingredients": ["2 cups broth", "2 eggs", "Sesame, scallion", "White pepper"], "steps": ["Bring broth to simmer. Stream in beaten egg while stirring."], "tip": "Cornstarch slurry for thicker soup.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "quick"]},
];
