import type { Recipe } from "./types";

export const QUICK_PART_4: Recipe[] = [
  {"id": "ham-egg-muffin", "title": "Ham Egg Muffin", "time": 8, "tag": "Portable", "category": "Quick", "servings": "1 sandwich", "blurb": "Breakfast sandwich energy any time of day.", "ingredients": ["English muffin", "1 egg", "Ham or turkey", "Cheese optional"], "steps": ["Cook egg. Toast muffin. Assemble."], "tip": "Freeze assembled sandwiches.", "macros": {"protein": 42, "carbs": 25, "fat": 18, "calories": 430}, "diet": ["high-protein", "quick"]},
  {"id": "zucchini-noodles-pesto", "title": "Zoodles with Pesto", "time": 12, "tag": "Lower carb", "category": "Quick", "servings": "1 bowl", "blurb": "Zucchini noodles with bright pesto.", "ingredients": ["2 zucchini spiralized", "2 tbsp pesto", "Cherry tomatoes", "Optional chicken"], "steps": ["Warm zoodles briefly. Toss with pesto."], "tip": "Don't overcook or they go watery.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "soup-can-upgrade", "title": "Upgraded Canned Soup", "time": 8, "tag": "Emergency", "category": "Quick", "servings": "1 bowl", "blurb": "Canned soup with added protein and greens.", "ingredients": ["1 can soup", "Leftover chicken or beans", "Handful spinach"], "steps": ["Heat soup with additions."], "tip": "Still faster than delivery.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "meal-prep", "quick", "plant-forward"]},
  {"id": "rice-paper-rolls", "title": "Quick Rice Paper Rolls", "time": 15, "tag": "Fresh", "category": "Quick", "servings": "4 rolls", "blurb": "Fresh rolls with vegetables and protein.", "ingredients": ["Rice paper", "Vegetables", "Protein of choice", "Dipping sauce"], "steps": ["Dip paper in water. Fill and roll."], "tip": "Don't oversoak the paper.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "quick"]},
  {"id": "microwave-fish", "title": "Microwave Lemon Fish", "time": 8, "tag": "Lean protein", "category": "Quick", "servings": "1 serving", "blurb": "Fish when the stove feels like too much.", "ingredients": ["1 fish fillet", "Lemon", "Salt, herbs"], "steps": ["Cover and microwave 2-4 min until opaque."], "tip": "Check early - microwaves vary.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "sweet-potato-toast", "title": "Sweet Potato Toast", "time": 15, "tag": "Fiber", "category": "Quick", "servings": "2 slices", "blurb": "Roasted sweet potato slices as toast.", "ingredients": ["1 sweet potato", "Toppings: avocado, egg, nut butter"], "steps": ["Slice 1/4-inch. Toast or roast until tender."], "tip": "Works in a toaster when thin enough.", "macros": {"protein": 35, "carbs": 40, "fat": 18, "calories": 462}, "diet": ["high-protein", "quick"]},
  {"id": "cottage-toast", "title": "Cottage Cheese Toast", "time": 5, "tag": "High protein", "category": "Quick", "servings": "1 plate", "blurb": "High-protein toast topping.", "ingredients": ["1 slice bread", "1/2 cup cottage cheese", "Tomato or fruit", "Pepper"], "steps": ["Toast. Top. Season."], "tip": "Savory or sweet both work.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "frozen-veg-stir", "title": "Frozen Veg Stir-Fry", "time": 12, "tag": "Emergency", "category": "Quick", "servings": "1 bowl", "blurb": "Frozen vegetables rescued with eggs or tofu.", "ingredients": ["3 cups frozen vegetables", "2 eggs or tofu", "Soy, garlic", "Oil"], "steps": ["Stir-fry hot. Add protein. Season."], "tip": "Don't thaw vegetables first.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "smoothie-bowl-fast", "title": "Fast Smoothie Bowl", "time": 5, "tag": "Recovery", "category": "Quick", "servings": "1 bowl", "blurb": "Thicker smoothie with toppings.", "ingredients": ["Frozen fruit", "Yogurt or protein", "Splash of milk", "Toppings"], "steps": ["Blend thick. Top with seeds and fruit."], "tip": "Use a spoon, not a straw.", "macros": {"protein": 18, "carbs": 20, "fat": 8, "calories": 224}, "diet": ["high-protein", "quick"]},
  {"id": "deli-plate", "title": "Deli Plate Done Right", "time": 5, "tag": "High protein", "category": "Quick", "servings": "1 plate", "blurb": "Sliced meats, cheese, vegetables, mustard.", "ingredients": ["3-4 oz turkey or roast beef", "Cheese", "Pickles, vegetables", "Mustard"], "steps": ["Arrange like a board."], "tip": "Skip the processed cheese if you can.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
];
