import type { Recipe } from "./types";

export const QUICK_PART_2: Recipe[] = [
  {"id": "caprese-snack", "title": "Caprese Bites", "time": 5, "tag": "No-cook", "category": "Quick", "servings": "1 plate", "blurb": "Tomato, mozzarella, basil, oil.", "ingredients": ["Cherry tomatoes", "Mozzarella balls", "Basil", "Olive oil"], "steps": ["Skewer or plate. Drizzle oil."], "tip": "Balsamic optional.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["mediterranean", "quick"]},
  {"id": "sardine-crackers", "title": "Sardines on Crackers", "time": 5, "tag": "Omega-3", "category": "Quick", "servings": "1 plate", "blurb": "Pantry power snack-meal.", "ingredients": ["1 can sardines", "Crackers", "Mustard or lemon"], "steps": ["Top crackers with sardines."], "tip": "Spicy mustard cuts the richness.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["mediterranean", "quick"]},
  {"id": "fried-egg-toast", "title": "Fried Egg on Toast", "time": 7, "tag": "Classic", "category": "Quick", "servings": "1 plate", "blurb": "The minimum viable hot meal.", "ingredients": ["1-2 eggs", "1 slice bread", "Salt, pepper", "Hot sauce optional"], "steps": ["Fry eggs. Toast bread. Stack."], "tip": "Butter the toast.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "quick"]},
  {"id": "turkey-rollups", "title": "Turkey Cheese Roll-Ups", "time": 5, "tag": "High protein", "category": "Quick", "servings": "4 rolls", "blurb": "Deli turkey rolled with cheese.", "ingredients": ["Turkey slices", "Cheese", "Mustard", "Pickles optional"], "steps": ["Roll and eat."], "tip": "Look for low-sodium turkey.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "smoothie-green", "title": "Green Smoothie", "time": 5, "tag": "Micronutrients", "category": "Quick", "servings": "1 glass", "blurb": "Spinach, fruit, protein.", "ingredients": ["1 cup spinach", "1 banana", "1/2 cup frozen pineapple", "Protein or yogurt", "Milk"], "steps": ["Blend until smooth."], "tip": "Add ginger for brightness.", "macros": {"protein": 18, "carbs": 20, "fat": 8, "calories": 224}, "diet": ["high-protein", "quick"]},
  {"id": "rice-cake-stack", "title": "Rice Cake Stacks", "time": 5, "tag": "Light", "category": "Quick", "servings": "2 stacks", "blurb": "Crunchy base with protein toppings.", "ingredients": ["2 rice cakes", "Cottage cheese or tuna", "Tomato", "Pepper"], "steps": ["Top and eat."], "tip": "Best eaten immediately so they stay crisp.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "frozen-burrito-upgrade", "title": "Frozen Burrito Upgrade", "time": 8, "tag": "Emergency", "category": "Quick", "servings": "1 burrito", "blurb": "Frozen burrito plus fresh toppings.", "ingredients": ["1 frozen burrito", "Salsa", "Yogurt", "Lettuce"], "steps": ["Heat burrito. Add fresh toppings."], "tip": "Still better than skipping a meal.", "macros": {"protein": 20, "carbs": 25, "fat": 12, "calories": 288}, "diet": ["quick"]},
  {"id": "miso-salmon-flakes", "title": "Salmon Flake Bowl", "time": 8, "tag": "Omega-3", "category": "Quick", "servings": "1 bowl", "blurb": "Canned salmon over rice with sesame.", "ingredients": ["1 can salmon", "1 cup rice", "Sesame, soy", "Scallion"], "steps": ["Warm rice. Top with salmon and seasonings."], "tip": "Mix in a soft egg if available.", "macros": {"protein": 42, "carbs": 40, "fat": 12, "calories": 436}, "diet": ["high-protein", "quick"]},
  {"id": "apple-cheese", "title": "Apple & Cheese", "time": 3, "tag": "Balanced", "category": "Quick", "servings": "1 serving", "blurb": "Fiber plus protein and fat.", "ingredients": ["1 apple", "1-2 oz cheese"], "steps": ["Slice and pair."], "tip": "Cheddar and apple is classic.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "garlic-toast-tomato", "title": "Tomato Garlic Toast", "time": 8, "tag": "Simple", "category": "Quick", "servings": "1 plate", "blurb": "Rubbed garlic toast with tomato.", "ingredients": ["1-2 slices bread", "Garlic clove", "Tomato", "Olive oil", "Salt"], "steps": ["Toast. Rub garlic. Top with tomato and oil."], "tip": "Spanish pan con tomate style.", "macros": {"protein": 20, "carbs": 40, "fat": 18, "calories": 402}, "diet": ["mediterranean", "quick"]},
];
