import type { Recipe } from "./types";

export const QUICK_PART_3: Recipe[] = [
  {"id": "yogurt-cucumber", "title": "Cucumber Yogurt Bowl", "time": 5, "tag": "Cooling", "category": "Quick", "servings": "1 bowl", "blurb": "Savory yogurt with cucumber and herbs.", "ingredients": ["1 cup Greek yogurt", "Cucumber", "Dill or mint", "Salt, olive oil"], "steps": ["Mix and eat."], "tip": "Add chickpeas for more substance.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "microwave-eggs", "title": "Microwave Scrambled Eggs", "time": 3, "tag": "Fast protein", "category": "Quick", "servings": "1 bowl", "blurb": "Eggs when you only have a microwave.", "ingredients": ["2 eggs", "Splash of milk", "Salt"], "steps": ["Whisk in a microwave-safe bowl. Cook 45-second intervals, stirring."], "tip": "Stop while still slightly wet.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "bagged-salad-protein", "title": "Bagged Salad + Protein", "time": 5, "tag": "Emergency", "category": "Quick", "servings": "1 bowl", "blurb": "Pre-washed salad plus a can of protein.", "ingredients": ["Bagged salad", "1 can tuna or beans", "Dressing"], "steps": ["Combine."], "tip": "Keep dressing light.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "oat-mug", "title": "Mug Oats", "time": 5, "tag": "Warm", "category": "Quick", "servings": "1 mug", "blurb": "Single-serve oats in a mug.", "ingredients": ["1/2 cup oats", "1/2 cup milk", "Pinch salt", "Toppings"], "steps": ["Microwave 1-2 min. Stir. Top."], "tip": "Watch for boil-over.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "cheese-fruit-plate", "title": "Cheese & Fruit Plate", "time": 5, "tag": "Simple", "category": "Quick", "servings": "1 plate", "blurb": "Adult lunchable done properly.", "ingredients": ["2 oz cheese", "Fruit", "Nuts", "Crackers"], "steps": ["Arrange and eat."], "tip": "Balance salty and sweet.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "kimchi-eggs", "title": "Kimchi & Eggs", "time": 10, "tag": "Gut-friendly", "category": "Quick", "servings": "1 plate", "blurb": "Spicy fermented cabbage with soft eggs.", "ingredients": ["1/2 cup kimchi", "2 eggs", "Oil", "Rice optional"], "steps": ["Saute kimchi. Cook eggs. Serve together."], "tip": "Great over leftover rice.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "quick"]},
  {"id": "tortilla-pizza", "title": "Tortilla Pizza", "time": 10, "tag": "Comfort", "category": "Quick", "servings": "1 pizza", "blurb": "Thin crispy personal pizza.", "ingredients": ["1 tortilla", "Tomato sauce", "Cheese", "Toppings"], "steps": ["Assemble. Bake or skillet until cheese melts."], "tip": "Keep toppings light so it crisps.", "macros": {"protein": 20, "carbs": 40, "fat": 18, "calories": 402}, "diet": ["mediterranean", "quick"]},
  {"id": "protein-ice-cream", "title": "Blended Protein Ice Cream", "time": 5, "tag": "Sweet", "category": "Quick", "servings": "1 bowl", "blurb": "Frozen banana blended thick with protein.", "ingredients": ["1 frozen banana", "1 scoop protein", "Splash of milk"], "steps": ["Blend until soft-serve texture."], "tip": "Eat immediately.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "chickpea-snack-plate", "title": "Spiced Chickpea Plate", "time": 10, "tag": "Plant protein", "category": "Quick", "servings": "1 plate", "blurb": "Crispy chickpeas with yogurt dip.", "ingredients": ["1 can chickpeas", "Spices", "Oil", "Yogurt"], "steps": ["Roast or pan-crisp chickpeas. Serve with yogurt."], "tip": "Dry chickpeas well before crisping.", "macros": {"protein": 35, "carbs": 25, "fat": 12, "calories": 348}, "diet": ["high-protein", "mediterranean", "quick", "plant-forward"]},
  {"id": "broth-sip", "title": "Bone Broth Cup", "time": 5, "tag": "Light", "category": "Quick", "servings": "1 cup", "blurb": "Warm minerals when you don't want a full meal.", "ingredients": ["1-2 cups broth", "Salt", "Optional ginger"], "steps": ["Heat and sip."], "tip": "Add a soft egg to make it a meal.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
];
