import type { Recipe } from "./types";

export const QUICK_PART_0: Recipe[] = [
  {"id": "recovery-smoothie", "title": "Recovery Smoothie", "time": 5, "tag": "Recovery", "category": "Quick", "servings": "1 smoothie", "blurb": "Post-training fuel you can drink standing up.", "ingredients": ["1 banana", "3/4 cup Greek yogurt", "3/4 cup milk", "1 cup frozen berries", "1/4 cup oats"], "steps": ["Blend until smooth."], "tip": "Frozen fruit = thicker texture.", "macros": {"protein": 18, "carbs": 20, "fat": 8, "calories": 224}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "egg-rice", "title": "Egg Fried Rice", "time": 10, "tag": "Pantry", "category": "Quick", "servings": "1 bowl", "blurb": "Eggs, leftover rice, soy - done.", "ingredients": ["1 cup cooked rice", "2 eggs", "Soy", "Scallion", "Oil"], "steps": ["Scramble eggs. Add rice and soy. Finish with scallion."], "tip": "Cold rice only.", "macros": {"protein": 35, "carbs": 40, "fat": 12, "calories": 408}, "diet": ["high-protein", "meal-prep", "quick"]},
  {"id": "tuna-cucumber", "title": "Tuna Cucumber Boats", "time": 5, "tag": "No-cook", "category": "Quick", "servings": "1 plate", "blurb": "Cucumber as the vessel.", "ingredients": ["1 can tuna", "1 cucumber", "Yogurt or mayo", "Pepper"], "steps": ["Mix tuna with yogurt. Fill cucumber halves."], "tip": "Pat cucumber dry.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "hummus-plate", "title": "Hummus Snack Plate", "time": 5, "tag": "No-cook", "category": "Quick", "servings": "1 plate", "blurb": "Hummus with vegetables and crackers.", "ingredients": ["Hummus", "Carrots, cucumber", "Crackers or pita"], "steps": ["Arrange and eat."], "tip": "Add boiled eggs for more protein.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["mediterranean", "quick"]},
  {"id": "microwave-potato", "title": "Loaded Microwave Potato", "time": 10, "tag": "Fast", "category": "Quick", "servings": "1 potato", "blurb": "Full meal from a microwave potato.", "ingredients": ["1 potato", "Greek yogurt", "Cheese or beans", "Scallion", "Salt"], "steps": ["Microwave potato 8-10 min. Split and load."], "tip": "Flip halfway through cooking.", "macros": {"protein": 35, "carbs": 40, "fat": 18, "calories": 462}, "diet": ["high-protein", "mediterranean", "quick", "plant-forward"]},
  {"id": "greek-yogurt-parfait", "title": "Yogurt Parfait", "time": 5, "tag": "High protein", "category": "Quick", "servings": "1 cup", "blurb": "Layered yogurt, fruit, crunch.", "ingredients": ["Greek yogurt", "Fruit", "Nuts or granola"], "steps": ["Layer and eat."], "tip": "Unsweetened yogurt + fruit is enough.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "quesadilla", "title": "Cheese Quesadilla", "time": 8, "tag": "Comfort", "category": "Quick", "servings": "1 quesadilla", "blurb": "Crispy tortilla, melted cheese, optional beans.", "ingredients": ["1 tortilla", "Cheese", "Optional beans or chicken", "Salsa"], "steps": ["Fill half. Fold. Toast in dry pan both sides."], "tip": "Add spinach for volume.", "macros": {"protein": 35, "carbs": 40, "fat": 18, "calories": 462}, "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "cottage-cheese-snack", "title": "Savory Cottage Cheese", "time": 3, "tag": "High protein", "category": "Quick", "servings": "1 bowl", "blurb": "Cottage cheese with pepper and tomatoes.", "ingredients": ["1 cup cottage cheese", "Tomato", "Black pepper", "Olive oil"], "steps": ["Combine and eat."], "tip": "Everything bagel seasoning is excellent here.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "peanut-banana", "title": "Peanut Butter Banana", "time": 3, "tag": "Fast fuel", "category": "Quick", "servings": "1 serving", "blurb": "The classic emergency snack-meal.", "ingredients": ["1 banana", "1-2 tbsp peanut butter"], "steps": ["Slice and spread or dip."], "tip": "Add cinnamon.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "instant-miso", "title": "Instant Miso Bowl", "time": 5, "tag": "Light", "category": "Quick", "servings": "1 bowl", "blurb": "Miso, scallion, optional egg or tofu.", "ingredients": ["1 tbsp miso", "1.5 cups hot water", "Scallion", "Optional egg or tofu"], "steps": ["Whisk miso into hot water. Add toppings."], "tip": "Don't boil the miso.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick", "plant-forward"]},
];
