import type { Recipe } from "./types";

export const SNACKS_PART_4: Recipe[] = [
  {"id": "frozen-grapes", "title": "Frozen Grapes", "time": 5, "tag": "Sweet", "category": "Snacks", "servings": "1 cup", "blurb": "Nature's candy, cold.", "ingredients": ["1 cup grapes"], "steps": ["Freeze 2+ hours. Eat."], "tip": "Portion first.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "avocado-salt", "title": "Avocado with Salt", "time": 3, "tag": "Healthy fat", "category": "Snacks", "servings": "1/2 avocado", "blurb": "Simple and complete.", "ingredients": ["1/2 avocado", "Salt", "Lime"], "steps": ["Season and spoon."], "tip": "Chili flakes welcome.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "whole-grain-crackers-cheese", "title": "Crackers & Cheese", "time": 3, "tag": "Balanced", "category": "Snacks", "servings": "1 serving", "blurb": "Portioned carbs and protein.", "ingredients": ["5-6 whole-grain crackers", "1 oz cheese"], "steps": ["Assemble."], "tip": "Count the crackers.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "smoothie-shot", "title": "Mini Smoothie", "time": 5, "tag": "Micronutrients", "category": "Snacks", "servings": "1 small glass", "blurb": "Half smoothie as a snack.", "ingredients": ["1/2 banana", "Handful spinach", "1/2 cup milk"], "steps": ["Blend."], "tip": "Don't supersize it.", "macros": {"protein": 18, "carbs": 20, "fat": 8, "calories": 224}, "diet": ["quick"]},
  {"id": "spiced-nuts", "title": "Warm Spiced Nuts", "time": 10, "tag": "Satisfying", "category": "Snacks", "servings": "1 oz", "blurb": "Toasted nuts with spice.", "ingredients": ["1 oz mixed nuts", "Chili, cumin, salt"], "steps": ["Toast in a dry pan with spices."], "tip": "Cool before storing.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "nori-tuna", "title": "Nori Tuna Wraps", "time": 5, "tag": "Omega-3", "category": "Snacks", "servings": "2 wraps", "blurb": "Seaweed wraps with tuna.", "ingredients": ["Nori sheets", "1/2 can tuna", "Cucumber"], "steps": ["Fill and roll."], "tip": "Keep nori dry until assembling.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "chocolate-milk-protein", "title": "Chocolate Protein Milk", "time": 3, "tag": "Recovery", "category": "Snacks", "servings": "1 glass", "blurb": "Post-training classic, upgraded.", "ingredients": ["1 cup milk", "1 scoop chocolate protein"], "steps": ["Shake."], "tip": "Or cocoa + milk + protein.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["high-protein", "quick"]},
  {"id": "apple-cinnamon-chips", "title": "Baked Apple Chips", "time": 40, "tag": "Sweet crunch", "category": "Snacks", "servings": "2 servings", "blurb": "Thin apple slices baked crisp.", "ingredients": ["2 apples", "Cinnamon"], "steps": ["Slice thin. Bake 200F 1.5-2 hrs."], "tip": "Patience for crispness.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}},
  {"id": "hummus-pretzel", "title": "Hummus & Pretzels", "time": 3, "tag": "Salty", "category": "Snacks", "servings": "1 serving", "blurb": "Crunch with plant protein.", "ingredients": ["1/4 cup hummus", "Small handful pretzels"], "steps": ["Dip."], "tip": "Whole-grain pretzels if available.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick", "plant-forward"]},
  {"id": "mango-chili", "title": "Mango with Chili-Lime", "time": 5, "tag": "Fresh", "category": "Snacks", "servings": "1 serving", "blurb": "Sweet heat snack.", "ingredients": ["1 mango", "Chili powder", "Lime"], "steps": ["Cube. Season."], "tip": "Tajin works well.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
];
