import type { Recipe } from "./types";

export const SNACKS_PART_2: Recipe[] = [
  {"id": "guacamole-veg", "title": "Guacamole & Vegetables", "time": 5, "tag": "Healthy fat", "category": "Snacks", "servings": "1 serving", "blurb": "Avocado dip with crunchy vegetables.", "ingredients": ["1/2 avocado mashed", "Lime, salt", "Vegetables"], "steps": ["Mash and season. Dip."], "tip": "Eat the same day.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "smoked-salmon-cucumber", "title": "Salmon on Cucumber", "time": 5, "tag": "Omega-3", "category": "Snacks", "servings": "6 bites", "blurb": "Cucumber rounds with salmon.", "ingredients": ["Smoked salmon", "Cucumber", "Dill"], "steps": ["Top cucumber slices with salmon."], "tip": "Cream cheese optional.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "whey-water", "title": "Protein in Water", "time": 2, "tag": "Training", "category": "Snacks", "servings": "1 shake", "blurb": "Fastest protein delivery.", "ingredients": ["1 scoop whey", "Water"], "steps": ["Shake."], "tip": "Useful right after training.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "banana", "title": "Banana", "time": 1, "tag": "Potassium", "category": "Snacks", "servings": "1 banana", "blurb": "The original packaged snack.", "ingredients": ["1 banana"], "steps": ["Eat."], "tip": "Slightly green lasts longer.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "dates-almond", "title": "Dates Stuffed with Almonds", "time": 3, "tag": "Sweet fuel", "category": "Snacks", "servings": "3 dates", "blurb": "Natural sweetness with crunch.", "ingredients": ["3 dates", "3 almonds"], "steps": ["Pit and stuff."], "tip": "Medjool dates are softest.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "kale-chips", "title": "Kale Chips", "time": 25, "tag": "Crunchy", "category": "Snacks", "servings": "2 servings", "blurb": "Crispy kale, better than they sound.", "ingredients": ["Kale", "Oil", "Salt"], "steps": ["Tear, oil, bake 300F 20 min."], "tip": "Don't overcrowd the pan.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}},
  {"id": "yogurt-cocoa", "title": "Cocoa Yogurt", "time": 3, "tag": "Chocolate fix", "category": "Snacks", "servings": "1 cup", "blurb": "Chocolate flavor with protein.", "ingredients": ["3/4 cup Greek yogurt", "1 tsp cocoa", "1 tsp honey"], "steps": ["Stir until smooth."], "tip": "Unsweetened cocoa only.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "pickles", "title": "Pickles", "time": 1, "tag": "Low calorie", "category": "Snacks", "servings": "1-2 pickles", "blurb": "Salty crunch, almost no calories.", "ingredients": ["Pickles"], "steps": ["Eat."], "tip": "Fermented pickles for gut benefit.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "tuna-packet", "title": "Tuna Packet", "time": 2, "tag": "Protein", "category": "Snacks", "servings": "1 packet", "blurb": "No-drain tuna for bags and desks.", "ingredients": ["1 tuna packet", "Crackers optional"], "steps": ["Open and eat."], "tip": "Look for olive-oil packs.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "snap-peas", "title": "Snap Peas", "time": 2, "tag": "Crunchy", "category": "Snacks", "servings": "1 cup", "blurb": "Sweet raw crunch.", "ingredients": ["1 cup snap peas"], "steps": ["Eat raw."], "tip": "Great with hummus.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
];
