import type { Recipe } from "./types";

export const SNACKS_PART_3: Recipe[] = [
  {"id": "chia-drink", "title": "Chia Water", "time": 5, "tag": "Fiber", "category": "Snacks", "servings": "1 glass", "blurb": "Hydration plus fiber.", "ingredients": ["1 tbsp chia", "1 cup water", "Lemon optional"], "steps": ["Stir. Wait 10 min. Drink."], "tip": "Stir again before drinking.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "moon-cheese", "title": "Baked Cheese Crisps", "time": 15, "tag": "High protein", "category": "Snacks", "servings": "1 serving", "blurb": "Crispy cheese chips.", "ingredients": ["2 oz shredded cheese"], "steps": ["Bake small piles 400F 5-7 min."], "tip": "Cool to crisp.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "fruit-nut-butter-pack", "title": "Fruit & Nut Butter Pack", "time": 3, "tag": "Portable", "category": "Snacks", "servings": "1 serving", "blurb": "Pre-portioned nut butter with fruit.", "ingredients": ["1 apple or banana", "1 single-serve nut butter"], "steps": ["Dip."], "tip": "Single-serve packs prevent overeating.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "roasted-seaweed", "title": "Roasted Seaweed Snacks", "time": 1, "tag": "Light", "category": "Snacks", "servings": "1 pack", "blurb": "Salty, light, mineral-rich.", "ingredients": ["1 pack roasted seaweed"], "steps": ["Eat."], "tip": "Low calorie volume.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "protein-muffin", "title": "Protein Muffin", "time": 25, "tag": "Meal prep", "category": "Snacks", "servings": "6 muffins", "blurb": "Muffins with actual protein.", "ingredients": ["Protein powder", "Eggs", "Banana or pumpkin", "Oats"], "steps": ["Mix. Bake 350F 18-20 min."], "tip": "Freeze extras.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "meal-prep"]},
  {"id": "watermelon", "title": "Watermelon Cubes", "time": 5, "tag": "Hydrating", "category": "Snacks", "servings": "2 cups", "blurb": "Mostly water, still satisfying.", "ingredients": ["Watermelon"], "steps": ["Cube and chill."], "tip": "Add feta and mint for a mini salad.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["mediterranean", "quick"]},
  {"id": "bell-pepper-strips", "title": "Bell Pepper Strips", "time": 3, "tag": "Crunchy", "category": "Snacks", "servings": "1 pepper", "blurb": "Sweet crunch, high vitamin C.", "ingredients": ["1 bell pepper"], "steps": ["Slice and eat."], "tip": "Pair with guacamole.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "string-cheese-jerky", "title": "String Cheese & Jerky", "time": 2, "tag": "High protein", "category": "Snacks", "servings": "1 serving", "blurb": "Double protein grab-bag.", "ingredients": ["1 string cheese", "1 oz jerky"], "steps": ["Eat."], "tip": "Solid travel combo.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "overnight-oats-snack", "title": "Mini Overnight Oats", "time": 5, "tag": "Prep-ahead", "category": "Snacks", "servings": "1 small jar", "blurb": "Smaller portion for snack time.", "ingredients": ["1/4 cup oats", "1/2 cup milk", "Chia", "Fruit"], "steps": ["Mix. Refrigerate."], "tip": "Keeps hunger quiet before dinner.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["meal-prep", "quick"]},
  {"id": "bone-broth-snack", "title": "Warm Broth", "time": 5, "tag": "Light", "category": "Snacks", "servings": "1 cup", "blurb": "Warm, savory, settling.", "ingredients": ["1 cup broth"], "steps": ["Heat and sip."], "tip": "Add miso for depth.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
];
