import type { Recipe } from "./types";

export const SNACKS_PART_0: Recipe[] = [
  {"id": "almonds-handful", "title": "Handful of Almonds", "time": 1, "tag": "Healthy fat", "category": "Snacks", "servings": "1 oz", "blurb": "Portion-controlled fat and protein.", "ingredients": ["1 oz almonds (~23 nuts)"], "steps": ["Measure and eat."], "tip": "Pre-portion into bags.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "apple-almond-butter", "title": "Apple & Almond Butter", "time": 3, "tag": "Balanced", "category": "Snacks", "servings": "1 serving", "blurb": "Crunch plus protein and fiber.", "ingredients": ["1 apple", "1 tbsp almond butter"], "steps": ["Slice and dip."], "tip": "Natural almond butter only.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "carrot-hummus", "title": "Carrots & Hummus", "time": 3, "tag": "Fiber", "category": "Snacks", "servings": "1 serving", "blurb": "Crunchy vegetables with plant protein.", "ingredients": ["1 cup carrot sticks", "1/4 cup hummus"], "steps": ["Dip and eat."], "tip": "Add cucumber and peppers.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick", "plant-forward"]},
  {"id": "greek-yogurt-honey", "title": "Greek Yogurt with Honey", "time": 3, "tag": "High protein", "category": "Snacks", "servings": "1 cup", "blurb": "Simple protein snack.", "ingredients": ["3/4 cup Greek yogurt", "1 tsp honey"], "steps": ["Stir and eat."], "tip": "Plain yogurt + honey beats flavored cups.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "mediterranean", "quick"]},
  {"id": "hard-boiled-eggs", "title": "Hard-Boiled Eggs", "time": 15, "tag": "Protein", "category": "Snacks", "servings": "2 eggs", "blurb": "Make a batch; snack all week.", "ingredients": ["Eggs", "Salt"], "steps": ["Boil 10 min. Ice bath. Peel."], "tip": "Store peeled in water.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "meal-prep", "quick"]},
  {"id": "rice-cake-pb", "title": "Rice Cake with Peanut Butter", "time": 3, "tag": "Fast fuel", "category": "Snacks", "servings": "1 cake", "blurb": "Crunch and protein.", "ingredients": ["1 rice cake", "1 tbsp peanut butter"], "steps": ["Spread and eat."], "tip": "Add banana slices.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["high-protein", "quick"]},
  {"id": "trail-mix-diy", "title": "DIY Trail Mix", "time": 5, "tag": "Portable", "category": "Snacks", "servings": "1/4 cup", "blurb": "Nuts, seeds, a little dried fruit.", "ingredients": ["Mixed nuts", "Seeds", "Dried fruit (few pieces)"], "steps": ["Mix. Portion 1/4 cup."], "tip": "Keep dried fruit minority.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "celery-pb", "title": "Celery & Peanut Butter", "time": 3, "tag": "Classic", "category": "Snacks", "servings": "1 serving", "blurb": "Crunch and protein.", "ingredients": ["Celery sticks", "1-2 tbsp peanut butter"], "steps": ["Fill and eat."], "tip": "Add raisins if you want ants-on-a-log.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "cheese-stick", "title": "Cheese Stick & Fruit", "time": 2, "tag": "Protein", "category": "Snacks", "servings": "1 serving", "blurb": "Grab-and-go dairy protein.", "ingredients": ["1 cheese stick", "1 piece fruit"], "steps": ["Eat together."], "tip": "Pair with an apple.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "roasted-chickpeas", "title": "Roasted Chickpeas", "time": 30, "tag": "Crunchy", "category": "Snacks", "servings": "2 servings", "blurb": "Crispy, seasoned, addictive.", "ingredients": ["1 can chickpeas", "Oil", "Spices"], "steps": ["Dry well. Roast 400F 25-30 min."], "tip": "Dryness = crispiness.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["mediterranean", "plant-forward"]},
];
