import type { Recipe } from "./types";

export const SNACKS_PART_1: Recipe[] = [
  {"id": "edamame-snack", "title": "Edamame Snack", "time": 5, "tag": "Plant protein", "category": "Snacks", "servings": "1 cup", "blurb": "Salty, satisfying, high protein.", "ingredients": ["1 cup edamame", "Sea salt"], "steps": ["Steam. Salt."], "tip": "Buy frozen in pods or shelled.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick", "plant-forward"]},
  {"id": "protein-bar-check", "title": "Quality Protein Bar", "time": 1, "tag": "Portable", "category": "Snacks", "servings": "1 bar", "blurb": "Only if ingredients are short and sensible.", "ingredients": ["1 protein bar with clean label"], "steps": ["Eat."], "tip": "Watch sugar alcohols if they bother you.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "cucumber-tzatziki", "title": "Cucumber & Tzatziki", "time": 5, "tag": "Cooling", "category": "Snacks", "servings": "1 serving", "blurb": "Fresh crunch with yogurt dip.", "ingredients": ["Cucumber", "1/4 cup tzatziki"], "steps": ["Dip."], "tip": "Make tzatziki: yogurt, cucumber, garlic, dill.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["mediterranean", "quick"]},
  {"id": "turkey-roll-mustard", "title": "Turkey Mustard Rolls", "time": 5, "tag": "High protein", "category": "Snacks", "servings": "4 rolls", "blurb": "Deli turkey with mustard.", "ingredients": ["Turkey slices", "Mustard"], "steps": ["Roll and eat."], "tip": "Add a cheese slice if needed.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "berry-handful", "title": "Fresh Berries", "time": 2, "tag": "Antioxidants", "category": "Snacks", "servings": "1 cup", "blurb": "Sweet without the crash.", "ingredients": ["1 cup berries"], "steps": ["Wash and eat."], "tip": "Frozen works thawed.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["quick"]},
  {"id": "olives-handful", "title": "Olives", "time": 2, "tag": "Healthy fat", "category": "Snacks", "servings": "10 olives", "blurb": "Salty Mediterranean snack.", "ingredients": ["~10 olives"], "steps": ["Eat."], "tip": "Rinse if very briny.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["mediterranean", "quick"]},
  {"id": "popcorn-air", "title": "Air-Popped Popcorn", "time": 5, "tag": "Volume", "category": "Snacks", "servings": "3 cups", "blurb": "High volume, low calorie density.", "ingredients": ["1/4 cup kernels", "Salt"], "steps": ["Pop. Season."], "tip": "Avoid heavy movie-theater butter.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["quick"]},
  {"id": "cottage-pineapple", "title": "Cottage Cheese & Pineapple", "time": 3, "tag": "High protein", "category": "Snacks", "servings": "1 bowl", "blurb": "Sweet-savory protein bowl.", "ingredients": ["3/4 cup cottage cheese", "1/2 cup pineapple"], "steps": ["Combine."], "tip": "Use canned in juice, not syrup.", "macros": {"protein": 18, "carbs": 20, "fat": 14, "calories": 278}, "diet": ["high-protein", "quick"]},
  {"id": "beef-jerky-quality", "title": "Quality Beef Jerky", "time": 2, "tag": "Portable protein", "category": "Snacks", "servings": "1 oz", "blurb": "Shelf-stable protein for the bag.", "ingredients": ["1 oz jerky with short ingredient list"], "steps": ["Eat."], "tip": "Watch sodium.", "macros": {"protein": 18, "carbs": 20, "fat": 12, "calories": 260}, "diet": ["high-protein", "quick"]},
  {"id": "dark-chocolate-almonds", "title": "Dark Chocolate & Almonds", "time": 2, "tag": "Satisfying", "category": "Snacks", "servings": "1 serving", "blurb": "Small sweet with fat and protein.", "ingredients": ["2 squares dark chocolate (70%+)", "10 almonds"], "steps": ["Eat together slowly."], "tip": "Portion before you start.", "macros": {"protein": 8, "carbs": 20, "fat": 14, "calories": 238}, "diet": ["high-protein", "quick"]},
];
