"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Bookmark, Headphones, Search } from "lucide-react";
import { PageHero } from "@/components/layout/page-hero";
import { DESKS, WIKI, type WikiDesk } from "@/lib/wiki";

const PALETTE = ["#0F7FFF", "#FCF927", "#F93827", "#F61981", "#9A00FF", "#4DFF00", "#FF9D23"];
const SAVED_KEY = "livv-mind-saved-v1";
function colorFor(slug: string) { let n = 0; for (const ch of slug) n = (n * 31 + ch.charCodeAt(0)) >>> 0; return PALETTE[n % PALETTE.length]; }
function readSaved() { try { const raw = window.localStorage.getItem(SAVED_KEY); return raw ? JSON.parse(raw) as string[] : []; } catch { return []; } }

export default function MindPage() {
  const [desk, setDesk] = useState<WikiDesk | "all">("all");
  const [query, setQuery] = useState("");
  const [saved, setSaved] = useState<string[]>([]);
  useEffect(() => setSaved(readSaved()), []);
  const list = useMemo(() => { const q = query.trim().toLowerCase(); return WIKI.filter((a) => (desk === "all" || a.desk === desk) && (!q || a.title.toLowerCase().includes(q) || a.hook.toLowerCase().includes(q))); }, [desk, query]);
  const featured = list[0] || WIKI[0];
  const save = (slug: string) => setSaved((current) => { const next = current.includes(slug) ? current.filter((x) => x !== slug) : [...current, slug]; try { window.localStorage.setItem(SAVED_KEY, JSON.stringify(next)); } catch {} return next; });
  return <main className="livv-page relative min-h-full overflow-hidden pb-16 text-white"><div className="relative z-10 mx-auto max-w-xl px-5 pt-5">
    <PageHero eyebrow="Mind" title="The Field" subtitle="Original LIVV reads for clearer thinking, better habits, and a life you can actually use." accent="#F61981" right={<Headphones size={20} className="text-[#F61981]" />} />
    <section className="mt-6 rounded-[30px] border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl border border-[#F61981]/25 bg-[#F61981]/[0.06] text-[#F61981]"><Headphones size={18} /></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#F61981]">LIVV reading room</p><p className="mt-1 text-[13px] text-white/65">Read one idea. Sit with it. Then use it.</p></div></div><div className="relative mt-5"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/40"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search LIVV articles" aria-label="Search LIVV articles" className="w-full rounded-2xl border border-white/10 bg-black/15 py-3 pl-10 pr-4 text-[13px] text-white outline-none placeholder:text-white/35 focus:border-[#F61981]/45" /></div></section>
    <div className="mt-5 flex gap-2 overflow-x-auto pb-1 scrollbar-none" role="tablist" aria-label="Mind categories"><button type="button" onClick={() => setDesk("all")} role="tab" aria-selected={desk === "all"} className={`shrink-0 rounded-full px-3 py-2 text-[11px] font-semibold ${desk === "all" ? "bg-white text-black" : "border border-white/10 bg-white/[0.03] text-white/55"}`}>All</button>{DESKS.map((d, i) => <button key={d.id} type="button" onClick={() => setDesk(d.id)} role="tab" aria-selected={desk === d.id} className={`shrink-0 rounded-full px-3 py-2 text-[11px] font-semibold ${desk === d.id ? "text-black" : "border border-white/10 bg-white/[0.03] text-white/55"}`} style={desk === d.id ? { background: PALETTE[(i + 1) % PALETTE.length] } : undefined}>{d.label}</button>)}</div>
    <Link href={`/home/mind/${featured.slug}`} className="group relative mt-7 block overflow-hidden rounded-[32px] border p-6 active:scale-[0.985]" style={{ borderColor: `${colorFor(featured.slug)}55`, background: `linear-gradient(145deg,${colorFor(featured.slug)}12,rgba(255,255,255,.025))` }}><div className="relative"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[0.2em]" style={{ color: colorFor(featured.slug) }}>Continue reading</span><span className="text-[10px] uppercase tracking-[0.16em] text-white/45">{featured.readMins} min</span></div><h2 className="font-display mt-5 max-w-[15ch] text-[31px] font-semibold leading-[1.02] tracking-tight">{featured.title}</h2><p className="mt-3 max-w-[35ch] text-[14px] leading-relaxed text-white/65">{featured.hook}</p><div className="mt-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-white text-black">→</span><span className="text-[11px] font-semibold text-white/60">Open the article</span></div></div></Link>
    <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-white/45">For you</p><h2 className="font-display mt-1 text-[25px] font-semibold">Keep going.</h2></div><span className="text-[10px] text-white/40">{list.length} reads</span></div><div className="mt-4 space-y-3">{list.slice(1).map((a, i) => { const c = colorFor(a.slug); const isSaved = saved.includes(a.slug); return <article key={a.slug} className="rounded-[25px] border border-white/10 bg-white/[0.025] p-4" style={{ boxShadow: `inset 2px 0 0 ${c}` }}><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl" style={{ background: `${c}12`, color: c }}><span className="text-[10px] font-bold">{String(i + 2).padStart(2, "0")}</span></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-[9px] font-semibold uppercase tracking-[0.16em]" style={{ color: c }}>{a.desk}</span><span className="text-[9px] text-white/40">{a.readMins} min</span></div><Link href={`/home/mind/${a.slug}`} className="mt-1 block text-[16px] font-semibold leading-snug">{a.title}</Link><p className="mt-1 text-[11px] leading-relaxed text-white/50">{a.hook}</p></div><button type="button" onClick={() => save(a.slug)} aria-label={isSaved ? "Remove bookmark" : "Save article"} aria-pressed={isSaved} className="grid h-9 w-9 shrink-0 place-items-center rounded-full border border-white/10 text-white/45"><Bookmark size={15} fill={isSaved ? "currentColor" : "none"} /></button></div></article>; })}</div></section>
    <section className="mt-9 rounded-[28px] border border-white/10 bg-white/[0.025] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#F61981]">How to use this</p><p className="mt-2 text-[13px] leading-relaxed text-white/65">Do not race through the Field. Read the idea, take the useful part, and put it into motion. The goal is a better decision after the article, not a higher article count.</p></section>
    {saved.length > 0 && <p className="mt-5 text-center text-[10px] uppercase tracking-[0.18em] text-white/35">{saved.length} article{saved.length === 1 ? "" : "s"} saved</p>}
  </div></main>;
}
