import { NextRequest, NextResponse } from "next/server";
import { getStripe, tierFromPriceId, type PaidTier } from "@/lib/stripe-server";
import { effectiveTier, findUserIdByCustomerId, findUserIdBySubscriptionId, mapSubscriptionStatus, recordPackPurchase, recordWebhookEvent, resolveLivvUserId, tierFromSubscription, upsertEntitlement } from "@/lib/stripe-entitlements";
import { getSupabaseAdmin, isSupabaseAdminConfigured } from "@/lib/supabase/admin";
import type Stripe from "stripe";
export const runtime="nodejs";
export async function POST(req:NextRequest){const stripe=getStripe(),secret=process.env.STRIPE_WEBHOOK_SECRET;if(!stripe||!secret)return NextResponse.json({error:"Webhook not configured"},{status:503});const signature=req.headers.get("stripe-signature");if(!signature)return NextResponse.json({error:"No signature"},{status:400});const rawBody=await req.text();let event:Stripe.Event;try{event=stripe.webhooks.constructEvent(rawBody,signature,secret);}catch{return NextResponse.json({error:"Invalid signature"},{status:400});}if(!isSupabaseAdminConfigured())return NextResponse.json({received:true,fulfilled:false});try{const admin=getSupabaseAdmin();if(admin){const{data:existing}=await admin.from("stripe_webhook_events").select("event_id").eq("event_id",event.id).maybeSingle();if(existing?.event_id)return NextResponse.json({received:true,duplicate:true});}switch(event.type){case"checkout.session.completed":await handleCheckoutCompleted(stripe,event.data.object as Stripe.Checkout.Session);break;case"customer.subscription.created":case"customer.subscription.updated":case"customer.subscription.paused":case"customer.subscription.resumed":await handleSubscriptionUpdated(event.data.object as Stripe.Subscription);break;case"customer.subscription.deleted":await handleSubscriptionDeleted(event.data.object as Stripe.Subscription);break;}const recorded=await recordWebhookEvent(event.id,event.type);return NextResponse.json({received:true,duplicate:!recorded});}catch(err){console.error("[stripe/webhook] handler",err);return NextResponse.json({error:"Handler failed"},{status:500});}}
async function handleCheckoutCompleted(stripe:Stripe,session:Stripe.Checkout.Session){const userId=resolveLivvUserId({metadata:session.metadata,clientReferenceId:session.client_reference_id});if(session.mode==="payment"){if(session.payment_status!=="paid"||!userId)return;const grade=Number(session.metadata?.livv_grade||0),quantity=Number(session.metadata?.livv_qty||0);if(!Number.isInteger(grade)||grade<1||grade>4||!Number.isInteger(quantity)||quantity<1||quantity>10)return;const customerId=typeof session.customer==="string"?session.customer:session.customer?.id||null;await recordPackPurchase({userId,stripeSessionId:session.id,stripeCustomerId:customerId,grade,quantity});return;}if(!userId)return;let tier:PaidTier|null=(session.metadata?.livv_tier as PaidTier|undefined)||null;const subscriptionId=typeof session.subscription==="string"?session.subscription:session.subscription?.id||null;let customerId=typeof session.customer==="string"?session.customer:session.customer?.id||null;let status:ReturnType<typeof mapSubscriptionStatus>="active",periodEnd:string|null=null;if(subscriptionId){try{const sub=await stripe.subscriptions.retrieve(subscriptionId);status=mapSubscriptionStatus(sub.status);const mapped=tierFromSubscription(sub);if(mapped!=="spark")tier=mapped as PaidTier;else if(!tier)tier=tierFromPriceId(sub.items.data[0]?.price?.id);customerId=typeof sub.customer==="string"?sub.customer:sub.customer?.id||customerId;periodEnd=sub.current_period_end?new Date(sub.current_period_end*1000).toISOString():null;}catch(err){console.error("[stripe/webhook] retrieve subscription",err);}}if(!tier)return;await upsertEntitlement({userId,tier:effectiveTier(status,tier),status,stripeCustomerId:customerId,stripeSubscriptionId:subscriptionId,currentPeriodEnd:periodEnd});}
async function resolveSubscriptionUserId(sub:Stripe.Subscription){let userId=resolveLivvUserId({metadata:sub.metadata});const customerId=typeof sub.customer==="string"?sub.customer:sub.customer?.id||null;if(!userId)userId=await findUserIdBySubscriptionId(sub.id);if(!userId&&customerId)userId=await findUserIdByCustomerId(customerId);return userId;}
async function handleSubscriptionUpdated(sub:Stripe.Subscription){const userId=await resolveSubscriptionUserId(sub);if(!userId)return;const status=mapSubscriptionStatus(sub.status),mapped=tierFromSubscription(sub),tier=effectiveTier(status,mapped),customerId=typeof sub.customer==="string"?sub.customer:sub.customer?.id||null,periodEnd=sub.current_period_end?new Date(sub.current_period_end*1000).toISOString():null;await upsertEntitlement({userId,tier,status,stripeCustomerId:customerId,stripeSubscriptionId:sub.id,currentPeriodEnd:periodEnd});}
async function handleSubscriptionDeleted(sub:Stripe.Subscription){const userId=await resolveSubscriptionUserId(sub);if(!userId)return;const customerId=typeof sub.customer==="string"?sub.customer:sub.customer?.id||null;await upsertEntitlement({userId,tier:"spark",status:"canceled",stripeCustomerId:customerId,stripeSubscriptionId:sub.id,currentPeriodEnd:sub.current_period_end?new Date(sub.current_period_end*1000).toISOString():null});}