"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { PageHero } from "@/components/layout/page-hero";
import { livePillars, loadRecord, weekBars, weekHitCount, type LivvRecord } from "@/lib/record";
import { evolutionTitle } from "@/lib/levels";
import { needsAttention, strongestPillar } from "@/lib/command";
import { buildProgressInsights } from "@/lib/progress-insights";

const COLORS: Record<string,string> = { Body:"#F93827", Mind:"#F61981", Career:"#FF9D23", Finance:"#9A00FF", Social:"#4DFF00", Life:"#FCF927" };
export default function ProgressPage(){
 const [rec,setRec]=useState<LivvRecord|null>(null); const sync=()=>setRec(loadRecord());
 useEffect(()=>{sync();const events=["livv-record","livv-daily","livv-billing","livv-identity"];events.forEach(e=>window.addEventListener(e,sync));return()=>events.forEach(e=>window.removeEventListener(e,sync));},[]);
 const insights=useMemo(()=>rec?buildProgressInsights(rec,14):null,[rec]);
 if(!rec||!insights)return <main className="min-h-dvh"/>;
 const week=weekBars(rec), hits=weekHitCount(rec), pillars=livePillars(rec), evo=evolutionTitle(rec.level), strong=strongestPillar(rec), weak=needsAttention(rec), pct=Math.min(100,Math.round(rec.currentXp/Math.max(1,rec.xpToNext)*100));
 return <main className="livv-page relative min-h-full overflow-hidden pb-14 text-white"><div className="relative z-10 mx-auto max-w-xl px-5 pt-5"><PageHero eyebrow="Progress" title="Is your life getting better?" subtitle="Progress is what your recorded actions say, not what a badge says." accent="#0F7FFF"/>
  <section className="livv-glass mt-7 rounded-[30px] p-6"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-white/45">Current evolution</p><h2 className="font-display mt-2 text-[28px]">{evo.name}</h2></div><div className="text-right"><p className="text-[9px] uppercase tracking-[.2em] text-white/40">Level</p><p className="font-display text-[30px] text-[#0F7FFF]">{rec.level}</p></div></div><p className="mt-2 text-[12px] leading-relaxed text-white/60">{evo.line}</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/[.08]"><div className="h-full rounded-full bg-[#0F7FFF]" style={{width:`${pct}%`}}/></div><p className="mt-2 text-right text-[10px] text-white/40">{rec.currentXp} / {rec.xpToNext} XP</p></section>
  <section className="mt-7 grid grid-cols-3 gap-2"><Stat value={`${insights.consistencyPct}%`} label="14d active"/><Stat value={`${insights.longestActiveRun}d`} label="best run"/><Stat value={`${insights.objectivesCompletedInWindow}`} label="actions"/></section>
  <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-white/40">This week</p><h2 className="font-display mt-1 text-[23px]">Consistency</h2></div><span className="text-[11px] text-white/45">{hits}/7 active</span></div><div className="mt-5 flex items-end gap-2">{week.map((d:any)=><div key={d.key} className="flex flex-1 flex-col items-center gap-2"><div className="relative h-20 w-full overflow-hidden rounded-xl bg-white/[.05]"><div className="absolute bottom-0 w-full rounded-xl bg-[#0F7FFF]/75" style={{height:`${Math.max(8,d.v)}%`}}/></div><span className="text-[9px] text-white/40">{d.d}</span></div>)}</div></section>
  <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-white/40">Six areas</p><h2 className="font-display mt-1 text-[23px]">Where your life is moving.</h2></div></div><div className="mt-4 space-y-3">{pillars.map((p:any)=><div key={p.id} className="rounded-[24px] border border-white/10 bg-white/[.025] p-4"><div className="flex items-center justify-between"><div><p className="text-[14px] font-semibold">{p.name}</p><p className="mt-1 text-[10px] text-white/40">Level {p.level} · {p.xp} XP</p></div><span className="h-2.5 w-2.5 rounded-full" style={{background:COLORS[p.name]||"#0F7FFF"}}/></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/[.08]"><div className="h-full rounded-full" style={{width:`${p.progress}%`,background:COLORS[p.name]||"#0F7FFF"}}/></div></div>)}</div></section>
  <section className="mt-10"><p className="text-[10px] uppercase tracking-[.25em] text-white/40">What the evidence says</p><div className="mt-4 space-y-3">{insights.bullets.slice(0,4).map((b)=><div key={b.title} className="rounded-[24px] border border-white/10 bg-white/[.025] p-5"><p className="text-[9px] uppercase tracking-[.2em] text-white/40">{b.title}</p><p className="mt-2 text-[15px] font-medium leading-snug text-white/85">{b.detail}</p><p className="mt-2 text-[10px] leading-relaxed text-white/40">{b.evidence.facts.slice(0,3).join(" · ")}</p></div>)}</div></section>
  <section className="mt-10 grid grid-cols-2 gap-3"><div className="rounded-[24px] border border-white/10 bg-white/[.025] p-4"><p className="text-[9px] uppercase tracking-[.2em] text-white/40">Leading area</p><p className="mt-3 text-[18px] font-semibold">{strong.name}</p><p className="mt-1 text-[11px] text-white/40">Level {strong.level}</p></div><div className="rounded-[24px] border border-white/10 bg-white/[.025] p-4"><p className="text-[9px] uppercase tracking-[.2em] text-white/40">Needs attention</p><p className="mt-3 text-[18px] font-semibold">{weak.name}</p><p className="mt-1 text-[11px] text-white/40">Level {weak.level}</p></div></section>
  <Link href="/home/evala" className="mt-10 flex items-center justify-between rounded-[24px] border border-white/10 bg-white/[.025] p-5"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#0F7FFF]">Next step</p><p className="mt-1 text-[15px] font-semibold">Ask Evala what to improve next.</p></div><span className="text-white/45">→</span></Link>
 </div></main>;
}
function Stat({value,label}:{value:string;label:string}){return <div className="rounded-[22px] border border-white/10 bg-white/[.025] p-4"><p className="font-display text-[20px]">{value}</p><p className="mt-1 text-[9px] uppercase tracking-[.16em] text-white/45">{label}</p></div>}
