"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Brain, ChevronLeft, Pause, Play, RotateCcw, Wind } from "lucide-react";

const PRACTICES = [
  { name:"Reset", minutes:3, purpose:"Downshift quickly when your mind is noisy.", steps:["Sit comfortably and let your shoulders drop.","Breathe in gently through your nose.","Let the exhale be slow and unforced.","Notice what is happening without fixing it.","Choose one useful next action."] },
  { name:"Focus", minutes:5, purpose:"Create a clean transition into work, study, or training.", steps:["Sit upright and put the phone down.","Notice five slow breaths.","When attention wanders, return to the breath.","Name the single task you are about to do.","Begin without checking anything else."] },
  { name:"Night", minutes:10, purpose:"Create a quieter landing before sleep.", steps:["Dim the room and get comfortable.","Relax the face, jaw, shoulders, and hands.","Let breathing become natural.","Notice sensations without judging them.","When thoughts arrive, return to the next breath."] },
] as const;

export default function MeditationPage(){
 const [idx,setIdx]=useState(0),[sec,setSec]=useState(PRACTICES[0].minutes*60),[run,setRun]=useState(false),[done,setDone]=useState(0);
 const item=PRACTICES[idx];
 useEffect(()=>{if(!run)return;const id=setInterval(()=>setSec(v=>{if(v<=1){setRun(false);setDone(n=>n+1);return 0}return v-1}),1000);return()=>clearInterval(id)},[run]);
 function choose(i:number){setIdx(i);setSec(PRACTICES[i].minutes*60);setRun(false)}
 const mm=String(Math.floor(sec/60)).padStart(2,"0"),ss=String(sec%60).padStart(2,"0");
 return <main className="livv-page min-h-full"><div className="mx-auto w-full max-w-xl px-5 pb-14 sm:px-6">
  <header className="pt-6 sm:pt-9"><Link href="/home/health" className="inline-flex items-center gap-1 text-[10px] font-semibold uppercase tracking-[.18em] text-livv-muted"><ChevronLeft size={13}/> Health</Link><div className="mt-7 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.2em] text-livv-accent"><Brain size={13}/> Mind</div><h1 className="mt-2 text-[40px] font-semibold leading-[.96] tracking-[-.06em] sm:text-[48px]">Make space.</h1><p className="mt-4 max-w-[42ch] text-[13px] leading-6 text-livv-muted">Meditation is not about emptying your mind. It is practice in noticing attention, creating a pause, and choosing where to put your focus.</p></header>
  <div className="mt-9 grid grid-cols-3 gap-2">{PRACTICES.map((x,i)=><button key={x.name} type="button" onClick={()=>choose(i)} className={`rounded-2xl border p-4 text-left ${idx===i?"border-livv-accent bg-livv-accent-soft":"border-livv-border"}`}><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-livv-muted">{x.minutes} min</p><p className="mt-2 text-[14px] font-semibold">{x.name}</p></button>)}</div>
  <section className="mt-7 border-y border-livv-border py-9 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-livv-border text-livv-muted"><Wind size={19}/></div><p className="mt-5 text-[11px] leading-5 text-livv-muted">{item.purpose}</p><p className="mt-3 text-[clamp(4rem,20vw,7rem)] font-semibold leading-none tracking-[-.08em] tabular-nums">{mm}:{ss}</p><div className="mt-7 flex justify-center gap-2"><button type="button" onClick={()=>setRun(v=>!v)} className="inline-flex min-w-28 items-center justify-center gap-2 rounded-full bg-livv-ink px-7 py-3.5 text-[10px] font-semibold uppercase tracking-[.14em] text-livv-bg">{run?<><Pause size={14}/> Pause</>:<><Play size={14}/> {sec===0?"Done":"Start"}</>}</button><button type="button" onClick={()=>{setSec(item.minutes*60);setRun(false)}} className="inline-flex items-center justify-center gap-2 rounded-full border border-livv-border px-5 py-3.5 text-[10px] font-semibold uppercase tracking-[.14em] text-livv-muted"><RotateCcw size={14}/> Reset</button></div><p className="mt-4 text-[10px] text-livv-muted">Completed this session: {done}</p></section>
  <section className="mt-10"><p className="text-[10px] font-semibold uppercase tracking-[.19em] text-livv-muted">Practice</p><h2 className="mt-1 text-[26px] font-semibold tracking-[-.045em]">{item.name}, step by step.</h2><div className="mt-5 divide-y divide-livv-border border-y border-livv-border">{item.steps.map((s,i)=><div key={s} className="flex gap-4 py-5"><span className="w-7 shrink-0 text-[10px] font-semibold tabular-nums text-livv-accent">{String(i+1).padStart(2,"0")}</span><p className="text-[13px] leading-6">{s}</p></div>)}</div></section>
  <section className="mt-10"><p className="text-[10px] font-semibold uppercase tracking-[.19em] text-livv-muted">Make it useful</p><div className="mt-4 space-y-4"><Guide title="Start small" text="Three minutes done consistently is more useful than a twenty-minute session you never start."/><Guide title="Do not chase a feeling" text="The point is practice. Wandering attention is not failure; noticing it and returning is the repetition."/><Guide title="Carry it forward" text="When the timer ends, immediately do one deliberate thing. The pause should change what happens next." /></div></section>
 </div></main>;
}
function Guide({title,text}:{title:string;text:string}){return <div className="border-b border-livv-border pb-4"><h3 className="text-[14px] font-semibold">{title}</h3><p className="mt-1 text-[12px] leading-5 text-livv-muted">{text}</p></div>}
