-- Server-authoritative ledger for one-time LIVV pack purchases.
-- Each Stripe Checkout session can fulfill at most once.
create table if not exists public.pack_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_session_id text not null unique,
  stripe_customer_id text,
  grade integer not null check (grade between 1 and 4),
  quantity integer not null default 1 check (quantity between 1 and 10),
  status text not null default 'paid' check (status in ('paid','refunded','disputed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pack_purchases_user_id_idx on public.pack_purchases(user_id);

alter table public.pack_purchases enable row level security;

drop policy if exists "members can read own pack purchases" on public.pack_purchases;
create policy "members can read own pack purchases"
  on public.pack_purchases for select
  to authenticated
  using (user_id = auth.uid());

revoke all on public.pack_purchases from anon;
revoke insert, update, delete on public.pack_purchases from authenticated;
grant select on public.pack_purchases to authenticated;

create or replace function public.set_pack_purchases_updated_at()
returns trigger language plpgsql security invoker as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pack_purchases_updated_at on public.pack_purchases;
create trigger pack_purchases_updated_at
before update on public.pack_purchases
for each row execute function public.set_pack_purchases_updated_at();
