-- Membership V1: real tier-controlled themes and server-authoritative Ember awards.
alter table public.profiles
  add column if not exists theme text not null default 'ember';

alter table public.profiles
  drop constraint if exists profiles_theme_check;

alter table public.profiles
  add constraint profiles_theme_check
  check (theme = any (array['ember'::text,'midnight'::text,'bone'::text]));

create table if not exists private.ember_awards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null unique,
  base_amount integer not null check (base_amount > 0 and base_amount <= 150),
  multiplier integer not null check (multiplier in (1,2,4,6)),
  awarded_amount integer not null check (awarded_amount > 0),
  created_at timestamptz not null default now()
);

alter table private.ember_awards enable row level security;
revoke all on table private.ember_awards from public, anon, authenticated;

create index if not exists ember_awards_user_created_idx
  on private.ember_awards (user_id, created_at desc);

create or replace function public.grant_embers(
  p_user_id uuid,
  p_event_key text,
  p_base_amount integer
)
returns table(awarded integer, total integer, tier text, multiplier integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tier text := 'spark';
  v_status text := 'none';
  v_multiplier integer := 1;
  v_awarded integer := 0;
  v_total integer := 0;
begin
  if p_user_id is null then raise exception 'user id required'; end if;
  if p_event_key is null or length(trim(p_event_key)) < 8 or length(p_event_key) > 120 then raise exception 'invalid event key'; end if;
  if p_base_amount is null or p_base_amount <= 0 or p_base_amount > 150 then raise exception 'invalid ember amount'; end if;

  select coalesce(e.tier, 'spark'), coalesce(e.status, 'none')
    into v_tier, v_status
  from public.entitlements e
  where e.user_id = p_user_id;

  if v_status not in ('active','trialing','past_due') then v_tier := 'spark'; end if;

  v_multiplier := case v_tier
    when 'circle' then 6
    when 'apex' then 4
    when 'rise' then 2
    else 1
  end;

  insert into private.ember_awards (user_id,event_key,base_amount,multiplier,awarded_amount)
  values (p_user_id,trim(p_event_key),p_base_amount,v_multiplier,p_base_amount*v_multiplier)
  on conflict (event_key) do nothing;

  if found then
    v_awarded := p_base_amount * v_multiplier;
    update public.profiles
      set embers = greatest(0, coalesce(embers,0) + v_awarded), updated_at = now()
    where id = p_user_id
    returning embers into v_total;
  else
    select coalesce(p.embers,0) into v_total from public.profiles p where p.id=p_user_id;
  end if;

  if v_total is null then raise exception 'profile not found'; end if;
  return query select v_awarded,v_total,v_tier,v_multiplier;
end;
$$;

revoke execute on function public.grant_embers(uuid,text,integer) from public, anon, authenticated;
grant execute on function public.grant_embers(uuid,text,integer) to service_role;

create or replace function private.protect_membership_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_tier text := 'spark';
  v_status text := 'none';
  v_rank integer := 0;
begin
  if v_uid is null then return new; end if;

  if new.tier is distinct from old.tier or new.embers is distinct from old.embers then
    raise exception 'membership-controlled fields are server managed';
  end if;

  if new.accent is distinct from old.accent or new.theme is distinct from old.theme then
    select coalesce(e.tier,'spark'),coalesce(e.status,'none')
      into v_tier,v_status
    from public.entitlements e where e.user_id=v_uid;

    if v_status not in ('active','trialing','past_due') then v_tier := 'spark'; end if;

    v_rank := case v_tier when 'circle' then 3 when 'apex' then 2 when 'rise' then 1 else 0 end;
    if new.accent is distinct from old.accent and v_rank < 1 then
      raise exception 'accent customization requires Rise or above';
    end if;
    if new.theme is distinct from old.theme and v_rank < 2 then
      raise exception 'app themes require Apex or above';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists protect_membership_fields on public.profiles;
create trigger protect_membership_fields
before update on public.profiles
for each row execute function private.protect_membership_fields();

revoke execute on function private.protect_membership_fields() from public, anon, authenticated;
