-- Ember redemption ledger + server-side burn for Collection checkout.
-- Client never decides the final burn amount.

create table if not exists private.ember_redemptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id text not null,
  embers_applied integer not null check (embers_applied > 0),
  credit_cents integer not null check (credit_cents > 0),
  subtotal_cents integer not null check (subtotal_cents > 0),
  created_at timestamptz not null default now(),
  unique (order_id)
);

create index if not exists ember_redemptions_user_idx
  on private.ember_redemptions (user_id, created_at desc);

alter table private.ember_redemptions enable row level security;
revoke all on table private.ember_redemptions from public, anon, authenticated;

create or replace function public.redeem_embers(
  p_user_id uuid,
  p_order_id text,
  p_subtotal_cents integer,
  p_embers_requested integer,
  p_embers_per_dollar integer,
  p_min_redeem integer,
  p_max_credit_dollars integer,
  p_max_fraction numeric
)
returns table(applied integer, total integer, credit_cents integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_balance integer := 0;
  v_want integer := 0;
  v_max_by_fraction integer := 0;
  v_max_by_cap integer := 0;
  v_max_credit_cents integer := 0;
  v_max_embers integer := 0;
  v_applied integer := 0;
  v_credit_dollars integer := 0;
  v_credit_cents integer := 0;
  v_total integer := 0;
begin
  if p_user_id is null then raise exception 'user id required'; end if;
  if p_order_id is null or length(trim(p_order_id)) < 8 then raise exception 'invalid order'; end if;
  if p_subtotal_cents is null or p_subtotal_cents < 100 then raise exception 'invalid subtotal'; end if;
  if p_embers_per_dollar is null or p_embers_per_dollar < 50 then raise exception 'invalid rate'; end if;
  if p_min_redeem is null or p_min_redeem < 100 then raise exception 'invalid minimum'; end if;

  -- Idempotent: same order cannot burn twice
  if exists (select 1 from private.ember_redemptions r where r.order_id = trim(p_order_id)) then
    raise exception 'already redeemed for order';
  end if;

  select coalesce(p.embers, 0) into v_balance
  from public.profiles p where p.id = p_user_id for update;

  if v_balance is null then raise exception 'profile not found'; end if;
  if v_balance < p_min_redeem then raise exception 'below minimum'; end if;

  v_want := coalesce(p_embers_requested, v_balance);
  if v_want < 0 then v_want := 0; end if;
  if v_want > v_balance then v_want := v_balance; end if;

  v_max_by_fraction := floor(p_subtotal_cents * p_max_fraction)::integer;
  v_max_by_cap := p_max_credit_dollars * 100;
  v_max_credit_cents := least(v_max_by_fraction, v_max_by_cap, p_subtotal_cents);
  v_max_embers := (v_max_credit_cents / 100) * p_embers_per_dollar;

  v_applied := least(v_want, v_max_embers);
  -- Whole dollars only
  v_credit_dollars := v_applied / p_embers_per_dollar;
  v_applied := v_credit_dollars * p_embers_per_dollar;
  v_credit_cents := v_credit_dollars * 100;

  if v_applied < p_min_redeem then raise exception 'below minimum after caps'; end if;
  if v_applied > v_balance then raise exception 'insufficient'; end if;

  update public.profiles
    set embers = greatest(0, coalesce(embers, 0) - v_applied),
        updated_at = now()
  where id = p_user_id
  returning embers into v_total;

  insert into private.ember_redemptions (user_id, order_id, embers_applied, credit_cents, subtotal_cents)
  values (p_user_id, trim(p_order_id), v_applied, v_credit_cents, p_subtotal_cents);

  return query select v_applied, v_total, v_credit_cents;
end;
$$;

revoke execute on function public.redeem_embers(uuid, text, integer, integer, integer, integer, integer, numeric)
  from public, anon, authenticated;
grant execute on function public.redeem_embers(uuid, text, integer, integer, integer, integer, integer, numeric)
  to service_role;
