"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import Link from "next/link";
import { ArrowRight, CalendarCheck, ChevronRight, Flame, Pencil, Sparkles, Trophy, Zap } from "lucide-react";
import { Avatar } from "@/components/identity/avatar";
import { PageHero } from "@/components/layout/page-hero";
import { fileToPhoto, loadIdentity, patchIdentity, type Identity } from "@/lib/identity";
import { changeUsername } from "@/lib/auth";
import { loadRecord } from "@/lib/record";
import { evolutionTitle } from "@/lib/levels";
import { collectionStats } from "@/lib/packs";
import { tierColor } from "@/lib/tier-style";
import { getTier } from "@/lib/membership";
import { getEffectiveTier } from "@/lib/billing";
import { feedback } from "@/lib/sensory";

export default function ProfilePage(){
 const [me,setMe]=useState<Identity|null>(null);const [rec,setRec]=useState<ReturnType<typeof loadRecord>|null>(null);const [edit,setEdit]=useState(false);const [name,setName]=useState("");const [username,setUsername]=useState("");const [bio,setBio]=useState("");const [goal,setGoal]=useState("");const [status,setStatus]=useState("");const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const sync=()=>{const id=loadIdentity();setMe(id);setRec(loadRecord());setName(id.displayName);setUsername(id.username);setBio(id.bio);setGoal(id.goal);};sync();for(const e of ["livv-identity","livv-record","livv-packs","livv-billing"])window.addEventListener(e,sync);return()=>{for(const e of ["livv-identity","livv-record","livv-packs","livv-billing"])window.removeEventListener(e,sync);};},[]);
 if(!me||!rec)return <main className="min-h-dvh"/>;
 const evo=evolutionTitle(rec.level);const pct=Math.min(100,Math.round((rec.currentXp/rec.xpToNext)*100));const tc=tierColor(getEffectiveTier());const vault=collectionStats();
 const save=()=>{setStatus("");try{const cleanName=name.trim()||"Member";patchIdentity({displayName:cleanName,bio:bio.trim().slice(0,180),goal:goal.trim().slice(0,120)});if(username.trim().toLowerCase()!==me.username.toLowerCase())changeUsername(username);setMe(loadIdentity());setEdit(false);setStatus("Profile saved.");feedback("complete");}catch(e){setStatus(e instanceof Error?e.message:"Could not save profile.");}};
 const photo=async(file?:File)=>{if(!file)return;try{setMe(patchIdentity({photo:await fileToPhoto(file)}));feedback("tick");}catch{setStatus("Could not update photo.");}};
 return <main className="livv-page relative min-h-full overflow-hidden pb-28 text-white"><div className="relative z-10 mx-auto max-w-xl px-5 pt-5"><PageHero eyebrow="Identity" title="You" subtitle="Your profile, your goals, your place in LIVV." accent="#FF72C9" right={<Link href="/home/settings" aria-label="Settings" className="grid h-10 w-10 place-items-center text-white/60"><Pencil size={16}/></Link>}/>
 <section className="livv-glass relative mt-7 overflow-hidden rounded-[32px] p-6 text-center"><div className="absolute inset-x-10 top-0 h-px" style={{background:`linear-gradient(90deg,transparent,${tc.hex},transparent)`}}/><button type="button" onClick={()=>fileRef.current?.click()} className="relative mx-auto block rounded-full"><Avatar identity={me} size={112} showTierRing/><span className="absolute bottom-0 right-0 grid h-8 w-8 place-items-center rounded-full border-4 border-[#08090b] bg-white text-black"><Sparkles size={13}/></span></button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>void photo(e.target.files?.[0])}/><h1 className="font-display mt-5 text-[31px] font-semibold">{me.displayName||"Member"}</h1><p className="mt-1 text-[14px] text-white/55">@{me.username||"member"}</p>{me.goal&&<p className="mx-auto mt-4 max-w-[32ch] text-[13px] leading-relaxed text-white/70">Goal: {me.goal}</p>}<div className="mt-6 grid grid-cols-3 divide-x divide-white/10 rounded-2xl border border-white/10 bg-black/10 py-4"><Stat value={`${rec.streak}d`} label="streak" icon={<CalendarCheck size={13}/>}/><Stat value={String(rec.level)} label="level" icon={<Zap size={13}/>}/><Stat value={String(me.embers)} label="embers" icon={<Flame size={13}/>}/></div></section>
 <section className="mt-5 rounded-[28px] border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#FF72C9]">Profile details</p><h2 className="font-display mt-1 text-[23px] font-semibold">Make it yours.</h2></div><button type="button" onClick={()=>setEdit(v=>!v)} className="rounded-full border border-white/10 px-3 py-2 text-[10px] font-semibold">{edit?"Close":"Edit"}</button></div>{edit?<div className="mt-5 space-y-3"><Field label="Display name" value={name} onChange={setName} placeholder="Your name"/><Field label="Username" value={`@${username}`} onChange={v=>setUsername(v.replace(/^@/,""))} placeholder="username"/><Field label="Goal" value={goal} onChange={setGoal} placeholder="What are you working toward?"/><label className="block"><span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-white/50">Bio</span><textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={180} placeholder="Tell people a little about you" className="mt-2 min-h-24 w-full resize-none rounded-2xl border border-white/10 bg-black/10 p-3 text-[13px] text-white outline-none placeholder:text-white/35 focus:border-[#FF72C9]/40"/></label><button type="button" onClick={save} className="w-full rounded-full bg-white py-3 text-[13px] font-semibold text-black">Save profile</button>{status&&<p className="text-[11px] leading-relaxed text-[#FF72C9]">{status}</p>}</div>:<div className="mt-5 space-y-3"><Row label="Display name" value={me.displayName||"Not set"}/><Row label="Username" value={`@${me.username||"member"}`}/><Row label="Goal" value={me.goal||"Add a goal"}/><Row label="Bio" value={me.bio||"Add a short bio"}/></div>}</section>
 <section className="mt-5 rounded-[28px] border border-white/10 bg-white/[0.025] p-5"><div className="flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-white/50">Current evolution</p><h2 className="font-display mt-1 text-[26px] font-semibold">{evo.name}</h2></div><span className="text-[11px] text-white/55">{rec.currentXp} / {rec.xpToNext} XP</span></div><p className="mt-1 text-[12px] leading-relaxed text-white/60">{evo.line}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-livv-accent" style={{width:`${pct}%`}}/></div><div className="mt-3 flex justify-between text-[10px] text-white/50"><span>{pct}% to next level</span><Link href="/home/progress" className="text-livv-accent-soft">View progress <ArrowRight size={12} className="inline"/></Link></div></section>
 <div className="mt-4 grid grid-cols-2 gap-3"><Link href="/home/progress" className="rounded-[24px] border border-white/10 bg-white/[0.025] p-4"><Trophy size={18} className="text-livv-accent-soft"/><p className="mt-6 text-[15px] font-semibold">Progress</p><p className="mt-1 text-[11px] text-white/50">Chapters and milestones</p><ChevronRight size={15} className="mt-3 text-white/40"/></Link><Link href="/home/vault" className="rounded-[24px] border border-white/10 bg-white/[0.025] p-4"><Sparkles size={18} className="text-livv-accent-soft"/><p className="mt-6 text-[15px] font-semibold">Vault</p><p className="mt-1 text-[11px] text-white/50">{vault.uniqueCount} of {vault.catalogSize} collected</p><ChevronRight size={15} className="mt-3 text-white/40"/></Link></div>
 <section className="mt-8 rounded-[28px] border border-white/10 bg-white/[0.025] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.2em]" style={{color:tc.hex}}>Membership</p><h2 className="font-display mt-1 text-[24px] font-semibold">{getTier(getEffectiveTier()).name}</h2><p className="mt-2 text-[12px] leading-relaxed text-white/55">Your membership controls access to the parts of LIVV you have earned or purchased.</p><Link href="/home/settings" className="mt-4 flex items-center justify-between rounded-2xl border border-white/10 px-4 py-3 text-[12px] font-semibold">Manage account settings <ChevronRight size={15}/></Link></section>
 </div></main>;
}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="block"><span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-white/50">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/10 px-3 py-3 text-[13px] text-white outline-none placeholder:text-white/35 focus:border-[#FF72C9]/40"/></label>}
function Row({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-black/10 px-4 py-3"><p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-white/45">{label}</p><p className="mt-1 text-[13px] text-white/80">{value}</p></div>}
function Stat({value,label,icon}:{value:string;label:string;icon:ReactNode}){return <div className="flex flex-col items-center gap-1 text-white/70">{icon}<span className="text-[18px] font-semibold">{value}</span><span className="text-[9px] uppercase tracking-[0.16em] text-white/45">{label}</span></div>}
